### PR TITLE
Use "jtr" prefixed fseek & ftell functions to allow larger files

### PR DESCRIPTION
**Pull request by visuve**
- Optimal way would be to use fstat, but will do for now
  - More info: https://wiki.sei.cmu.edu/confluence/display/c/FIO19-C.+Do+not+use+fseek%28%29+and+ftell%28%29+to+compute+the+size+of+a+regular+file

### CODE REVIEW

**Review by solardiz — CHANGES_REQUESTED** [review]
Thanks. I think you also need to upgrade these to an explicitly 64-bit type:

```
long int fp_before_aes = 0, fp_before_salt = 0;
```

`long` is commonly 32-bit on 32-bit systems and on Windows (including 64-bit Windows).

Also, please prefix the commit message title line with `bitlocker2john: ` (yet keep it within 72 chars, perhaps by re-wording the rest of it).

**Comment by solardiz** [comment]
@visuve Have you tested these changes? Perhaps on input that wasn't correctly processed before, but with these changes is?

**Review by solardiz — CHANGES_REQUESTED** [review]
There are still a few `fprintf` that use the `%lx` format on what's now the return value from `jtr_ftell64`. This is incorrect on some systems. One way to fix that for all would be to cast the value passed to `fprintf` to `(unsigned long long)` and to use `%llx`. BTW, I don't understand why we choose to print those offsets in hex - so maybe we should use `%llu` instead (edit: and drop the `0x` prefix).

**Comment by visuve** [comment]
> @visuve Have you tested these changes? Perhaps on input that wasn't correctly processed before, but with these changes is?

@solardiz you could consider this as a first step towards migrating to fstat which should allow passing devices directly e.g. 
``bitlocker2john.exe -i \\.\PHYSICALDRIVE9``



> There are still a few `fprintf` that use the `%lx` format on what's now the return value from `jtr_ftell64`. This is incorrect on some systems. One way to fix that for all would be to cast the value passed to `fprintf` to `(unsigned long long)` and to use `%llx`. BTW, I don't understand why we choose to print those offsets in hex - so maybe we should use `%llu` instead (edit: and drop the `0x` prefix).

@solardiz ``%lld`` to be exact ;-) Personally I think the hex prefix makes sense in offsets that might be huge (e.g. memory or drive), because hex strings are usually easier to remember than long integers. Hence I would not change it. However I will fix them to int64.

**Review by solardiz — APPROVED** [review]
Those `fprintf` are still not exactly right because `jtr_ftell64` won't always return the same type as a `long long`. However, yes, I am OK treating these changes as temporary, and won't insist further.

**Comment by solardiz** [comment]
Actually, no, can't ignore the wrongness of those `fprintf` formats even temporarily - our CI is unhappy:

```
bitlocker2john.c: In function 'rp_search_salt_aes':
bitlocker2john.c:109:19: error: format '%llx' expects argument of type 'long long unsigned int', but argument 3 has type 'int64_t {aka long int}' [-Werror=format=]
   fprintf(stderr, "Searching AES-CCM from 0x%llx\n", fp_before_aes);
                   ^
bitlocker2john.c:115:20: error: format '%llx' expects argument of type 'long long unsigned int', but argument 3 has type 'long int' [-Werror=format=]
    fprintf(stderr, "Trying offset 0x%llx....\n", jtr_ftell64(fp_eimg));
                    ^
bitlocker2john.c: In function 'process_encrypted_image':
bitlocker2john.c:177:20: error: format '%llx' expects argument of type 'long long unsigned int', but argument 3 has type 'long int' [-Werror=format=]
    fprintf(stderr, "\nSignature found at 0x%llx\n", (jtr_ftell64(fp_eimg) - i - 1));
                    ^
bitlocker2john.c:202:20: error: format '%llx' expects argument of type 'long long unsigned int', but argument 3 has type 'long int' [-Werror=format=]
    fprintf(stderr, "\nVMK entry found at 0x%llx\n", (jtr_ftell64(fp_eimg) - i));
                    ^
bitlocker2john.c:212:21: error: format '%llx' expects argument of type 'long long unsigned int', but argument 3 has type 'int64_t {aka long int}' [-Werror=format=]
     fprintf(stderr, "VMK not encrypted.. stored clear! (0x%llx)\n", fp_before_salt);
                     ^
bitlocker2john.c:214:21: error: format '%llx' expects argument of type 'long long unsigned int', but argument 3 has type 'int64_t {aka long int}' [-Werror=format=]
     fprintf(stderr, "VMK encrypted with TPM...not supported! (0x%llx)\n", fp_before_salt);
                     ^
bitlocker2john.c:216:21: error: format '%llx' expects argument of type 'long long unsigned int', but argument 3 has type 'int64_t {aka long int}' [-Werror=format=]
     fprintf(stderr, "VMK encrypted with Startup Key...not supported! (0x%llx)\n", fp_before_salt);
                     ^
bitlocker2john.c:218:21: error: format '%llx' expects argument of type 'long long unsigned int', but argument 3 has type 'int64_t {aka long int}' [-Werror=format=]
     fprintf(stderr, "\nVMK encrypted with Recovery Password found at 0x%llx\n", fp_before_salt);
                     ^
cc1: all warnings being treated as errors
```

This shows why I had suggested explicit casts to `(unsigned long long)`.

**Review by solardiz — CHANGES_REQUESTED** [review]
Please implement explicit casts to `(unsigned long long)` on `fprintf`.

**Comment by visuve** [comment]
@solardiz is there some readme how to build this locally? The src/configure halts on syntax errors when run with sh (I'm using WSL).

**Comment by solardiz** [comment]
@visuve Can you show those syntax errors? It should just work.

**Comment by visuve** [comment]
@solardiz ``configure: 32: Syntax error: newline unexpected (expecting ")")``

**Comment by solardiz** [comment]
@visuve That `configure` error looks like an instance of #4736 - please look in there for possible workarounds, and we'd appreciate it if you help us fix that issue.

Does your bumping into that issue imply that the changes you're proposing in this PR are untested by you? Or if not, how did you test those? Thanks!

**Review by solardiz — APPROVED** [review]
The changes look good to me now, although I'd prefer to also hear of whether/how they've been tested.

**Comment by visuve** [comment]
@solardiz I found the issue with the src/configure file. I set .gitconfig ``[core] autocrlf = false`` and now it works... :D

**Comment by solardiz** [comment]
@visuve So, can you answer my question on whether/how you tested the changes in this PR? By the way, we already had to apply a further fix to them in #5104.

> I found the issue with the src/configure file. I set .gitconfig `[core] autocrlf = false` and now it works... :D

Great. As I recall, that's one of the workarounds mentioned in #4736. Maybe we need to have something like this by default - please feel free to send us a PR fixing #4736.

**Pull request merged**
