### PR TITLE
Assorted fixes

### PR DESCRIPTION
**Pull request by magnumripper**
I'll probably add more (unrelated) commits to this PR.

### CODE REVIEW

**Comment by solardiz** [comment]
I'd easily approve the first 2 commits here, but the 3rd one is less obvious to me:

> [OpenCL NTLMv2 and MSCASH formats: Bug fix for reset()](https://github.com/openwall/john/pull/5219/commits/ae44ceb8eb2954778de188928a5acb207d04567b)
> 
> When running without mask, format would not reinitialize hash tables
> between self-tests and the real run, causing a hang at best and false
> negatives at worst.
> 
> Problem introduced with https://github.com/magnumripper/john/commit/bd7b8267764bfda5bce9df40cf1a6dfcf89e0329 (https://github.com/openwall/john/issues/4012).

The issue sounds similar to #4964, which I fixed in ddfcc27d7b2097afa34c3c300ca170290a680bbf and 2bf0b31278070fa5e072b9f986221f822f73944b, but your fix here is different. Maybe we should use the same approach here, and make the kernel + hash tables rebuild unconditional?

**Comment by solardiz** [comment]
> Maybe we should use the same approach here, and make the kernel + hash tables rebuild unconditional?

Actually, seeing how I had done it in two commits back then, I don't mind the commit here introducing the extra condition first, and then dropping all of those conditions with a separate commit.

**Comment by magnumripper** [comment]
Wouldn't using `num_loaded_hashes != db->salts->count` fail when the number of loaded hashes happens to be the same as the number of test vectors? Good thing that's not in there anymore.

We could make it unconditional (and be sure to avoid bugs like this one), but some systems might be very slow at building and/or tuning even trivial kernels so I'd rather not rebuild unless actually needed. When mask mode iterates over length it calls `reset()` between each length.

Instead of adding that static `*last_db` we could test it as `|| (db->real == db)` though.

loader.h:
```c
/*
 * Pointer to real db. NULL if there is none. If this db *is* the real db
 * this points back to ourself (db->real == db).
 */
       struct db_main *real;
```

**Comment by magnumripper** [comment]
> Instead of adding that static `*last_db` we could test it as `|| (db->real == db)` though.

No wait, that would defeat the purpose - it would be more or less the same as unconditional. The current code in this PR is better.

**Comment by solardiz** [comment]
> Wouldn't using `num_loaded_hashes != db->salts->count` fail when the number of loaded hashes happens to be the same as the number of test vectors?

Yes, and I recall concluding that was fine. However, the reasoning was tricky and I did prefer not to have the condition.

**Comment by solardiz** [comment]
> I recall concluding that was fine.

Maybe I was wrong. I now see the logic was skipping not only kernel rebuild, but also a `prepare_tables`. Also, there are many more potentially affected formats listed in my comments in #4964 - @magnumripper, please take a look. If we're only patching two kernels here now, we need to have a comment (I mean here on GitHub) explaining why we don't need to patch the rest of these.

**Comment by magnumripper** [comment]
> there are many more potentially affected formats listed in my comments in #4964 - @magnumripper, please take a look.

The bug hit me with NTLMv2-opencl (crashed unless using mask) and I did look for it in more formats - that's how I found it in mscash-opencl. The rest did look fine to me but it wasn't a super thorough review. IIRC I reviewed all formats with `FMT_MASK` and `prepare_*`.

**Comment by magnumripper** [comment]
> We could make it unconditional (and be sure to avoid bugs like this one), but some systems might be very slow at building and/or tuning even trivial kernels so I'd rather not rebuild unless actually needed. When mask mode iterates over length it calls `reset()` between each length.

I had a look at this now - it seems mask mode is smart enough not to call `reset()` unless needed. So perhaps we should make it unconditional!

**Comment by magnumripper** [comment]
I reviewed all `FMT_MASK` formats again, and dropped obsolete code from a bunch of them. They were creating a database out of test vectors but we're doing that in core nowadays.

Now a good deal of testing ahead...

**Comment by magnumripper** [comment]
> Now a good deal of testing ahead...

They all seem fine. I tried `-test=0`, `-test-full=0`, `-test` with or without `-no-mask` and all available tests in the TS, plus some random manual testing.

DES-opencl also has obsolete handling of test vectors, but I'm not sure I dare touching it.

**Comment by solardiz** [comment]
@magnumripper Perhaps we should get this PR merged already, at the same time with today's contributed PR? Thanks!

**Review by ghost — APPROVED** [review]
Since the PR has been tested by magnum and Solar has given his LGMT to merge, I will merge and create a new dev package.

**Pull request merged**
