### PR TITLE
OpenCL SHA-2: Roll the loops in SHA256_ZEROS and SHA512_ZEROS

### LINKED ISSUE #3525: Optimize our OpenCL PBKDF2-HMAC-SHA512 code
Our current speed,

```
$ ../run/john --format=PBKDF2-HMAC-SHA512-opencl --test 
Device 0: GeForce GTX 1050 Ti
Benchmarking: PBKDF2-HMAC-SHA512-opencl, GRUB2 / OS X 10.8+ [PBKDF2-SHA512 OpenCL]
Speed for cost 1 (iteration count) of 1000
Raw:	72817 c/s real, 72817 c/s virtual, GPU util: 100%
```

Hashcat's speed,

```
$ ./hashcat --optimized-kernel-enable -b -m 12100 -w 4
hashcat (v5.1.0-39-gdbbba1fb) starting in benchmark mode...

Hashmode: 12100 - PBKDF2-HMAC-SHA512 (Iterations: 999)
Speed.#1.........:   130.8 kH/s (330.53ms) @ Accel:128 Loops:124 Thr:512 Vec:1
```

It seems that our OpenCL `PBKDF2-HMAC-SHA1` stuff is solid but our `PBKDF2-HMAC-SHA512-opencl` stuff isn't the best.

Hopefully, I am comparing comparable things here.

@magnumripper This will require your help.

### PR DESCRIPTION
**Pull request by solardiz**
Reduces code size and register pressure, and speeds up OpenCL formats using this code on many devices while not hurting most others tested so far (except for NVIDIA Kepler, which we now check for and use old code there). Examples include +50% for pbkdf2-hmac-sha512-opencl on NVIDIA Maxwell and Pascal GPUs, +33% for tezos-opencl on GTX 1080, +3% to +10% for pbkdf2-hmac-sha256-opencl, pbkdf2-hmac-sha512-opencl, and bitcoin-opencl on AMD Vega 64.

Since this change is to an OpenCL header file only, you need to force OpenCL kernels rebuild with "make kernel-cache-clean" for the change to take effect.

Fixes #3525.

I also tried rolling the loops in non-`ZEROS` versions of these macros, which would have made the source code simpler and could provide some more speedup (although our current uses of the non-`ZEROS` versions are not performance-critical). Unfortunately, that resulted in self-test failures on AMD Vega 64 with AMDGPU-Pro, so is avoided in the changes proposed here.

### CODE REVIEW

**Review by magnumripper — APPROVED** [review]
Just glanced it but saw no evil

**Comment by solardiz** [comment]
I am running more tests. Somehow `iwork-opencl` fails to build now - puzzling. Investigating.

**Comment by solardiz** [comment]
OK, not so puzzling - I should probably be passing `W` as parameter into the sub-macros. With the changes, the sub-macros rely on `W` being declared under that name in the current scope, which might not always be true.

**Comment by solardiz** [comment]
> I should probably be passing `W` as parameter into the sub-macros.

This fixed build for Intel, but not for NVIDIA - puzzling.

**Comment by solardiz** [comment]
Also, 3 tests fail with the old Intel OpenCL on "super" (the remaining 88 formats pass):

```
Testing: pfx-opencl, (.pfx, .p12) [PKCS#12 PBE (SHA1/SHA-256/512) OpenCL]... Build log: Compilation started
Compilation done
Linking started
Linking done
Kernel <pfx> was not vectorized
Done.
FAILED (cmp_all(5))

Testing: raw-SHA512-free-opencl [SHA512 OpenCL (inefficient, development use mostly)]... Build log: Compilation started
Compilation done
Linking started
Linking done
Kernel <kernel_sha512> was not vectorized
Kernel <kernel_cmp> was successfully vectorized
Done.
FAILED (cmp_all(10))

Testing: XSHA512-free-opencl, Mac OS X 10.7+ [SHA512 OpenCL (efficient at "many salts" only)]... Build log: Compilation started
Compilation done
Linking started
Linking done
Kernel <kernel_xsha512> was not vectorized
Kernel <kernel_cmp> was successfully vectorized
Done.
FAILED (cmp_all(29))
```

I don't know if these failures are new with these changes or not - will test these formats as of prior to these changes as well.

**Comment by solardiz** [comment]
The raw-SHA512-free-opencl and XSHA512-free-opencl failures are intermittent and they also happen with older code, so not related to this PR.

However, the pfx-opencl failure on Intel is new with this PR. Somehow this format still passes test on NVIDIA.

**Comment by solardiz** [comment]
> > I should probably be passing `W` as parameter into the sub-macros.
> 
> This fixed build for Intel, but not for NVIDIA - puzzling.

I had a copy of an older version of `opencl_sha2.h` in `run` - turns out that one was picked up on NVIDIA (`run` was my current directory) despite of the `-I opencl`.

**Comment by solardiz** [comment]
> However, the pfx-opencl failure on Intel is new with this PR.

I cannot avoid this even if I limit my changes only to `_ZEROS` (leaving the non-`_ZEROS` macros entirely unmodified).

**Comment by solardiz** [comment]
> The raw-SHA512-free-opencl and XSHA512-free-opencl failures are intermittent and they also happen with older code

This is #4434.

**Comment by solardiz** [comment]
> I also tried rolling the loops in non-`ZEROS` versions of these macros, which would have made the source code simpler and could provide some more speedup (although our current uses of the non-`ZEROS` versions are not performance-critical). Unfortunately, that resulted in self-test failures on AMD Vega 64 with AMDGPU-Pro, so is avoided in the changes proposed here.

Incidentally, that attempted change affected how `tezos-opencl` failed on Intel HD Graphics on "well": without that change (such as with this PR as currently proposed), it fails with "Error: out of memory." during kernel build. With the non-`ZEROS` loops also rolled, it built and failed self-test. Whatever.

**Comment by solardiz** [comment]
All 91 formats pass tests on 3 NVIDIA GPUs in "super" now.

> However, the pfx-opencl failure on Intel is new with this PR.

That's on "super". On "well", it's also failing prior to this PR, but it wasn't failing as of May 2021. _Maybe_ 91e96a73780de80f4613af4ba2c0df9acfd0c912 broke it there - I didn't specifically check for this, but I don't have any better guess at this point.

**Comment by magnumripper** [comment]
> I had a copy of an older version of `opencl_sha2.h` in `run` - turns out that one was picked up on NVIDIA (`run` was my current directory) despite of the `-I opencl`.

Wow, that's just crazy - and annoying.

**Comment by magnumripper** [comment]
BTW we made some changes a while ago (#4335, #4373) so we chdir into run and then pass `-I opencl`. Why don't we just chdir into run/opencl and ditch `-I` altogether?

**Comment by solardiz** [comment]
> Why don't we just chdir into run/opencl and ditch `-I` altogether?

Yes, we probably should.

Back then, I was thinking what if we fail to chdir or to chdir back or where possible core dumps would be. However, now that I'm aware of this issue on NVIDIA, that's a reason to reconsider.

**Pull request merged**
