### PR TITLE
Keplr wallet format and import script (*2john.py)

### PR DESCRIPTION
**Pull request by alainesp**

### CODE REVIEW

**Review by solardiz — APPROVED** [review]
Thanks, Alain! This will need a `NEWS` entry and maybe some minor cleanups, which I might add with a separate commit.

**Comment by solardiz** [comment]
@alainesp Can you please also add a sample Keplr wallet (with known passwords and no funds) to https://github.com/openwall/john-samples?

**Comment by solardiz** [comment]
@AlekseyCherepanov This is a new format you could fuzz.

**Comment by alainesp** [comment]
> @alainesp Can you please also add a sample Keplr wallet (with known passwords and no funds) to https://github.com/openwall/john-samples?

I had errors cloning this repository when I forked it. TortoiseGit and plain git both give me errors. Something like:

PS C:\Users\Alain\Desktop\Repositories> git clone https://github.com/alainesp/john-samples.git
Cloning into 'john-samples'...
remote: Enumerating objects: 7028, done.
remote: Counting objects: 100% (151/151), done.
remote: Compressing objects: 100% (106/106), done.
remote: Total 7028 (delta 33), reused 129 (delta 29), pack-reused 6877
Receiving objects: 100% (7028/7028), 441.68 MiB | 28.47 MiB/s, done.
Resolving deltas: 100% (223/223), done.
error: invalid path 'SSH/ssh-key-collection/key-!@#$%^&*'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

This is on Windows 10.

**Comment by solardiz** [comment]
> error: invalid path 'SSH/ssh-key-collection/key-!@#$%^&*'

Oh, right, known issue: https://github.com/openwall/john-samples/issues/2

**Comment by solardiz** [comment]
@alainesp I think I've just fixed the issue with john-samples vs. Windows filesystems, please try cloning that repo again.

**Comment by alainesp** [comment]
> @alainesp I think I've just fixed the issue with john-samples vs. Windows filesystems, please try cloning that repo again.

Now it works without a problem. I have the pull request done.

**Pull request merged**
