### PR TITLE
Assorted fixes and enhancements

### PR DESCRIPTION
**Pull request by solardiz**
This improves messages printed by `john`, reduces HMAC-SHA256's false positive detections (#3993), adds explicit scrypt, yescrypt, gost-yescrypt support to the generic crypt(3) format and its uses by loader (#4622), and fixes a few issues with the generic crypt(3) format (I only separated one of those fixes into its own commit).

### CODE REVIEW

**Comment by solardiz** [comment]
@AlekseyCherepanov It would be good to fuzz the 4 HMAC formats after this is merged.

**Comment by solardiz** [comment]
@magnumripper JFYI, in 75705bdbe719a3cd90de0734a07851e049764876 you introduced a bug, fixed here. This change wasn't correct (it effectively removed the padding):

```diff
+++ b/src/c3_fmt.c
@@ -400,9 +401,8 @@ static void *salt(char *ciphertext)
                    !strncmp(ciphertext, "$md5,", 5))) {
                        char *p = strrchr(ciphertext + 4, '$');
                        if (p) {
-                               /* NUL padding is required */
-                               memset(out, 0, sizeof(out));
-                               memcpy(out, ciphertext, ++p - ciphertext);
+                               strncpy_pad(out, ciphertext,
+                                           ++p - ciphertext, 0);
 /*
  * Workaround what looks like a bug in sunmd5.c: crypt_genhash_impl() where it
  * takes a different substring as salt depending on whether the optional
```

**Comment by ghost** [comment]
Probably off-topic.

* Just for the record: this is extremely rare, but it did happen once (at least):
```
:: Testing: crypt, generic crypt(3) [?/64]... (4xOMP) FAILED (cmp_all(96))
:: 1 out of 406 tests have FAILED
::  FAILED: -test-full=0 --format=cpu
```

**Comment by solardiz** [comment]
> Testing: crypt, generic crypt(3) [?/64]... (4xOMP) FAILED (cmp_all(96))

I'm not aware of a bug like that in our code. It could be that the system this ran on has a thread-safety bug in its `crypt_r`. What system was that?

**Comment by ghost** [comment]
> I'm not aware of a bug like that in our code. 

I saved it as a kind of note for myself.

> What system was that?

Ubuntu 22, but I'm not sure of the architecture.

**Pull request merged**
