### PR TITLE
Update and bring in sync INSTALL-FEDORA and INSTALL-UBUNTU

### PR DESCRIPTION
**Pull request by solardiz**
I'd appreciate review. For example, I don't know whether `nvidia-opencl-dev` possibly brings a version of CUDA with it or not. To be on the safe side, I assumed here that it does not. I don't recall ever installing this package myself - would install then-latest CUDA off the NVIDIA website instead.

### CODE REVIEW

**Comment by ghost** [comment]
> I'd appreciate review. For example, I don't know whether nvidia-opencl-dev possibly brings a version of CUDA with it or not

I suppose we need community volunteers for these use cases (please, help!). No developers have GPUs for testing.

**Review by magnumripper — APPROVED** [review]
Note: I know nothing about Fedora - but the Ubuntu stuff looks good to me

**Comment by magnumripper** [comment]
Doesn't @kholia use to run Fedora? Or perhaps we can ask folks on the john-users ML for a review?

**Comment by ghost** [comment]
I run a CI test using Fedora. Therefore, OpenCL is the open question.

**Comment by solardiz** [comment]
This failed on Travis with:

```
Testing: lp-opencl, LastPass offline [PBKDF2-SHA256 AES OpenCL]... 

The job exceeded the maximum time limit for jobs, and has been terminated.
```

I guess magnum will need to use his powers to get this merged anyway.

**Comment by ghost** [comment]
You can merge it now, if you wish.

**Pull request merged**
