### PR TITLE
Use a #define to "inline" in OpenCL

### PR DESCRIPTION
**Pull request by ghost**
Testing now. It contains the revert and (the last commit) the `#define`.

### CODE REVIEW

**Comment by ghost** [comment]
It seems it will succeed. So, pending is ROCM (in case anyone complained directly to you, the guy should test now).

**Comment by magnumripper** [comment]
I added a few changes. Right now it uses 'static inline' for any AMD that isn't POCL or MESA. Should work fine.

**Review by magnumripper — APPROVED** [review]

**Comment by ghost** [comment]
POCL is unhappy when it sees the re-definition of `inline`. I'm thinking about doing:

```
#elif __POCL__
// Do nothing
```

**Comment by magnumripper** [comment]
> POCL is unhappy when it sees the re-definition of `inline`. I'm thinking about doing:
> 
> ```
> #elif __POCL__
> // Do nothing
> ```

That's fine (with the comment!)

**Comment by magnumripper** [comment]
Actually we should do the same (nothing!) as default!

**Comment by ghost** [comment]
> Actually we should do the same (nothing!) as default!

:+1:

**Comment by magnumripper** [comment]
I think I have beignet installed somewhere as well. And we should test all drivers on Solar's test rigs.

**Comment by ghost** [comment]
> I think I have beignet installed somewhere as well. And we should test all drivers on Solar's test rigs.

I have a "script" testing that does that (manual, since I can't add Solar's stuff to CI).

**Comment by magnumripper** [comment]
You might want to squash all commits for opencl_misc.h into a single one before we merge.

**Comment by ghost** [comment]
> You might want to squash all commits for opencl_misc.h into a single one before we merge.

I almost did that, but then I thought more commits tell the story better.

**Pull request merged**
