### PR TITLE
Rules update

### PR DESCRIPTION
**Pull request by solardiz**
This is my work-in-progress on #4851, #5003, #5004.

### CODE REVIEW

**Comment by solardiz** [comment]
Testing on one CPU core against representative 100M from HIBP v8:

```
./john -form=nt -verb=1 -encoding=cp1252 -w -ru -progress-every=120 pp8-sample-100m
Loaded 53848563 password hashes with no different salts (NT [MD4 128/128 AVX 4x3])
Proceeding with wordlist:./password.lst, rules:Wordlist
Press 'q' or Ctrl-C to abort, almost any other key for status
13694837g 0:00:02:01 15.32% (ETA: 23:11:37) 113105g/s 6380Kp/s 6380Kc/s 274317GC/s 020f00..042f
15664147g 0:00:04:01 35.78% (ETA: 23:09:41) 64977g/s 7291Kp/s 7291Kc/s 297171GC/s xandgee..1983g1958
16624474g 0:00:06:01 55.71% (ETA: 23:09:15) 46044g/s 7594Kp/s 7594Kc/s 301096GC/s digestive565..robbie20565
17341434g 0:00:08:01 76.60% (ETA: 23:08:55) 36050g/s 7936Kp/s 7936Kc/s 308370GC/s nghia123443..10121968443
17862308g 0:00:10:01 97.02% (ETA: 23:08:47) 29720g/s 8087Kp/s 8087Kc/s 309690GC/s coolcat4..gore4
17906157g 0:00:10:14 DONE (2022-01-31 23:08) 29144g/s 8097Kp/s 8097Kc/s 309632GC/s Chokolate538..Sambarock38
```

This is 40% of Single-Extra rules cracking 97.5% of what full Single-Extra would, which was:

```
18351644g 0:00:22:21 DONE (2022-01-31 19:00) 13682g/s 7021Kp/s 7021Kc/s 259805GC/s
```

Proceeding further with the next 40%:

```
./john -form=nt -verb=1 -encoding=cp1252 -w -ru=worse-by-score -progress-every=120 pp8-sample-100m
Loaded 53848563 password hashes with no different salts (NT [MD4 128/128 AVX 4x3])
Remaining 35942406 password hashes with no different salts
Proceeding with wordlist:./password.lst, rules:worse-by-score
Press 'q' or Ctrl-C to abort, almost any other key for status
251752g 0:00:02:00 20.31% (ETA: 23:29:33) 2094g/s 8029Kp/s 8029Kc/s 287835GC/s GreGoRius..KabOoM123
354288g 0:00:04:00 40.34% (ETA: 23:29:37) 1475g/s 7997Kp/s 7997Kc/s 285863GC/s Popp00225..Gypsy24225
405043g 0:00:06:00 60.00% (ETA: 23:29:43) 1124g/s 7843Kp/s 7843Kc/s 279876GC/s Risers931..Proline23931
431603g 0:00:08:00 80.66% (ETA: 23:29:38) 898.9g/s 7541Kp/s 7541Kc/s 268817GC/s Trish100698..Horcsog698
443881g 0:00:09:42 DONE (2022-01-31 23:29) 761.4g/s 7256Kp/s 7256Kc/s 258871GC/s Mrsolo'..Sambarock'
```

and the final 20%:

```
./john -form=nt -verb=1 -encoding=cp1252 -w -ru=worst-by-score -progress-every=120 pp8-sample-100m
Loaded 53848563 password hashes with no different salts (NT [MD4 128/128 AVX 4x3])
Remaining 35498525 password hashes with no different salts
Proceeding with wordlist:./password.lst, rules:worst-by-score
Press 'q' or Ctrl-C to abort, almost any other key for status
1606g 0:00:02:00 79.89% (ETA: 23:35:46) 13.35g/s 1547Kp/s 1547Kc/s 55024GC/s chivas504..emiliano504
1606g 0:00:02:28 DONE (2022-01-31 23:35) 10.80g/s 1440Kp/s 1440Kc/s 51361GC/s syNyster123..saMbarock
```

That's somehow much less than 20% of time and low p/s rate - perhaps lots of word rejects by the worst 20% rules. Anyhow, it is obvious these are in fact worst.

Also comparing this against `OneRuleToRuleThemAll` (which is supposed to have been similarly optimized, albeit of course on different samples):

```
./john -form=nt -verb=1 -encoding=cp1252 -w -ru=OneRuleToRuleThemAll -progress-every=120 pp8-sample-100m
Loaded 53848563 password hashes with no different salts (NT [MD4 128/128 AVX 4x3])
Proceeding with wordlist:./password.lst, rules:OneRuleToRuleThemAll
Press 'q' or Ctrl-C to abort, almost any other key for status
3621034g 0:00:00:21 0.13% (ETA: 03:38:51) 171612g/s 5533Kp/s 5533Kc/s 285310GC/s 1986021..1408841
4707650g 0:00:00:47 0.37% (ETA: 02:35:49) 99950g/s 7201Kp/s 7201Kc/s 362340GC/s jjuurez07..002231984
6292190g 0:00:02:00 1.07% (ETA: 02:10:50) 52295g/s 8216Kp/s 8216Kc/s 402535GC/s vinzheaven28..vinzqwe789456123
7929247g 0:00:04:00 2.18% (ETA: 02:06:22) 33001g/s 8443Kp/s 8443Kc/s 404281GC/s crazyroxy81..crazyQWer12
8253124g 0:00:06:00 3.31% (ETA: 02:04:23) 22911g/s 8549Kp/s 8549Kc/s 403181GC/s fishymsniscool..fishyhevean
8892903g 0:00:08:00 4.48% (ETA: 02:01:41) 18519g/s 8681Kp/s 8681Kc/s 405381GC/s Porrain1n1..Poggy0505
9597223g 0:00:10:00 5.69% (ETA: 01:59:00) 15990g/s 8818Kp/s 8818Kc/s 407617GC/s 200084war..flamenkitowar
10599202g 0:00:12:00 6.90% (ETA: 01:57:09) 14717g/s 8915Kp/s 8915Kc/s 408237GC/s elis12tt..whimpertt
11127630g 0:00:14:00 8.08% (ETA: 01:56:21) 13243g/s 8959Kp/s 8959Kc/s 406643GC/s brmdsoX..jemnmaRco
11983370g 0:00:16:00 9.30% (ETA: 01:55:08) 12481g/s 9024Kp/s 9024Kc/s 405958GC/s badassabc1010..badassjackie48
13411218g 0:00:18:00 10.41% (ETA: 01:56:00) 12416g/s 8981Kp/s 8981Kc/s 400115GC/s javiskaren38..javisrick67
13863667g 0:00:20:00 11.53% (ETA: 01:56:36) 11552g/s 8952Kp/s 8952Kc/s 395077GC/s b0l1v14n4..b0xelder
14567010g 0:00:22:00 12.71% (ETA: 01:56:16) 11035g/s 8971Kp/s 8971Kc/s 392102GC/s mistersexybam1..mister72222222
14954700g 0:00:24:00 13.88% (ETA: 01:56:00) 10384g/s 8986Kp/s 8986Kc/s 389310GC/s 8257..che97l68
15366189g 0:00:26:00 15.10% (ETA: 01:55:19) 9850g/s 8979Kp/s 8979Kc/s 385800GC/s mewtwo133945..mewtwoREADY1
15514480g 0:00:28:00 16.27% (ETA: 01:55:16) 9234g/s 8984Kp/s 8984Kc/s 383071GC/s canelo584112..canelosanyboy
15708393g 0:00:29:59 17.43% (ETA: 01:55:14) 8726g/s 8990Kp/s 8990Kc/s 380680GC/s kiko1973..aria2007
16115263g 0:00:31:59 18.78% (ETA: 01:53:32) 8393g/s 9083Kp/s 9083Kc/s 381753GC/s 136591s..19400s
16581595g 0:00:33:59 20.12% (ETA: 01:52:06) 8128g/s 9161Kp/s 9161Kc/s 382230GC/s akirado87..bizkid
17034972g 0:00:35:59 21.45% (ETA: 01:50:54) 7886g/s 9229Kp/s 9229Kc/s 382355GC/s rando1l..2312o172
17761613g 0:00:39:59 24.06% (ETA: 01:49:23) 7400g/s 9318Kp/s 9318Kc/s 380990GC/s medrings06..mcaatilado
18141042g 0:00:41:59 25.43% (ETA: 01:48:17) 7199g/s 9383Kp/s 9383Kc/s 381087GC/s 12wabcj..Rowertobolle
18413643g 0:00:43:59 26.77% (ETA: 01:47:28) 6975g/s 9431Kp/s 9431Kc/s 380672GC/s dodnie7..tadi
18649185g 0:00:45:59 28.10% (ETA: 01:46:47) 6757g/s 9472Kp/s 9472Kc/s 380043GC/s AMska12..1M61110
18892347g 0:00:47:59 29.44% (ETA: 01:46:11) 6560g/s 9509Kp/s 9509Kc/s 379350GC/s aaison0311..markec11
19045016g 0:00:49:59 30.79% (ETA: 01:45:32) 6348g/s 9549Kp/s 9549Kc/s 378810GC/s Tberdeen1020..Tlyse220
19220126g 0:00:51:59 32.13% (ETA: 01:44:57) 6160g/s 9584Kp/s 9584Kc/s 378222GC/s Nolce123..N921293
19415168g 0:00:53:59 33.47% (ETA: 01:44:27) 5992g/s 9615Kp/s 9615Kc/s 377542GC/s kmatra44..kintage7544
19571522g 0:00:55:59 34.83% (ETA: 01:43:56) 5825g/s 9647Kp/s 9647Kc/s 376957GC/s giszy19..grazan
19755736g 0:00:57:59 36.15% (ETA: 01:43:34) 5677g/s 9671Kp/s 9671Kc/s 376128GC/s CnwoCthy..Cey1C3
19959320g 0:00:59:59 37.48% (ETA: 01:43:14) 5544g/s 9692Kp/s 9692Kc/s 375266GC/s unicorndemon311..unicornrachael90
20074885g 0:01:01:59 38.66% (ETA: 01:43:29) 5396g/s 9677Kp/s 9677Kc/s 373240GC/s branden371990..brandencorazon17
20212171g 0:01:03:59 39.91% (ETA: 01:43:29) 5264g/s 9679Kp/s 9679Kc/s 371833GC/s him7xavier..himaxle13
20346487g 0:01:05:59 41.15% (ETA: 01:43:32) 5138g/s 9675Kp/s 9675Kc/s 370295GC/s pitbullrainhard..pitbullBlackDragon
20564385g 0:01:07:59 42.33% (ETA: 01:43:46) 5040g/s 9663Kp/s 9663Kc/s 368485GC/s specialpepper82..special7129
21206958g 0:01:09:59 43.56% (ETA: 01:43:49) 5049g/s 9660Kp/s 9660Kc/s 366922GC/s erikkeith2007..erikhilda01
21365837g 0:01:11:59 44.83% (ETA: 01:43:46) 4946g/s 9664Kp/s 9664Kc/s 365587GC/s 27949i9i..103914i4i
21462476g 0:01:13:59 46.07% (ETA: 01:43:45) 4834g/s 9665Kp/s 9665Kc/s 364206GC/s bambidenval..bambijunea
21601372g 0:01:15:59 47.35% (ETA: 01:43:39) 4737g/s 9671Kp/s 9671Kc/s 363057GC/s augenau1234..tim456
21726840g 0:01:17:59 48.61% (ETA: 01:43:36) 4642g/s 9674Kp/s 9674Kc/s 361830GC/s blockw35ork..55689
21841427g 0:01:19:59 49.83% (ETA: 01:43:41) 4550g/s 9671Kp/s 9671Kc/s 360417GC/s justichee97..readyche3
22001885g 0:01:21:59 51.03% (ETA: 01:43:49) 4472g/s 9662Kp/s 9662Kc/s 358890GC/s chris222428..oct2422291
22095873g 0:01:23:59 52.22% (ETA: 01:44:00) 4384g/s 9652Kp/s 9652Kc/s 357343GC/s loiallono..mynull1
22216923g 0:01:25:59 53.39% (ETA: 01:44:14) 4305g/s 9639Kp/s 9639Kc/s 355721GC/s 147954321..dani54321lle54
22310518g 0:01:27:59 54.47% (ETA: 01:44:42) 4225g/s 9612Kp/s 9612Kc/s 353703GC/s shiyvji..nicyki2
22379609g 0:01:29:59 55.68% (ETA: 01:44:47) 4144g/s 9605Kp/s 9605Kc/s 352374GC/s 573ara73..douara1234
22481299g 0:01:31:59 56.80% (ETA: 01:45:08) 4073g/s 9586Kp/s 9586Kc/s 350656GC/s Idt3007..Ifoyygurl
22560317g 0:01:33:59 57.99% (ETA: 01:45:14) 4000g/s 9580Kp/s 9580Kc/s 349391GC/s feadliz20..kaadtrinar
22634699g 0:01:35:59 59.17% (ETA: 01:45:24) 3930g/s 9571Kp/s 9571Kc/s 348064GC/s Maurelissa04..caurdcd11
22725751g 0:01:37:59 60.25% (ETA: 01:45:48) 3865g/s 9547Kp/s 9547Kc/s 346322GC/s HDhacker77..HDwitchs
22947839g 0:01:39:59 61.44% (ETA: 01:45:55) 3825g/s 9540Kp/s 9540Kc/s 345091GC/s georgharley1955..georgmedia4
23049782g 0:01:41:59 62.69% (ETA: 01:45:52) 3766g/s 9544Kp/s 9544Kc/s 344206GC/s ruejenifer7..rueaguilaroja
23147014g 0:01:43:59 63.89% (ETA: 01:45:56) 3709g/s 9539Kp/s 9539Kc/s 343099GC/s waffle310306..wafflejnkbxybwf
23229667g 0:01:45:59 65.08% (ETA: 01:46:01) 3652g/s 9535Kp/s 9535Kc/s 342004GC/s KURAMAea..tati98ea
23323494g 0:01:47:59 66.31% (ETA: 01:46:01) 3599g/s 9535Kp/s 9535Kc/s 341084GC/s parin..entrep
23382365g 0:01:49:59 67.54% (ETA: 01:46:01) 3543g/s 9536Kp/s 9536Kc/s 340187GC/s oveduse2..car1
23458481g 0:01:51:59 68.74% (ETA: 01:46:05) 3491g/s 9532Kp/s 9532Kc/s 339180GC/s 120782011..litlesheep2011
23520512g 0:01:53:59 69.90% (ETA: 01:46:14) 3439g/s 9524Kp/s 9524Kc/s 338045GC/s eizabeth081234..lludog1234
23586851g 0:01:55:59 71.13% (ETA: 01:46:14) 3389g/s 9523Kp/s 9523Kc/s 337185GC/s Santa8e6..Rievauelx
23689965g 0:01:57:59 72.37% (ETA: 01:46:13) 3346g/s 9525Kp/s 9525Kc/s 336407GC/s 31825..Max1992825
23785680g 0:01:59:59 73.58% (ETA: 01:46:14) 3303g/s 9524Kp/s 9524Kc/s 335550GC/s Darksorrow549..Hornpipe1549
23868594g 0:02:01:59 74.79% (ETA: 01:46:17) 3261g/s 9522Kp/s 9522Kc/s 334658GC/s Brownies3312..Steve59312
23962258g 0:02:03:59 76.00% (ETA: 01:46:19) 3221g/s 9520Kp/s 9520Kc/s 333805GC/s Unlisted1962..Queenbee11962
24026395g 0:02:05:59 77.19% (ETA: 01:46:23) 3178g/s 9516Kp/s 9516Kc/s 332905GC/s cnahermaher..cblleycat13
24093106g 0:02:07:59 78.39% (ETA: 01:46:26) 3137g/s 9514Kp/s 9514Kc/s 332067GC/s jimmy55BR..marimoBR
24181102g 0:02:09:59 79.65% (ETA: 01:46:22) 3100g/s 9517Kp/s 9517Kc/s 331411GC/s barraczarek1..barraelisas
24267813g 0:02:11:59 80.85% (ETA: 01:46:25) 3064g/s 9515Kp/s 9515Kc/s 330584GC/s rafaeladavidavid..rafaelabornintheusa
24347251g 0:02:13:59 82.06% (ETA: 01:46:27) 3028g/s 9513Kp/s 9513Kc/s 329782GC/s taba421571..tabacoots
24457112g 0:02:15:58 83.35% (ETA: 01:46:19) 2997g/s 9522Kp/s 9522Kc/s 329335GC/s 88teven10..8810792
24544985g 0:02:17:58 84.67% (ETA: 01:46:08) 2964g/s 9532Kp/s 9532Kc/s 328912GC/s damary/..farmer.1
24631642g 0:02:19:58 85.99% (ETA: 01:45:58) 2932g/s 9542Kp/s 9542Kc/s 328490GC/s cherish7630..straylight630
24706472g 0:02:21:58 87.30% (ETA: 01:45:49) 2900g/s 9551Kp/s 9551Kc/s 328050GC/s 87521..eadaehd2
24784277g 0:02:23:58 88.60% (ETA: 01:45:41) 2868g/s 9559Kp/s 9559Kc/s 327576GC/s 1234relmadrid1902..1234jae143
24862538g 0:02:25:58 89.92% (ETA: 01:45:31) 2838g/s 9569Kp/s 9569Kc/s 327168GC/s cdouh..1griffi
24936279g 0:02:27:58 91.23% (ETA: 01:45:23) 2808g/s 9577Kp/s 9577Kc/s 326745GC/s longstem2711..garfield3212711
25018011g 0:02:29:58 92.58% (ETA: 01:45:11) 2780g/s 9589Kp/s 9589Kc/s 326416GC/s 21novembre21!..10176921!
25158120g 0:02:31:58 93.89% (ETA: 01:45:03) 2758g/s 9597Kp/s 9597Kc/s 325972GC/s 1207201624..bobby19901624
25233053g 0:02:33:58 95.18% (ETA: 01:44:57) 2731g/s 9603Kp/s 9603Kc/s 325483GC/s yourmom041188..balloon231188
25318399g 0:02:35:58 96.52% (ETA: 01:44:47) 2705g/s 9614Kp/s 9614Kc/s 325138GC/s denis190726..yenifer0726
25385566g 0:02:37:58 97.84% (ETA: 01:44:39) 2678g/s 9622Kp/s 9622Kc/s 324723GC/s 7991asivk..1ihsut0
25456882g 0:02:39:58 99.17% (ETA: 01:44:30) 2652g/s 9631Kp/s 9631Kc/s 324335GC/s Peqrejean..31115
25468452g 0:02:41:13 DONE (2022-02-01 01:44) 2632g/s 9636Kp/s 9636Kc/s 324089GC/s 229078..sambarocj
```

Our result at 4 minutes is similar to theirs at 30 minutes, and that's despite of our lower p/s rate (more complex rules trying harder to avoid duplicates - well, maybe that does contribute to greater progress per time, too). OTOH, they're still having a steady improvement at 1 hour, and crack more total (it's a 10x larger rule set, so no surprise there).

**Comment by solardiz** [comment]
The numbers for the best/worse/worst components add up to the previous total: 17906157+443881+1606 = 18351644

Testing by-score vs. by-rate against a similar 1M sample (~827k unique), reporting unique crack counts at 10M, 100M, 1B candidates tested:

by-score:
217376g 0:00:00:01 0.24% (ETA: 00:01:58) 110343g/s 5076Kp/s 5076Kc/s 6315GC/s hampton40..maci120
286586g 0:00:00:10 2.05% (ETA: 00:03:13) 27345g/s 9541Kp/s 9541Kc/s 5705GC/s vin198789..kelas189
376822g 0:00:01:42 20.03% (ETA: 00:09:17) 3685g/s 9779Kp/s 9779Kc/s 4772GC/s hiehie786..meacuerdo786

by-rate:
217709g 0:00:00:02 0.30% (ETA: 00:06:27) 103670g/s 4761Kp/s 4761Kc/s 3156GC/s aquarious10..passeord0
287529g 0:00:00:11 2.33% (ETA: 00:03:39) 25903g/s 9009Kp/s 9009Kc/s 5180GC/s grimsley125..tratamento25
377011g 0:00:01:43 20.87% (ETA: 00:12:16) 3629g/s 9628Kp/s 9628Kc/s 4722GC/s dusty5u..truusju

As expected, by-rate cracks a tiny bit more passwords by candidates tested (until closer to the end of the rule set, where they ultimately crack the same number). It is to be used on the slowest hashes and when generating de-duplicated lists with `unique` or such.

I'm not sure this tiny difference was worth introducing the different ranking, but here we have it.

**Comment by solardiz** [comment]
I think we should merge this now. Any comments?

**Comment by solardiz** [comment]
> OneRuleToRuleThemAll.rule: Repair two rules with UTF-8 characters

BTW, while I repaired those two rules technically, I doubt the UTF-8 characters they insert are the optimal ones. Maybe something went wrong with those rules in a previous stage of processing. But it's "not our problem", and it's just 2 rules out of 50k+. In my own usage, I had simply commented them out.

**Comment by solardiz** [comment]
The single-core run of `OneRuleToRuleThemAll` completed:

```
25468452g 0:02:41:13 DONE (2022-02-01 01:44) 2632g/s 9636Kp/s 9636Kc/s 324089GC/s 229078..sambarocj
```

Interestingly, its cracks include almost all of those of our `Single-Extra` (or its re-ordered variants). Combining the 25468452 above with 18351644 from `Single-Extra` (~22 minutes), the total is 25673974, or only 0.8% higher. So while `OneRuleToRuleThemAll` makes much slower progress initially, it catches up and then proceeds much further.

**Comment by solardiz** [comment]
Here's how these correspond in terms of duplicate candidates, testing with RockYou top 1000 here (the dupe percentages are much higher for larger wordlists):

`Single-Extra`
```
Total lines read: 5520476, unique lines written: 5420499 (98%), no slow passes
```

`By-score` or `By-rate` (somehow fewer dupes than with `Single-Extra` original - and yes, exactly the same number for these two):
```
Total lines read: 5499788, unique lines written: 5420499 (98%), no slow passes
```

`OneRuleToRuleThemAll`:
```
Total lines read: 51995913, unique lines written: 38478175 (74%), no slow passes
```

`By-score` after `OneRuleToRuleThemAll` (excluding lines produced by `OneRuleToRuleThemAll`):
```
Total lines read: 5499788, unique lines written: 1345709 (24%), no slow passes
```

**Comment by magnumripper** [comment]
> I think we should merge this now. Any comments?

This all happened between two occasions of me reading my email 😆 but I'm sure it's Good Stuff™️ and I really appreciate your work with this. The selections and optimizations are tricky business and you are one of the very few guys I'd trust for doing it (and certainly better than myself).

> > OneRuleToRuleThemAll.rule: Repair two rules with UTF-8 characters
> 
> BTW, while I repaired those two rules technically, I doubt the UTF-8 characters they insert are the optimal ones. Maybe something went wrong with those rules in a previous stage of processing. But it's "not our problem", and it's just 2 rules out of 50k+. In my own usage, I had simply commented them out.

They must have been intended to prepend "contraseña" (That's Spanish for password so not that weird) and (based on the former) "toña" (Spanish for bash, punch, kick? I don't quite get why it'd score) respectively, to the base word. But I can't see how the original ones would be correct in any situation - and your fixes are thus also incorrect. Maybe we should just drop them?
Or we could replace them with `A0"contraseña"` and `A0"toña"` which I believe would make them work in many situations, disable them automagically in some, and just produce garbage in a few.

**Comment by solardiz** [comment]
> They must have been intended to prepend "contraseña" (That's Spanish for password so not that weird)

That's what I thought.

> and (based on the former) "toña" (Spanish for bash, punch, kick? I don't quite get why it'd score)

I didn't know that one.

> respectively, to the base word. But I can't see how the original ones would be correct in any situation - and your fixes are thus also incorrect. Maybe we should just drop them?
> Or we could replace them with `A0"contraseña"` and `A0"toña"` which I believe would make them work in many situations, disable them automagically in some, and just produce garbage in a few.

Yes, we could do one of these, but then this rule set is supposed to have been derived from larger ones (IIRC, it's 25% of those combined), so where did these come from and where were they corrupted, and was this rule set's sorting based on already-corrupted ones (meaning they ranked high enough nevertheless? - doubtful).

Anyway, please feel free to research this and/or just fix it in some way. Thanks!

**Comment by solardiz** [comment]
Testing against my own best results from last year:

The new default wordlist+rules crack 20.5% of HIBP v7 unique hashes in 5 billion candidates.

My old best attempt was splitting RockYou into 2 or 3 parts (by HIBP v7 ranking) and using `Jumbo` (sans `ShiftToggle`) on the smaller part(s) and `Single` on the rest. This cracked 20.3% in 11.7 billion candidates.

So there's a 2.3x+ reduction in candidate count for same crack count, and that's with much simpler usage (all defaults), smaller wordlist, and comparing against unreleased previously-best stuff (which we "couldn't" comfortably release because it contained full unfiltered RockYou, including some people's unique passwords, not only actually common passwords used by many people).

I have to note that the 20.5% and 20.3% figures are with (and include) RockYou itself pre-cracked, which provided the initial 2.3% in either case (that's by construction of HIBP, where RockYou corresponds to 2.3% of total HIBP v7). A user who doesn't have RockYou would possibly achieve a bit less than the 20.5% on this test now - actually, let me test that...

**Comment by solardiz** [comment]
> The new default wordlist+rules crack 20.5% of HIBP v7 unique hashes in 5 billion candidates.

Also, more than half of those cracks are in 10% of running time.

**Comment by solardiz** [comment]
> A user who doesn't have RockYou would possibly achieve a bit less than the 20.5% on this test now - actually, let me test that...

Yes, the 20.5% reduces to 19.36% (not by 2.3%, but roughly by half that). So it's still helpful to have larger wordlists as well, although this test isn't entirely correct since RockYou is literally part of HIBP.

**Comment by solardiz** [comment]
> The single-core run of `OneRuleToRuleThemAll` completed:
> 
> ```
> 25468452g 0:02:41:13 DONE (2022-02-01 01:44) 2632g/s 9636Kp/s 9636Kc/s 324089GC/s 229078..sambarocj
> ```
> 
> Interestingly, its cracks include almost all of those of our `Single-Extra` (or its re-ordered variants). Combining the 25468452 above with 18351644 from `Single-Extra` (~22 minutes), the total is 25673974, or only 0.8% higher. So while `OneRuleToRuleThemAll` makes much slower progress initially, it catches up and then proceeds much further.

FWIW, as percentages these are:

The new defaults crack 33.3% unique passwords or 59.0% non-unique, whereas _also_ running `Worse-by-score` and `OneRuleToRuleThemAll` gets the total to 47.7% unique or 67.7% non-unique.

**Comment by solardiz** [comment]
> Combining the 25468452 above with 18351644 from `Single-Extra` (~22 minutes), the total is 25673974, or only 0.8% higher.

Combining `OneRuleToRuleThemAll` 25468452 with 17906157 from our new defaults (just the best part) gives 25537776. So the "worse" part does still add something measurable on top of these two.

**Pull request merged**
