### PR TITLE
Zip optimizations

### PR DESCRIPTION
**Pull request by magnumripper**
See #4031

### CODE REVIEW

**Comment by magnumripper** [comment]
What the heck does this even mean?
```
zip_fmt_plug.c: In function 'crypt_all':
zip_fmt_plug.c:250:61: error: 'key_len' is predetermined 'shared' for 'shared'
 #pragma omp parallel for default(none) private(index) shared(count, saved_key, saved_salt, crypt_key, key_len, early_skip, late_skip, late_size)
                                                             ^
zip_fmt_plug.c:250:61: error: 'early_skip' is predetermined 'shared' for 'shared'
zip_fmt_plug.c:250:61: error: 'late_skip' is predetermined 'shared' for 'shared'
zip_fmt_plug.c:250:61: error: 'late_size' is predetermined 'shared' for 'shared'
make[1]: *** [Makefile:1604: zip_fmt_plug.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:190: default] Error 2
```
Seen on CircleCI mingw

**Comment by magnumripper** [comment]
> What the heck does this even mean?

I ended up just saying `#pragma omp parallel for` like I use to do

**Comment by solardiz** [comment]
> zip_fmt_plug.c:250:61: error: 'key_len' is predetermined 'shared' for 'shared'

I think that's because `const` implies it can be safely shared, so you don't (and can't?) declare that explicitly. I don't know if this implied-shared for `const` is guaranteed by OpenMP spec or not (and starting with which version). We may want to try excluding these specific constants' names from `shared` (keeping the rest of the directive), or (more reliably) dropping `const`. I think I used one of these solutions in some place in JtR last year or so, but unfortunately I don't recall which of the two approaches I chose and exactly where - you might want to grep for that in the tree or in my commits from last year (maybe in the `DES_bs*` changes, or maybe in some yescrypt-using formats). %-)

**Comment by magnumripper** [comment]
> > zip_fmt_plug.c:250:61: error: 'key_len' is predetermined 'shared' for 'shared'
> 
> I think that's because `const` implies it can be safely shared, so you don't (and can't?) declare that explicitly. I don't know if this implied-shared for `const` is guaranteed by OpenMP spec or not (and starting with which version). We may want to try excluding these specific constants' names from `shared` (keeping the rest of the directive), or (more reliably) dropping `const`. I think I used one of these solutions in some place in JtR last year or so, but unfortunately I don't recall which of the two approaches I chose and exactly where - you might want to grep for that in the tree or in my commits from last year (maybe in the `DES_bs*` changes, or maybe in some yescrypt-using formats). %-)

I suppose you're right but gcc 10 complains if I do not declare them. I'd rather just say `#pragma omp parallel for` than dropping `const` from stuff. In my head the former is more reliable.

**Comment by magnumripper** [comment]
Note to self: In latest version I could drop this workaround
```diff
diff --git a/run/opencl/zip_kernel.cl b/run/opencl/zip_kernel.cl
index 52185dcd5..b757b659c 100644
--- a/run/opencl/zip_kernel.cl
+++ b/run/opencl/zip_kernel.cl
@@ -186,11 +186,7 @@ inline void pbkdf2_hmac_sha1(const uchar *pass, const uint passlen,
 {
        uint ipad_state[5];
        uint opad_state[5];
-#if gpu_nvidia(DEVICE_INFO)
-       /* This is a driver bug workaround. Problem seen with eg. 465.19.01 */
-       volatile
-#endif
-               uint accum = 0;
+       uint accum = 0;
 
        preproc(pass, passlen, ipad_state, 0x36363636);
        preproc(pass, passlen, opad_state, 0x5c5c5c5c);
```
It now tunes and runs very well on nvidias and under macOS w/ any device I've tried but segfaults(!) with virtually all Intel or POCL CPU drivers and fails with most other AMD drivers I've tried. I suspect there's some bug left to nail (as opposed to driver bugs to work around). ASan doesn't complain about anything.

**Comment by magnumripper** [comment]
> Note to self: In latest version I could drop this workaround

That workaround is back, because I settled for the version that has everything beyond early rejection done in the final kernel. I'm about to merge this soon, despite some CPU drivers failing.

**Comment by solardiz** [comment]
> I'm about to merge this soon, despite some CPU drivers failing.

Would this be a regression - that is, does the current `zip-opencl` work with those CPU drivers? I'm concerned this might indicate a real bug in the new code, which could also show up with some GPUs.

**Comment by magnumripper** [comment]
> Would this be a regression

In a way, but OTOH the format also went from bad to good on AMD Vega under macOS.

> I'm concerned this might indicate a real bug in the new code, which could also show up with some GPUs.

That's what I said too a week ago and I've stared at the code since, I can't find any bug.

Under gdb using pocl, I get this:
```
Device 1: pthread-Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
Benchmarking: ZIP-opencl, WinZip [PBKDF2-SHA1 OpenCL]... -
Thread 9 "john" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc3ffe700 (LWP 297185)]
0x00007ffff7faf397 in u_preproc ()
   from ~/.cache/pocl/kcache/HI/FCCCMMKBMBKIEOBNLPLKFBIPNEFHCJLDAHJEA/zip/7-1-1-goffs0-smallgrid/zip.so
(gdb) bt
#0  0x00007ffff7faf397 in u_preproc ()
   from ~/.cache/pocl/kcache/HI/FCCCMMKBMBKIEOBNLPLKFBIPNEFHCJLDAHJEA/zip/7-1-1-goffs0-smallgrid/zip.so
#1  0x00007ffff7fb3fdc in pbkdf2_hmac_sha1 ()
   from ~/.cache/pocl/kcache/HI/FCCCMMKBMBKIEOBNLPLKFBIPNEFHCJLDAHJEA/zip/7-1-1-goffs0-smallgrid/zip.so
#2  0x00007ffff7fb45f8 in _pocl_kernel_zip_workgroup ()
   from ~/.cache/pocl/kcache/HI/FCCCMMKBMBKIEOBNLPLKFBIPNEFHCJLDAHJEA/zip/7-1-1-goffs0-smallgrid/zip.so
#3  0x00007ffff51b59fd in ?? () from /usr/lib/x86_64-linux-gnu/libpocl.so.2.4.0
#4  0x00007ffff782c609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#5  0x00007ffff7753103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
I take it the segfault happens while running the `preproc()` function and that function has been used for years in many other kernels. I have audited code and buffer sizes many times. I can't see anything wrong.

**Comment by magnumripper** [comment]
This is strange: If using `--lws=1`, both POCL and Intel stop segfaulting and pass self-test.

**Comment by magnumripper** [comment]
> This is strange: If using `--lws=1`, both POCL and Intel stop segfaulting and pass self-test.

Actually not just when using 1: If using either of `--lws` or `--gws` options, or both, it runs just fine on both platforms.

**Comment by ghost** [comment]
POCL failure is expected, Intel on the other hand is complicated: no bad bugs are expected from the proprietary Driver.

> If using either of --lws or --gws options, or both, it runs just fine on both platforms.

So, I would say auto-tune is doing something wrong (or at least the format while auto tuning is doing something bad).

**Comment by magnumripper** [comment]
I nailed it - it was my bumping of max. length to 125 that wasn't supported by the kernel. Down to 64 again and problems gone.

**Pull request merged**
