### PR TITLE
Improve `keplr2john.py` script

### PR DESCRIPTION
**Pull request by ghost**
What it does now :warning: :

```bash
$ python3 run/keplr2john.py john-samples-main/DHCP/   # **** DHCP IS NOT A VALID FOLDER ****
Keplr wallet data extractor

#################################################################################
Users found on the database in the format -> username:$keplr$salt*ciphertext*mac
#################################################################################
```
The proposed version will:

```bash
$ python3 run/keplr2john.py john-samples-main/DHCP/
Data extractor for Keplr wallet (only works with Chrome extension data)

Error:
 - No valid data found in <Keplr_wallet_folder>.
```

I didn't change anything important (I hope):
```bash
$ python3 run/keplr2john.py john-samples-main/Keplr_Wallet/
Data extractor for Keplr wallet (only works with Chrome extension data)

#################################################################################
Users found on the database in the format -> username:$keplr$salt*ciphertext*mac
#################################################################################
uttäb:$keplr$8c27d4300d2de3b209541659c17bc38e63345564d49df4b32c6f20c26cb2bfb5*05dd72de944d59f908339addfd8a42c5433043057a95823a779a32052471c0a9a191099ffd478c6801307e2433a9787838c09c09e4b019e02f0cd1f61d9e0dc88765aa819fb6bcc21ba8cdefc29cb7b6a8*d370e6aa94dbfcbc3029cd41146728c7f8ef9c51a0eb4e0c336118e4a6afba99
[...]
```

Verbose mode:
```bash
$ VERBOSE=1 python3 run/keplr2john.py john-samples-main/Keplr_Wallet/
Data extractor for Keplr wallet (only works with Chrome extension data)

keyring/key-multi-store : [{'bip44HDPath': {'account': 0, 'addressIndex': 0, 'change': 0}, 'coinTypeForChain': {'cosmoshub': 118}, 'crypto': {'cipher': 'aes-128-ctr', 'cipherparams': {'iv': '4d9b46c8a573704780c9770e92a48316'}, 'ciphertext': '8a3b159e9fd7e104049aca4f432575b5bb95c7e3f6829e1549ca9066ed4fcf0a6ff4eb355923a28a4171af171bc36055a2631f10f35dd0b8a5872a51ca9c2c09e7f4e407ec614d546717e1a03c', 'kdf': 'scrypt', 'kdfparams': {'dklen': 32, 'n': 131072, 'p': 1, 'r': 8, 'salt': '31aa4c50f62b54b4e4bf0a1f6ff38ef8bcc3902ab309533037e96ff60ecfd4a6'}, 'mac': '8ed6786d2ea66ac9a2f8347b8c84ff7eb250c0d5a9aae616500f24e635a7ada7'}, 'meta': {'__id__': '1', 'name': 'pepe'}, 'type': 'mnemonic', 'version': '1.2'}]
```

*****
[EDITED]

Improvements:
* We should say "No valid data found in $argv[1]", but let's hear what you guys think first. 
  * No wait, it is not bash. I have no idea of the correct syntax.
  * It is `print(f' - No valid data found in "{sys.argv[1]}" folder.')`

*****

**##### Or event worse #####**

```bash
$ mkdir empty
$ python3 run/keplr2john.py empty/                         
Keplr wallet data extractor

#################################################################################
Users found on the database in the format -> username:$keplr$salt*ciphertext*mac
#################################################################################
```

### CODE REVIEW

**Comment by solardiz** [comment]
Can you please take a look, @alainesp? Thank you!

**Comment by alainesp** [comment]
> Can you please take a look, @alainesp? Thank you!

found_something should be True or False instead of an int. I didn't see any other problem with the changes.

**Comment by ghost** [comment]
Thank you!

I added something else:
- if it's garbage (not a Google technology), two lines in the error message.
- if the content is valid, we can try to debug using verbose (even if it a new version of the wallet);

```
Data extractor for Keplr wallet (only works with Chrome extension data)

Error:
 - No valid data found in "john-samples-main/Monero/" folder.
 - The file was not detected as valid ccl_chrome_indexeddb (LevelDB) technology.

```

[EDITED]

Verbose=1: print  only keyring information.
Verbose=2: print everything.
```
JOHN_VERBOSE=1 python3 run/keplr2john.py john-samples-main/Keplr_Wallet/
JOHN_VERBOSE=2 python3 run/keplr2john.py john-samples-main/Keplr_Wallet/
```

**Review by solardiz — APPROVED** [review]

**Comment by claudioandre-br** [comment]
Solar, wait a second

**Comment by ghost** [comment]
Ready to go!

**Comment by solardiz** [comment]
OK. Longer term, I think we should namespace all of our custom env vars with the `JOHN_` prefix. Both in scripts and in compiled code. But for now, I'm fine with `VERBOSE` here as-is. We already have `FORCE` in another script nearby, which will also need renaming.

**Comment by ghost** [comment]
Done

**Pull request merged**
