### PR TITLE
docs: update CI badges

### PR DESCRIPTION
**Pull request by ghost**
WIP (Circle might be ok).

### CODE REVIEW

**Comment by solardiz** [comment]
Claudio, should I merge this for now?

**Comment by ghost** [comment]
The PR is not wrong, but CI is NOT working.

**Comment by solardiz** [comment]
Thanks Claudio. This repaired the Circle badge (maybe for a short time, as they claim that URL should have just been obsoleted), but not the Travis badge, and neither kind of CI is fully working (even if builds do possibly happen, they're not reflected in PRs). Any suggestions on our next steps at fixing this?

**Comment by ghost** [comment]
If it were I, I would delete the accounts on Travis and Circle, wait a few days for synchronization and then recreate them.

Both CIs/checks are not working. Or you can go deeper into the issues and keep trying to fix them.

**Pull request merged**
