### PR TITLE
Support Blockhain Android-Wallet-2-App format

### PR DESCRIPTION
**Pull request by udisch**
Please squash if merging.

### CODE REVIEW

**Comment by solardiz** [comment]
Thanks @udisch. Unfortunately, this is now failing OpenCL tests on Travis CI, I guess because the list of test vectors is common but you didn't add similar support to the -opencl format - please do.

Also, please move the `{NULL}` back onto its own line. Ideally, also squash your commits, although alternatively we'll be able to use GitHub's "squash and merge".

**Comment by magnumripper** [comment]
This should do it
```diff
diff --git a/run/opencl/blockchain_kernel.cl b/run/opencl/blockchain_kernel.cl
index 976edaac5..200c6764b 100644
--- a/run/opencl/blockchain_kernel.cl
+++ b/run/opencl/blockchain_kernel.cl
@@ -48,6 +48,11 @@ inline int blockchain_decrypt(__global uchar *derived_key,
 	if (out[0] != '{') // fast test
 		return 0;
 
+	// check for android format. See https://github.com/gurnec/btcrecover/issues/203
+	if (memmem_pc(out, 16, "\"address_book", 13)) {
+		return 1;
+	}
+
 	// "guid" will be found in the first block
 	if (memmem_pc(out, 16, "\"guid\"", 6)) {
 		AES_cbc_decrypt(data + 32, out + 16, SAFETY_FACTOR - 16, &akey, iv);
```

**Comment by solardiz** [comment]
Thanks @magnumripper and @udisch! This looks almost right to me now, except there's inconsistent indentation for the added `if` block in the C file - @udisch, can you correct this, please?

**Comment by udisch** [comment]
Had a weird issue with this, replaced with tabs now to be consistent.

**Review by magnumripper — APPROVED** [review]

**Comment by solardiz** [comment]
@magnumripper You ended up using a weird commit message when merging this. Going forward, I think in the rare cases when we have to use "squash and merge", we should generally edit/replace the commit message, which GitHub UI gives us an opportunity to do.

**Pull request merged**
