### PR TITLE
OpenCL 2.0 compatibility fixes

### LINKED ISSUE #4667: Update to NVIDIA 465.24.02 broke wpapsk-opencl
Update to NVIDA 465.24.02 broke wpapsk-opencl:

$ pacman -Q | grep nvidia
nvidia 465.24.02-1
nvidia-settings 465.24.02-1
nvidia-utils 465.24.02-1
opencl-nvidia 465.24.02-1

Affected:
latest release
https://archlinux.org/packages/community/x86_64/john/
as well as latest git head:
$ john
John the Ripper 1.9.0-jumbo-1+bleeding-3088ea62d 2021-04-14 16:10:23 +0200 MPI + OMP [linux-gnu 64-bit x86_64 AVX AC]

$ john --format=wpapsk-opencl --test
Device 1@tux1: NVIDIA GeForce GTX 1080 Ti
Benchmarking: wpapsk-opencl, WPA/WPA2/PMF/PMKID PSK [PBKDF2-SHA1 OpenCL]... Options used: -I opencl -cl-mad-enable -DSM_MAJOR=6 -DSM_MINOR=1 -D__GPU__ -DDEVICE_INFO=524306 -D__SIZEOF_HOST_SIZE_T__=8 -DDEV_VER_MAJOR=465 -DDEV_VER_MINOR=24 -D_OPENCL_COMPILER -DHASH_LOOPS=105 -DITERATIONS=4095 -DPLAINTEXT_LENGTH=63 -DV_WIDTH=1 /usr/share/john/opencl/wpapsk_kernel.cl
Build log: In file included from <kernel>:13:
opencl/opencl_cmac.h:62:22: error: implicit conversion from address space "generic" to address space "private" is not supported when passing to parameter of destination type 
        AES_set_encrypt_key(key, 128, &ctx->aesctx);
                            ^~~
opencl/opencl_aes_bitslice.h:1001:61: note: expanded from macro 'AES_set_encrypt_key'
#define AES_set_encrypt_key(key, bits, ctx) AES_Setkey(ctx, key, (bits) / 8)
                                                            ^
opencl/opencl_aes_bitslice.h:690:45: note: passing argument to parameter 'key' here
AES_Setkey(AES_CTX *ctx, AES_KEY_TYPE void *key, int len)
                                            ^

Error building kernel /usr/share/john/opencl/wpapsk_kernel.cl. DEVICE_INFO=524306
0: OpenCL CL_BUILD_PROGRAM_FAILURE (-11) error in opencl_common.c:1292 - clBuildProgram

Cheers
Mike

### PR DESCRIPTION
**Pull request by magnumripper**
Avoid declaring anything `__private` (it is/was the default anyway) because once we do, a can of worms is opened due to OpenCL 2.0's notion of generic address space.  Problems seen with nvidia 465.xx.

Closes #4667

### CODE REVIEW

**Review by solardiz — APPROVED** [review]
We'll need to test this on more systems/devices, but I don't mind merging first.

I notice this also removes `const` from the first argument of some `hmac_*()`. I wonder why.

**Comment by solardiz** [comment]
BTW, the word "compatibliy" in the commit message looks mistyped.

**Comment by magnumripper** [comment]
Let's not merge yet, I'm testing everywhere I can and have some further fixes coming.

**Comment by magnumripper** [comment]
> I notice this also removes `const` from the first argument of some `hmac_*()`. I wonder why.

It merely moved into the `HMAC_SRC_TYPE` macro - because if you want to use `__constant` address space, we don't want it to end up as `__constant const`. While that *should* be perfectly fine, I have a faint memory some device at some point got upset about it.

**Comment by magnumripper** [comment]
Should be fine now. Some further fixes was needed because the first ones actually *introduced* a problem with nvidia 418.39

**Comment by solardiz** [comment]
I also tested on Tahiti with old fglrx driver. Same behavior before/after this PR: rar-opencl segfaults, and when running with it excluded (`--format=opencl,-rar-opencl`) the final line is `22 out of 88 tests have FAILED`. I suppose this is "fine" for old AMD, and anyhow this PR didn't make things worse.

**Comment by ZerBea** [comment]
Looks like we are running into a new issue on latest git head:
$ john
John the Ripper 1.9.0-jumbo-1+bleeding-c2a24faf3 2021-04-16 18:49:04 +0200 MPI + OMP [linux-gnu 64-bit x86_64 AVX AC]

here:
$ john --test=0 --format=descrypt-opencl
Device 1@tux1: NVIDIA GeForce GTX 1080 Ti
Testing: descrypt-opencl, traditional crypt(3) [DES OpenCL]... [tux1:34694] *** Process received signal ***
[tux1:34694] Signal: Segmentation fault (11)
[tux1:34694] Signal code: Address not mapped (1)
[tux1:34694] Failing at address: (nil)
[tux1:34694] [ 0] /usr/lib64/libpthread.so.0(+0x13960)[0x7f2dffce4960]
[tux1:34694] [ 1] /usr/lib64/libc.so.6(fileno_unlocked+0x4)[0x7f2dffb81134]
[tux1:34694] [ 2] john(+0x3db4ec)[0x55ef88ac14ec]
[tux1:34694] [ 3] john(+0x3d558b)[0x55ef88abb58b]
[tux1:34694] [ 4] john(+0x3d6449)[0x55ef88abc449]
[tux1:34694] [ 5] john(+0x34024f)[0x55ef88a2624f]
[tux1:34694] [ 6] john(+0x330d52)[0x55ef88a16d52]
[tux1:34694] [ 7] john(+0x34b46b)[0x55ef88a3146b]
[tux1:34694] [ 8] /usr/lib64/libc.so.6(__libc_start_main+0xd5)[0x7f2dffb2bb25]
[tux1:34694] [ 9] john(+0x9f09e)[0x55ef8878509e]
[tux1:34694] *** End of error message ***

Maybe a race condition, which is not related to this patch.
@magnumripper can you confirm this?

**Comment by solardiz** [comment]
@ZerBea This is unexpected, and indeed @magnumripper wouldn't have merged the PR if he had seen this in his testing.

However, I notice you're running just `john`, not `./john` or the like. How is this `john` supposed to find its OpenCL kernels? Are you sure it's using the kernels that come with this same git revision?

Normally, we recommend against having `john` in PATH, except for system-wide installs in distro packages, which would also need to take care of the OpenCL kernels somehow.

Can you test with a non-packaged build, running `./john` with the proper `opencl/` directory right there?

**Comment by ZerBea** [comment]
@solardiz I use makepkg (Arch Linux) to build the package and install it via pacman -U.
All other tests are passed fine.
Now I'm going to test a non-package build.

**Comment by ZerBea** [comment]
@solardiz thanks for pointing me to the right direction:
$ ./john --test=0 --format=descrypt-opencl
Device 1: NVIDIA GeForce GTX 1080 Ti
Testing: descrypt-opencl, traditional crypt(3) [DES OpenCL]... PASS

Now everything is fine.
Looks that my pkgbuild and the default pkgbuild of Arch Linux are faulty.

Runnig john from Arch repository
$ john
John the Ripper 1.9.0-jumbo-1 MPI + OMP [linux-gnu 64-bit x86_64 AVX AC]
show this 

$ john --test=0 --format=descrypt-opencl
Device 1@tux1: NVIDIA GeForce GTX 1080 Ti
Testing: descrypt-opencl, traditional crypt(3) [DES OpenCL]... Error creating binary cache file: Permission denied
Error creating binary cache file: Permission denied
Error creating binary cache file: Permission denied
Error creating binary cache file: Permission denied

Not the same like my ERROR, but similar.

Thanks again for your help and your patience.

**Pull request merged**
