### PR TITLE
sipdump2john.py handle ```sip:*``` uri. Fixes #3829

### LINKED ISSUE #3829: SIP does not handle "sip:*" uri
Using the SIP trace log of SNOM phone, I have the problem that the URI looks like this "sip:*" in the authorization header field. 
However, this is not handled in JTP SIP format. 
It leads to a wrong number of fields in the SIP format.

### PR DESCRIPTION
**Pull request by marksilinio**
see https://github.com/openwall/john/issues/3829

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Do you have [sample files](https://github.com/openwall/john-samples) so we can test?

**Comment by marksilinio** [comment]
> Do you have [sample files](https://github.com/openwall/john-samples) so we can test?

you can use https://github.com/openwall/john/issues/3829#issuecomment-484040474 to test

**Comment by ghost** [comment]
It seems an invalid file.

```
Traceback (most recent call last):
  File "/home/claudio/sipdump2john.py", line 29, in <module>
    process_file(i)
  File "/home/claudio/sipdump2john.py", line 20, in process_file
    sys.stdout.write("%s-%s:$sip$*%s\n" % (data[0], data[1], '*'.join(data)))
IndexError: list index out of range
```

Anyway, the PR seems to work fine in python2 and python3 and produces a valid SIP hash (not cracked). I think we should merge and let people test it if nobody has SIP files.

**Review by ghost — APPROVED** [review]

**Comment by marksilinio** [comment]
> It seems an invalid file.
> 
> ```
> Traceback (most recent call last):
>   File "/home/claudio/sipdump2john.py", line 29, in <module>
>     process_file(i)
>   File "/home/claudio/sipdump2john.py", line 20, in process_file
>     sys.stdout.write("%s-%s:$sip$*%s\n" % (data[0], data[1], '*'.join(data)))
> IndexError: list index out of range
> ```
> 
> Anyway, the PR seems to work fine in python2 and python3 and produces a valid SIP hash (not cracked). I think we should merge and let people test it if nobody has SIP files.

You need to test it with:
```
1.2.3.4"5.6.7.8"155350609596347633"sip.provider.com"REGISTER"sip:*"7dfb229f37d9834084f1aa5cdd1e2460"547401db"00000147"auth"MD5"e1facc132ebe3973521a83950ff54994
```

result:
```
./sipdump2john.py testsip.txt
1.2.3.4-5.6.7.8:$sip$*1.2.3.4*5.6.7.8*155350609596347633*sip.provider.com*REGISTER*sip*0.0.0.0**7dfb229f37d9834084f1aa5cdd1e2460*547401db*00000147*auth*MD5*e1facc132ebe3973521a83950ff54994
```

**Pull request merged**
