### PR TITLE
ssh2john.py: Use base64.b64decode instead of codecs.decode

### PR DESCRIPTION
**Pull request by Pecneb**
Used base64.b64decode(data).

### CODE REVIEW

**Comment by Pecneb** [comment]
Hey guys!

**Comment by solardiz** [comment]
@Pecneb Can you please revise the commit message to start with "ssh2john.py: ", e.g. make it:

```
ssh2john.py: Use base64.b64decode instead of codecs.decode
```

Do this with `git commit --amend` followed by `git push -f`. Thanks!

**Review by ghost — APPROVED** [review]
The old and new versions produce identical hashes:

```
$ sha256sum *.txt
c9cd40aab690ab90d614e34e567ed17d417bc2115b64ececbb37f8684aec98b4  new.txt
c9cd40aab690ab90d614e34e567ed17d417bc2115b64ececbb37f8684aec98b4  old.txt

```

**Comment by ghost** [comment]
This pull did not trigger CI (a merge from a 'master of the universe' is required). 

Plus the edit of the commit message via 'squash and merge' (GitHub IDE was used to create the PR).

**Comment by solardiz** [comment]
> Pecneb changed the title No need for codecs for base64 decoding. ssh2john.py: Use base64.b64decode instead of codecs.decode 27 minutes ago

@Pecneb That's not what I asked you to do. I asked you to amend the commit message. You instead edited the PR title. The commit message is what ends up in our project's git history. The PR title is just a GitHub thing, so it doesn't matter as much and can be revised later anyway.

If you cannot amend the commit message (such as because you haven't yet used `git` on the command line and don't yet want to learn that), let us know - we'll use GitHub UI to do so (using the "squash and merge" feature), even though that's suboptimal (makes GitHub appear as the committer in git history).

**Comment by solardiz** [comment]
> This pull did not trigger CI (a merge from a 'master of the universe' is required).

I actually don't know why this didn't trigger CI, but anyhow our CI doesn't check Python scripts, so it doesn't matter (except that it affects who can merge).

**Comment by Pecneb** [comment]
I usually use git in command line, but this wasnt a big change i tought, so i used github UI.

**Comment by Pecneb** [comment]
Ok, managed to pull the branch, then revise it.

**Pull request merged**
