### PR TITLE
Update kirbi2john from nidem/kerberoast

### PR DESCRIPTION
**Pull request by daniruiz**
This python script was originally based on a previous version of the kirbi2john.py script from https://github.com/nidem/kerberoast but is now longer working. This changes are just an adaptation of the latest script version from the original repo

### CODE REVIEW

**Comment by solardiz** [comment]
Thanks @daniruiz. What made the script no longer work? Also, is it compatible with Python 2 or 3 or both? Before and after your changes?

**Comment by daniruiz** [comment]
The old script was python2 only and the new one is python3 only

The update also fixes an issue with the hash output not being recognized by john https://github.com/nidem/kerberoast/issues/19

Also, here's the original kirbi2john.py script from the kerberoast project. I just included the functions that were called from kerberos.py in the same script
https://github.com/nidem/kerberoast/blob/master/kirbi2john.py
https://github.com/nidem/kerberoast/blob/master/kerberos.py#L182

**Comment by solardiz** [comment]
> The old script was python2 only and the new one is python3 only

If so, please update the `#!/usr/bin/env python` line to use `python3`.

Also, please wrap the commit message lines at 75 chars. And fix the typo in "now longer" (should be "no longer").

> The update also fixes an issue with the hash output not being recognized by john [nidem/kerberoast#19](https://github.com/nidem/kerberoast/issues/19)
> 
> Also, here's the original kirbi2john.py script from the kerberoast project. I just included the functions that were called from kerberos.py in the same script https://github.com/nidem/kerberoast/blob/master/kirbi2john.py https://github.com/nidem/kerberoast/blob/master/kerberos.py#L182

This makes me wonder why not take the script from there almost literally, just replacing the `import kerberos` line with two(?) tiny functions we use from there. Would make further updates easier?

However, I'm fine keeping your changes the way they are now, assuming you've tested this.

@exploide @kholia Do you happen to have any comments before we merge this? Thanks!

**Comment by exploide** [comment]
I second the comments from @solardiz.

But I think at first it must be decided whether to include the script from nidem/kerberoast as close as possible, or if we want to deviate form it. Looking at the history there, the script seems to originate from a copy of john in 2015. So it's going back and forth now. (That's the problem of not having a single source of truth...)

If we want to deviate I propose a change to the description of the `files` parameter, which relates to the lines:

```python
for path in args.files:
    for filename in glob.glob(path):
```

Instead of relying to shell globbing (what we should) this accept `'*'` as an argument and resolves it on its own. I propose removing the inner loop, leaving just `for filename in args.files`. And change the parameter's description and remove that part about `'*'`. We neither need to explain to the user how shell globbing works, nor do we need to implement it by accepting the quoted asterisk. It already works when giving an unquoted asterisk because the shell does the globbing for us.

(Side node, I have not run the tool on any test files.)

**Comment by solardiz** [comment]
Oh, sure we need to get rid of `glob`. That's an unexpected misfeature, inconsistent with the rest of our scripts. It can be especially nasty if a filename happens to include a literal shell globbing character in it.

**Comment by daniruiz** [comment]
Agreed with removing glob, that should be handled by the shell :+1: 
I've made the script now look more similar to the original one, adding the 2 extra functions on top. Also removed the glob function. So, now the script is easier to maintain if the original project is updated but does include some changes too

**Comment by solardiz** [comment]
With the glob removal commit, please also remove this from the usage help message: `Use asterisk \'*\' for many files.`

And please prefix that commit message with `kirbi2john.py: `. In fact, the first commit message can also have `kirbi2john.py: Update from nidem/kerberoast` as its first line, but that change is optional since the message does mention the script.

**Comment by daniruiz** [comment]
Nice catch @solardiz. I didn't read that part.
Fixed and pushed

**Review by exploide — APPROVED** [review]

**Pull request merged**
