### PR TITLE
Restic format corrections and minor refactoring

### PR DESCRIPTION
**Pull request by solardiz**
Working OpenMP support.
Benchmark for just one combination of tunable costs.
ALGORITHM_NAME string similar to scrypt format's.
Make format methods static, drop restic_ prefix.
Avoid memory leak in get_salt().
Avoid memcpy() in crypt_all().

### CODE REVIEW

**Comment by solardiz** [comment]
@juergenhoetzel Please take a look. Most notably, this makes OpenMP support actually work - previously, the thread count was never set to anything other than 1.

**Comment by solardiz** [comment]
Forgot to drop `#include "yescrypt/sysendian.h"`, now done in a force-push.

**Comment by solardiz** [comment]
Added "Make format methods static, drop restic_ prefix."
The Ethereum format code that the Restic format was copy-pasted from was different: it shared stuff between its CPU and OpenCL formats. We don't need that here.

**Comment by solardiz** [comment]
All CircleCI tests except for the pending "more-tests" are successful. I've also tested on a POWER7 big-endian system. I'll merge.

**Comment by juergenhoetzel** [comment]
> @juergenhoetzel Please take a look. Most notably, this makes OpenMP support actually work - previously, the thread count was never set to anything other than 1.

Thanks a lot again. Actually I can't explain how it worked without the OpenMP fix. It did use all 8 Threads on my machine, but the code did only allocate 1 thread local:

```
Will run 8 OpenMP threads
```
i should have used `valgrind`  in the first place.

**Comment by juergenhoetzel** [comment]
```C
/* SCRYPT_ALGORITHM_NAME is based on scrypt_fmt.c */
#if !defined(JOHN_NO_SIMD) && defined(__XOP__)
#define SCRYPT_ALGORITHM_NAME "Salsa20/8 128/128 XOP"
#elif !defined(JOHN_NO_SIMD) && defined(__AVX__)
#define SCRYPT_ALGORITHM_NAME "Salsa20/8 128/128 AVX"
#elif !defined(JOHN_NO_SIMD) && defined(__SSE2__)
#define SCRYPT_ALGORITHM_NAME "Salsa20/8 128/128 SSE2"
#else
#define SCRYPT_ALGORITHM_NAME "Salsa20/8 32/" ARCH_BITS_STR
#endif
```
I wonder what the connection is with Salsa20: Copy/Paste error?

**Comment by solardiz** [comment]
> It did use all 8 Threads on my machine

No, I think it did not, even though it said it did. Without the `omp_autotune(self, OMP_SCALE);` call, `self->max_keys_per_crypt` was left at its initial value, which was 1. So the loop in `crypt_all()` only had 1 key to test, and its use of OpenMP was dummy - not an error, just not actually using more than 1 thread.

That said, in case it actually tries to use more threads while sharing a buffer due to some other bug, we'd possibly need more than one test vector with the same salt yet different password to detect that. Can you get one of those generated and add it and try to trigger the issue? Tricky. In fact, you might want to try triggering this kind of issue first, to see if it in fact remains undetected without more test vectors. Thanks!

Unrelated: another thing I noticed is we don't make any use of the first half of KDF output. This is an opportunity to save two SHA-256 computations inside PBKDF2. But it's tricky to do - would involve hacking shared yescrypt code - which is probably not worth it for such minor savings.

**Comment by solardiz** [comment]
> I wonder what the connection is with Salsa20?

scrypt spends most processing time on Salsa20/8.

**Comment by juergenhoetzel** [comment]
> > I wonder what the connection is with Salsa20?
> 
> scrypt spends most processing time on Salsa20/8.

I see: cannot say thank you often enough.

**Pull request merged**
