### PR TITLE
Mask benchmark

### PR DESCRIPTION
**Pull request by magnumripper**
@claudioandre-br I need you to look into your OpenCL formats' reset() functions, removing all or most of your local logic (if something is still "missing" in the shared code that you need there, feel free to add it!). The autotuned variable in opencl_autotune.h is deprecated, we'll remove it.

Just push to this branch.

### CODE REVIEW

**Comment by ghost** [comment]
I would say that:
- it seems ok;
- but `-verbosity=4` changed its behavior. It is unclear to me how users were using it, however.

Still need to run my automated tests on super and my CI; but it seems ok for broad testing.

**Comment by ghost** [comment]
BTW: I can't push. I'll use my branch, so you can cherry pick.

```
$ git push origin novo 
fatal: Erro remoto: 
  You can't push to git://github.com/magnumripper/JohnTheRipper.git
```
[0001-OpenCL-use-mask-benchmark-in-SHA2-formats.txt](https://github.com/magnumripper/JohnTheRipper/files/3563443/0001-OpenCL-use-mask-benchmark-in-SHA2-formats.txt)

***********

**[Edited]**
https://github.com/magnumripper/JohnTheRipper/commit/3c50fc166141570abd46f68e3431d5425387b775

**Comment by ghost** [comment]
So far everything is fine (my commit then -> CI + automated testing in a script).
****

I noticed:
* the axcrypt2 format is advertising LWS and GWS (no one else is doing the same).
```
Testing: axcrypt-opencl [SHA1 AES OpenCL]... PASS
Testing: axcrypt2-opencl, AxCrypt 2.x [PBKDF2-SHA512 AES OpenCL]... PASS
LWS=8 GWS=4096 Testing: bcrypt-opencl ("$2a$05", 32 iterations) [Blowfish OpenCL]... PASS
```
* TODO. Still reading logs.

**Comment by magnumripper** [comment]
Strange, you really should be able to push to this topic branch. But I'll pick it up

**Comment by magnumripper** [comment]
> * but `-verbosity=4` changed its behavior. It is unclear to me how users were using it, however.

I'm open for changes, I wasn't even aware of any change (I kinda use either default or `-v:5`) except we're back into printing LWS/GWS at default verbosity.

What are you expecting for `-v:4`?

**Comment by ghost** [comment]
> > * but `-verbosity=4` changed its behavior. It is unclear to me how users were using it, however.
> 
> I'm open for changes, I wasn't even aware of any change (I kinda use either default or `-v:5`) except we're back into printing LWS/GWS at default verbosity.
> 
> What are you expecting for `-v:4`?

It used to print GWS and LWS. Now, it is almost purposeless. 

Anyway, it's related to JtR messages, not to mask or tuning. Keep it up and listen to people.

**Comment by magnumripper** [comment]
> @claudioandre-br I need you to (...)

Right before I fell asleep yesterday I realized the word "please" (or por favor) was missing in that request of mine 😆 so now I'm not going to miss saying THANKS @claudioandre-br afterwards 👍 😄

**Comment by magnumripper** [comment]
> > > * but `-verbosity=4` changed its behavior. It is unclear to me how users were using it, however.
> > 
> > I'm open for changes, I wasn't even aware of any change (I kinda use either default or `-v:5`) except we're back into printing LWS/GWS at default verbosity.
> > What are you expecting for `-v:4`?
> 
> It used to print GWS and LWS. Now, it is almost purposeless.

OK, but that's good: Maybe we should drop the notion of "verbosity level" as mentioned in #4034 and (now) in a real issue #4086.

**Comment by ghost** [comment]
@magnumripper , have you seen this?

```
[claudio@super src]$ ../run/john -form:rar-opencl -dev:1 --no-mask --test=5
Will run 32 OpenMP threads
Device 1: gfx900 [Radeon RX Vega]
Benchmarking: rar-opencl, RAR3 (length 5) [SHA1 OpenCL AES]... (32xOMP) Error: AutotuneLWS must be a positive number (now set to -1)

[claudio@super src]$ cat ../run/john.conf | grep AutotuneLWS
AutotuneLWS = 1
```

**Comment by magnumripper** [comment]
No... that's strange! Good you found it. What triggers that? Just that device!?

**Comment by magnumripper** [comment]
I wonder if that could be some problem with 24cbe35a03? No... that's only GWS

**Comment by ghost** [comment]
I'm investigating. It is not new!

**Comment by magnumripper** [comment]
I believe it's this
```c
		cfg_lws = cfg_get_int(SECTION_OPTIONS, SUBSECTION_OPENCL,
		                      "AutotuneLWS");
```
If that option is *missing* in config, it will be -1

**Comment by magnumripper** [comment]
We use to do like this (default from params.h)
```c
        if ((words_pair_max = cfg_get_int(SECTION_OPTIONS, NULL,
                                          "SingleWordsPairMax")) < 0)
                words_pair_max = SINGLE_WORDS_PAIR_MAX;
```
but in this case it should probably just be 0. EDIT, it should better be 1

**Comment by magnumripper** [comment]
I'll open a new issue for this, there's more of them

**Comment by ghost** [comment]
Yes, it is inside `cfg_get_int`.

**Comment by magnumripper** [comment]
Fixed in 6ca398049

**Comment by magnumripper** [comment]
I saw a number of Travis CI tests failing yesterday just because they apparently couldn't install fglrx but that seems to be fine now

**Comment by magnumripper** [comment]
I ran TS internal, not 100% clean but also nothing I can associate with this PR

**Comment by magnumripper** [comment]
> I noticed:
> 
> * the axcrypt2 format is advertising LWS and GWS (no one else is doing the same).
> 
> ```
> Testing: axcrypt2-opencl, AxCrypt 2.x [PBKDF2-SHA512 AES OpenCL]... PASS
> LWS=8 GWS=4096 Testing: bcrypt-opencl ("$2a$05", 32 iterations) [Blowfish OpenCL]... PASS
> ```

This was actually the bcrypt format printing its work sizes before even announcing its existence. I'm mostly ignoring such little nuisances with the "bastard formats" that doesn't use shared code. One day or another I'll figure out how to fix them. And having said that, I think I fixed them a little since that output.

**Comment by ghost** [comment]
> Yes, it is inside `cfg_get_int`.

In fact, I was seeing a bug because I have a `john-local.conf `containing:
```
[Options:OpenCL]
Device = 5
```

It was overwriting all [Options:OpenCL] section, so, I didn't have `AutotuneLWS`.

**Comment by magnumripper** [comment]
Ah, yes. You'd better use `[Local:Options:OpenCL]` for not overwriting the rest. I'm not sure how well Jim documented it 😆

**Comment by ghost** [comment]
IMO, things seems is Ok. As a side note:
* some formats are slower (not new info) on mask mode (CPU). E.g., raw-sha256 OpenCL.
```
Device 2:        Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
Raw:	33629K c/s real, 1960K c/s virtual

Device 2:        Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
Raw:	25848K c/s real, 917819 c/s virtual
```
Since we don't target CPUs in JtR OpenCL, that is Ok.
******
**[EDITED]**

Not limited to CPUs.

```
[claudio@super src]$ ../run/john -form:sha256crypt-opencl --test=5
Device 1: gfx900 [Radeon RX Vega]
Benchmarking: sha256crypt-opencl, crypt(3) $5$ (rounds=5000) [SHA256 OpenCL]... LWS=64 GWS=262144 (4096 blocks) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	336698 c/s real, 6553K c/s virtual

[claudio@super src]$ ../run/john -form:sha256crypt-opencl --test=5 --no-mask
Device 1: gfx900 [Radeon RX Vega]
Benchmarking: sha256crypt-opencl, crypt(3) $5$ (rounds=5000) [SHA256 OpenCL]... LWS=64 GWS=524288 (8192 blocks) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	343795 c/s real, 11650K c/s virtual
```

**Comment by magnumripper** [comment]
Yeah not a blocker but it's interesting. Internal mask on GPU device is not necessarily a good thing for one reason or the other. Using NT-opencl, we do get higher figures with mask but they are still lousy.
```
$ ../run/john -test -form:nt-opencl -dev=cpu
Device 1: Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
Benchmarking: NT-opencl [MD4 OpenCL/mask accel]... LWS=1 GWS=32768 (32768 blocks) x100 DONE
Raw:	58688K c/s real, 8535K c/s virtual

$ ../run/john -test -form:nt-opencl -dev=cpu -no-mask
Device 1: Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
Benchmarking: NT-opencl [MD4 OpenCL]... LWS=1 GWS=65536 (65536 blocks) DONE
Raw:	28114K c/s real, 6857K c/s virtual

$ ../run/john -test -form:nt        
Benchmarking: NT [MD4 256/256 AVX2 8x3]... DONE
Raw:	85681K c/s real, 85681K c/s virtual
```
The last figure is using **one** core, the others are using all eight.

**Comment by magnumripper** [comment]
OK so I recall when we had this (non-mask self-test followed by mask benchmark) for Jumbo release candidate, we reverted it for some reason. What was that? Have we tested the same now?

**Comment by ghost** [comment]
> OK so I recall when we had this (non-mask self-test followed by mask benchmark) for Jumbo release candidate, we reverted it for some reason. What was that? Have we tested the same now?

I would say it is in better shape now. Anyway, we need to use JtR as it is now to be sure things are fine (merging or not the PR).

**Comment by magnumripper** [comment]
Yeah I think I'm about to merge it. I have been running it here and there for a month. I'll just sleep on it once more.

**Comment by magnumripper** [comment]
Did now

**Comment by ghost** [comment]
Tomorrow it will be available on [GitHub](https://github.com/claudioandre-br/packages/releases/tag/jumbo-dev) so anyone can test and use it.

**Pull request merged**
