### PR TITLE
Add a config setting for disabling the busy-wait workaround for nvidia

### PR DESCRIPTION
**Pull request by magnumripper**
See #5048

### CODE REVIEW

**Review by solardiz — APPROVED** [review]
Looks good to me, but I think we should drop "Nvidia" from the setting name, so that it's reusable without a rename later in case that is ever needed. Keep this in the comment.

Also, can we reasonably move the ` && gpu_nvidia(device_info[gpu_id])` checks to be done just once at initialization time? We could do `opencl_avoid_busy_wait &&= ...` if we're running post-fork (so that it's a separate variable per GPU). OTOH, that would further tie us to the current model of a process per GPU.

**Comment by magnumripper** [comment]
I pushed a new version - it needed to be put in `opencl_prepare_dev()` instead because some formats use that directly. I also added logging.

I tried it using two devices (GPU and CPU) with `--fork` and it ends up correct. With mscash2-opencl, the logging looks OK but it obviously ends up with the macros enabled even for the CPU device. Not sure how to remedy that other than to put the checks back in the macros.

**Comment by magnumripper** [comment]
I could make it `opencl_avoid_busy_wait[gpu_id]` of course. I'll look into that.

**Comment by magnumripper** [comment]
Done. This should be fine now.

**Comment by magnumripper** [comment]
>  We could do `opencl_avoid_busy_wait &&= ...` if we're running post-fork (so that it's a separate variable per GPU).

I'm not quite sure what you meant there so I'd need a review again.

**Review by solardiz — APPROVED** [review]

**Comment by solardiz** [comment]
This mostly looks good to me, except:

> With mscash2-opencl, the logging looks OK but it obviously ends up with the macros enabled even for the CPU device.

We don't even use the macros in that format, and I think we should not until we rewrite it.

I think this actually points out another issue: you do the logging regardless of whether the format uses the macros or not. This can be confusing. Maybe omit the logging until we start using the macros (almost) universally (maybe with very few exceptions that we'd check for)?

**Comment by magnumripper** [comment]
Changed it to only mention "disabled" for now.

Before we merge, I'll investigate one more thing: IIRC the macros aren't needed on macOS. I just need to find my ten year old nvidia macbook...

**Pull request merged**
