### PR TITLE
aem2john.py: add ability to parse+print user names

### PR DESCRIPTION
**Pull request by minispooner**
added helpful functionality that now allows us to associate a user name with a hash. in both the input AEM hash, and the output John-formatted hash. validated, working fine, allows both types of aem hash input lines (user or no user). hacktheplanet

### CODE REVIEW

**Comment by solardiz** [comment]
@minispooner Thanks! Can you please prefix the commit message with `aem2john.py: `? We try to prefix them with subsystem names to make `git log` more descriptive. Please amend the commit and force-push.

Longer term, I think we should implement support for this formatting directly in JtR and drop this script. In fact, I think we shouldn't have introduced it back then, implementing the support in JtR itself instead. This would be a welcome next contribution. However, I don't mind us enhancing the script for now.

@kholia @exploide Looks good to you? It does to me, except for the commit message.

**Comment by minispooner** [comment]
@solardiz k I updated the commit title. not sure how to edit the commit msg. or did I do what you were asking?

**Comment by solardiz** [comment]
@minispooner No, that's not it. You edited the GitHub PR title, but left the commit message intact. To edit the commit message, you'd use `git commit --amend` and then `git push -f`.

**Comment by minispooner** [comment]
oh I did this in the browser UI cause it's quicker and easier. not sure if I can go back into cli now that the PR is through UI. should I close this one and PR another from CLI?

**Comment by solardiz** [comment]
@minispooner Oh, OK. Yes, it is possible to go from GitHub UI to git CLI, and I just took care of that here.

**Comment by solardiz** [comment]
@minispooner Just to be clear, no further action is needed from you now. Thanks.

**Comment by minispooner** [comment]
Thanks!Ty AndersonOn Dec 22, 2022, at 6:34 PM, Solar Designer ***@***.***> wrote:﻿
@minispooner Just to be clear, no further action is needed from you now. Thanks.

**Comment by minispooner** [comment]
Cool thanks

**Review by exploide — APPROVED** [review]
LGTM

**Review by ghost — APPROVED** [review]
Reviewed.

**Pull request merged**
