### PR TITLE
Fix for #3796 (core in dynamic ad hoc compiler)

### PR DESCRIPTION
**Pull request by jfoug**
Updated pass_gen so I could force set a user name within the dynamic formats.  Needed for work fixing dynamic compiler crash #3796

2nd commit is the fix for #3796

### CODE REVIEW

**Comment by jfoug** [comment]
This is a zero impact change.  pass_gen.pl is not used by john proper or bleeding79

**Comment by jfoug** [comment]
2nd commit somehow pulled in (after the PR).    That commit IS the correction for #3794

**Review by solardiz — APPROVED** [review]
This is good enough for CI and the changes look sane to me, so it's good enough to be merged,

**Comment by solardiz** [comment]
Jim, I merged with "rebase and merge". Thank you!

For further occasions, let's avoid over-long lines in git commit messages. Instead, let's use this format:

```
Commit title up to 72 chars, not ending in a period

After the empty line above, commit description paragraphs with lines of up to
79 chars.

Fixes #3796
```

When applicable, it's also good to start the commit title with `Component name: `.

**Pull request merged**
