### PR TITLE
Use Windows package from Openwall org

### PR DESCRIPTION
**Pull request by ghost**
@solardiz, (if you approve the idea) I guess you'll need to install Azure Pipelines to allow me to push from Azure to a release (automagically).

Captura de tela de 2020-08-06 22-56-57
*****

[Edited] Seems to be here:
https://github.com/marketplace/azure-pipelines

Install it in the organization (not in your account). Then, enter Settings (as seen above), configure, and give it access to the repository.

You're giving access to the app itself. So, the guy pushing must have the "create a release" power (I do in `john-packages` repo).

### CODE REVIEW

**Comment by ghost** [comment]
In fact, an admin also should (unfortunately, I mean, have to) create an account in Travis and Circle (JtR repo needs it) for upstream. We are not talking about repos now, we are acting as the organization.

**Comment by solardiz** [comment]
@claudioandre-br I assume these two are unrelated tasks (Azure vs. Travis/Circle) - for packages publication and for CI, respectively, and can be implemented separately? You already provided clear(-looking) instructions for Azure above (thanks!), but I don't yet know what exactly I am supposed to do for Travis and Circle (are the accounts there somehow tied to the GitHub org? how?) Can you provide instructions on that as well? Thank you!

**Comment by ghost** [comment]
> @claudioandre-br I assume these two are unrelated tasks (Azure vs. Travis/Circle)

Yes. CI (Travis/Circle) is only needed for JtR (upstream) itself.

>  packages publication and for CI, respectively, and can be implemented separately?

Yes. I'm not using CI in Openwall's repos (for a while, at least).

> You already provided clear(-looking) instructions for Azure above (thanks!), but I don't yet know what exactly I am supposed to do for Travis and Circle (are the accounts there somehow tied to the GitHub org? how?) Can you provide instructions on that as well?

In fact, I'm not sure. I would say you (personal account) have to "Sign UP". Then, go to https://travis-ci.org/account/repositories, add you organization (lower left corner)

Captura de tela de 2020-08-07 09-19-00

I can see Openwall (maybe I can request and you approve somehow. For my own organization I see a grant button [not a request button]). We can make some experiments.
Captura de tela de 2020-08-07 09-22-58

**Review by solardiz — APPROVED** [review]
I guess this is ready to merge?

**Comment by solardiz** [comment]
@claudioandre-br Can you please try pressing Request on the Openwall org on Travis CI? Let's see what happens. Ideally, we'd limit the "Write repository hooks" permission to just the right repo, not have it org-wide.

**Comment by ghost** [comment]
A side note, @magnumripper moved to Travis.com some time ago (I'm still building on Travis.org, and it works in a PR as this one). You can choose.

Yes, it is ready to merge. Documentation only (and the destination site is "ok").

**Comment by ghost** [comment]
Done. It seems Circle have to be managed in GitHub itself:https://support.circleci.com/hc/en-us/articles/115014599088-My-GitHub-organization-is-not-listed

**Comment by solardiz** [comment]
Got the request from Travis that says:

"Review third-party application access request
Granting access will give this application the ability to request access to private data in the openwall organization."

Is access to "private data" really what's needed? What do we actually want Travis to be able to do? "Write repository hooks" on your screenshot sounds like the only relevant item, but I am not asked about it.

For Circle, per that support article it looks like the same person needs to access both Circle and GitHub at once to setup the access (what access will we be granting?) Do you have sufficient permissions in the Openwall org to do that, or should I temporarily(?) increase your permissions (and to what)?

**Comment by ghost** [comment]
I pushed againg.

> @magnumripper, please merge. GitHub created 2 _Travis CI - Pull Request_ checks. One is done, the other is imaginary.

**Comment by ghost** [comment]
I noticed the warning about "private data". Personally, I don't care about this because private in GitHub means e-mail, gender, age, ... I don't remember anything else. So, we know what they are doing.

Honestly, I'm not sure if you have a choice. We can run some tests using a fake organization. Probably you, since you have  concerns about the real Openwall org.

> For Circle, per that support article it looks like the same person needs to access both Circle and GitHub

This doesn't seem like a problem to me. Suppose a random user wants to submit a patch for JtR, if he/she wants to run the CI before submitting, he/she needs to create a fork and register with Travis and Circle. If he/she doesn't do this, the Openwall account will run the Pull Request CI. You only need to care about the "upstream" checks. 

For a while, members accounts are in a WIP stage. We must fork all and make PRs, formally.

**Comment by solardiz** [comment]
Claudio,

I approved the Travis request.

As to Azure, I got this far:

```
Install on your organization Openwall @openwall

Only select repositories
Selected 1 repository.
openwall/john-packages

...with these permissions:

Read access to metadata
Read and write access to checks, code, commit statuses, deployments, issues, and pull requests 
```

and when I click through, I get redirected to a Microsoft website asking me to login with a Microsoft account, which I don't have. Should I create one? Maybe instead I can (temporarily) give you privs to the Openwall org to set this up with whatever Microsoft account you've been using? Which way would you prefer, and why?

Similarly for Circle - I guess if you have sufficient permissions in the Openwall org, you'll be able to use your existing Circle account? Would that be a good idea?

**Comment by solardiz** [comment]
Claudio, actually, the "Azure Pipelines" app is now installed with permissions for that repo, despite of me never logging in to Microsoft. So maybe that's sufficient for you to start using it already?

**Comment by ghost** [comment]
Deploy from Azure is **working** (I would say that the right way to go is making these requests, as I just did and you approved).

---
Sorry for the spam (my internet is a zumbi today).

**Comment by claudioandre-br** [comment]
I send you a request from "Azure Pipelines" app from my GitHub account. Tested this new approach in a  fake org I created, it worked fine.

What you did is not working now for me (I would say the right way to go is making these requests). Please, let me know if you see something strange.

**Comment by solardiz** [comment]
Claudio, the way I read your comments, you said two contradictory things within a minute of each other. Can you clarify? First, you said "Deploy from Azure is working", then "What you did is not working now for me". So is it working or not? I did receive one "Third-party application approval request for Openwall" from you for "Azure Pipelines", which I approved. Nothing looked strange to me, except they again ask for access to private resources instead of what actually makes sense in our use case.

**Comment by ghost** [comment]
Sorry, my internet  is not helping. **It is working**. The release is at https://github.com/openwall/john-packages/releases/tag/jumbo-dev

**Pull request merged**
