### PR TITLE
doc/INSTALL-WINDOWS: Fix typo

### PR DESCRIPTION
**Pull request by sp8c3**
just fixed a small typo in the Setup Command

### CODE REVIEW

**Comment by solardiz** [comment]
@Sp8c3 Thanks. Can you please amend the comment message e.g. to "doc/INSTALL-WINDOWS: Fix typo"?

**Comment by sp8c3** [comment]
done ✔️

**Comment by solardiz** [comment]
No, not the PR title. The commit message.

**Comment by solardiz** [comment]
Anyway, I don't know if you made this PR's commit using the command-line `git` (and have experience amending commits and force-pushing) or possibly using GItHub UI (and lack experience). I don't want to discourage you on your very first contribution (even if trivial). So I suppose I'll simply use GitHub's "Squash and merge" and fix the commit message along with that. A drawback is GitHub will then appear as the "committer" in the commits history, but we can live with that. So nevermind.

**Comment by sp8c3** [comment]
Thank you :)
Fixed It now, but anyways took me a while because I indeed did the PR from the Webpage.

**Pull request merged**
