### PR TITLE
Inline strnzcpy() and strnzcpyn()

### PR DESCRIPTION
**Pull request by magnumripper**
I thought we could try this out for a while, verifying it doesn't break anywhere, then maybe add a few more. @solardiz do you think it's worth it at all? Function calls may be cheap but in some cases I reckon stuff can be optimized away when inlined.

See #5620

### CODE REVIEW

**Comment by solardiz** [comment]
> @solardiz do you think it's worth it at all?

For `strnzcpy`, yes, and I had this thought for a while. For other functions, I'm not sure - would need to consider specific cases.

Also, I think you may partially misunderstand the `extern line` in `.c` file thing. I think it was only needed for `MD5_body_for_thread` because `dynamic_types.h` has it as `extern` without including a header file that would have it. I think this is never the case for the two functions you're currently turning into inline in this PR. I also think this `extern inline` thing is never needed as a defense against the compiler just choosing not to inline despite of the `inline` keyword - that will work just fine anyhow, when the right header file with the function definition is included where the function is needed. So let's exclude the `extern inline` from the `.c` files.

**Comment by magnumripper** [comment]
> Also, I think you may partially misunderstand the `extern line` in `.c` file thing. I think it was only needed for `MD5_body_for_thread` because `dynamic_types.h` has it as `extern` without including a header file that would have it. I think this is never the case for the two functions you're currently turning into inline in this PR. I also think this `extern inline` thing is never needed as a defense against the compiler just choosing not to inline despite of the `inline` keyword - that will work just fine anyhow, when the right header file with the function definition is included where the function is needed. So let's exclude the `extern inline` from the `.c` files.

I need to read up on that again and try to understand what you are saying. Several texts mention specificallly the "define inline in .h and declare extern in .c". Such as https://www.greenend.org.uk/rjk/tech/inline.html or https://stackoverflow.com/questions/6312597/is-inline-without-static-or-extern-ever-useful-in-c99/6312854#6312854.

One thing is unclear: Some texts says the header should have a function definition using `inline` and the source file should have a declaration using `extern` - others say the latter should be `extern inline`. Maybe that detail doesn't matter.

**Comment by solardiz** [comment]
> Several texts mention specificallly the "define inline in .h and declare extern in .c". Such as https://www.greenend.org.uk/rjk/tech/inline.html

Oh, I now realize what I missed/forgot. Yes, "the compiler just choosing not to inline despite of the inline keyword [...] will work just fine anyhow", but if this happens more than once (in different translation units that include the header file), then there will be duplicate instances of the function body in the compiled program (no clash, just wasteful). The approach with `extern in .c` under "Strategies for using inline functions" / "A C99 model." over that link you referenced (very helpful) should avoid that.

So you're right, we need those `extern` things for commonly used functions like these. I was wrong.

**Comment by solardiz** [comment]
I took a look at the uses of `valid_utf8`, and I think we shouldn't be inlining this not-so-tiny function into those. So let's limit this PR's experiment to `strnzcpy`, then see whether we have any issues on any previously supported platform.

**Comment by solardiz** [comment]
> let's limit this PR's experiment to `strnzcpy`

... and `strnzcpyn`, which is also used a lot in similar places.

**Review by solardiz — APPROVED** [review]

**Comment by solardiz** [comment]
With this PR, we got a regression for `--enable-ztex` builds:

```
ztex/pkt_comm/cmp_config.o: In function `strnzcpy':
/home/user/j/bleeding-jumbo-20241229/src/ztex/pkt_comm/../../misc.h:121: multiple definition of `strnzcpy'
misc.o:/home/user/j/bleeding-jumbo-20241229/src/misc.h:118: first defined here
ztex/pkt_comm/cmp_config.o: In function `strnzcpyn':
/home/user/j/bleeding-jumbo-20241229/src/ztex/pkt_comm/../../misc.h:146: multiple definition of `strnzcpyn'
misc.o:/home/user/j/bleeding-jumbo-20241229/src/misc.h:142: first defined here
```

**Comment by solardiz** [comment]
> With this PR, we got a regression for --enable-ztex builds

The problem is f88688e273185bfec79d8d5e11cd419ffe41ed12 missed a deeper-level `Makefile.in`.

**Comment by solardiz** [comment]
> > With this PR, we got a regression for --enable-ztex builds
> 
> The problem is [f88688e](https://github.com/openwall/john/commit/f88688e273185bfec79d8d5e11cd419ffe41ed12) missed a deeper-level `Makefile.in`.

I've just fixed this in 41101537f6d75422976c51235aeb0a2e117001e3.

**Pull request merged**
