### PR TITLE
LWS can't be greater than GWS

### PR DESCRIPTION
**Pull request by ghost**
Initialize LWS with the value of GWS if the initial value of LWS is greater than GWS.

### CODE REVIEW

**Comment by ghost** [comment]
I am able to reproduce the `CL_INVALID_EVENT` error. 

It happens because an OpenCL operation [1] failed and the error was ignored, as we are auto tuning. So, I like `CL_INVALID_EVENT`, it highlights bugs.

[1] in the example, a `clEnqueueWriteBuffer` failed. It was before the kernel execution, so `CL_INVALID_EVENT` line 1818.

```
#1 Benchmarking: raw-SHA512-opencl [SHA512 OpenCL/mask accel]... 
[...]
0: OpenCL CL_INVALID_EVENT (-58) error in opencl_common.c:1818 - clWaitForEvents
```

See also #4044

**Comment by ghost** [comment]
The erratic behavior of NVIDIA 1080 is good for detecting bugs.

**Review by magnumripper — APPROVED** [review]

**Comment by magnumripper** [comment]
How is it erratic? I love nvidia for generally being so trouble-free compared to AMD.

**Comment by ghost** [comment]
When it throats, it starts to behave like another board. Then, the code path starts to change.

**Comment by solardiz** [comment]
This PR is now known to have fixed #4313.

**Pull request merged**
