### PR TITLE
mask: initialize properly for benchmarking

### LINKED ISSUE #4376: LM-opencl benchmark causes the next benchmarked format to crash
This reliably occurs when benchmarking all OpenCL formats, but does not occur when benchmarking just mscash-opencl.

```
Benchmarking: LM-opencl [DES BS OpenCL/mask accel]... LWS=128 GWS=131072 DONE
Raw:    6313M c/s real, 6080M c/s virtual

[Thread 0x7fff917fe700 (LWP 31531) exited]
[Thread 0x7fff99fff700 (LWP 31530) exited]
[Thread 0x7fff997fe700 (LWP 31529) exited]
[Thread 0x7fff98ffd700 (LWP 31528) exited]
[Thread 0x7fff91fff700 (LWP 31527) exited]
[Thread 0x7fffa0ffd700 (LWP 31526) exited]
[New Thread 0x7fffa0ffd700 (LWP 31532)]
[New Thread 0x7fff99fff700 (LWP 31533)]
[New Thread 0x7fff997fe700 (LWP 31534)]
[New Thread 0x7fff98ffd700 (LWP 31535)]
[New Thread 0x7fff91fff700 (LWP 31536)]
[New Thread 0x7fff917fe700 (LWP 31537)]
Benchmarking: mscash-opencl, M$ Cache Hash [MD4 OpenCL/mask accel]... LWS=32 GWS=81920 (2560 blocks) x24700
Thread 1 "john" received signal SIGSEGV, Segmentation fault.
set_key (_key=0x3977b640 "#a#A#1.", index=1869417) at opencl_mscash_fmt_plug.c:401
401             saved_idx[index] = (key_idx << 7) | len;
Missing separate debuginfos, use: debuginfo-install bzip2-libs-1.0.6-13.amzn2.0.2.x86_64 gmp-6.0.0-15.amzn2.0.2.x86_64 keyutils-libs-1.5.8-3.amzn2.0.2.x86_64 krb5-libs-1.15.1-37.amzn2.2.2.x86_64 libcom_err-1.42.9-12.amzn2.0.2.x86_64 libcrypt-2.26-34.amzn2.x86_64 libgomp-7.3.1-6.amzn2.0.4.x86_64 libselinux-2.5-12.amzn2.0.2.x86_64 openssl-libs-1.0.2k-19.amzn2.0.3.x86_64 pcre-8.32-17.amzn2.0.2.x86_64 zlib-1.2.7-18.amzn2.x86_64
(gdb) bt
#0  set_key (_key=0x3977b640 "#a#A#1.", index=1869417) at opencl_mscash_fmt_plug.c:401
#1  0x0000000000698937 in bench_generate_keys (my_candidates=0x206dd70 <cand>, cpu_mask_ctx=0x207e9e0 <cpu_mask_ctx>)
    at mask.c:1753
#2  0x000000000069e28d in do_mask_crack (extern_key=0x0) at mask.c:2624
#3  0x00000000006766d8 in bench_set_keys (format=format@entry=0xcb10e0 <fmt_opencl_mscash>, current=current@entry=0x0,
    pass=pass@entry=2) at bench.c:270
#4  0x0000000000676d3a in benchmark_format (format=0xcb10e0 <fmt_opencl_mscash>, salts=256, results=<optimized out>,
    test_db=<optimized out>) at bench.c:527
#5  0x0000000000677b64 in benchmark_all () at bench.c:949
#6  0x000000000068ea6c in john_run () at john.c:1795
#7  main (argc=<optimized out>, argv=<optimized out>) at john.c:2206
(gdb) disass
Dump of assembler code for function set_key:
   0x00000000007678c0 <+0>:     push   %rbp
   0x00000000007678c1 <+1>:     mov    %rsp,%rbp
   0x00000000007678c4 <+4>:     push   %r12
   0x00000000007678c6 <+6>:     push   %rbx
   0x00000000007678c7 <+7>:     mov    %esi,%r12d
   0x00000000007678ca <+10>:    mov    %rdi,%rbx
   0x00000000007678cd <+13>:    callq  0x405080 <strlen@plt>
   0x00000000007678d2 <+18>:    cmpl   $0x1,0x53d257(%rip)        # 0xca4b30 <mask_int_cand+16>
   0x00000000007678d9 <+25>:    mov    %eax,%r9d
   0x00000000007678dc <+28>:    movslq %r12d,%rsi
   0x00000000007678df <+31>:    jle    0x7679e2 <set_key+290>
   0x00000000007678e5 <+37>:    mov    0x191fcdd(%rip),%edx        # 0x20875c8 <mask_gpu_is_static>
   0x00000000007678eb <+43>:    test   %edx,%edx
   0x00000000007678ed <+45>:    jne    0x7679e2 <set_key+290>
   0x00000000007678f3 <+51>:    lea    0x0(,%rsi,4),%rdx
   0x00000000007678fb <+59>:    add    0x19aca1e(%rip),%rdx        # 0x2114320 <saved_int_key_loc>
   0x0000000000767902 <+66>:    mov    0x191fcc7(%rip),%r10        # 0x20875d0 <mask_skip_ranges>
   0x0000000000767909 <+73>:    mov    0x53d218(%rip),%r8        # 0xca4b28 <mask_int_cand+8>
   0x0000000000767910 <+80>:    movl   $0x0,(%rdx)
   0x0000000000767916 <+86>:    movslq (%r10),%rcx
   0x0000000000767919 <+89>:    cmp    $0xffffffff,%ecx
   0x000000000076791c <+92>:    je     0x767bc5 <set_key+773>
   0x0000000000767922 <+98>:    imul   $0x10c,%rcx,%r11
   0x0000000000767929 <+105>:   mov    0x108(%r8,%r11,1),%ecx
   0x0000000000767931 <+113>:   add    0x104(%r8,%r11,1),%ecx
   0x0000000000767939 <+121>:   mov    %ecx,%edi
   0x000000000076793b <+123>:   and    $0xff,%edi
   0x0000000000767941 <+129>:   mov    %edi,(%rdx)
   0x0000000000767943 <+131>:   movslq 0x4(%r10),%r11
   0x0000000000767947 <+135>:   mov    (%rdx),%r12d
   0x000000000076794a <+138>:   cmp    $0xffffffff,%r11d
   0x000000000076794e <+142>:   je     0x767bb8 <set_key+760>
   0x0000000000767954 <+148>:   imul   $0x10c,%r11,%r11
   0x000000000076795b <+155>:   mov    0x108(%r8,%r11,1),%edi
   0x0000000000767963 <+163>:   mov    0x104(%r8,%r11,1),%ecx
   0x000000000076796b <+171>:   add    %edi,%ecx
   0x000000000076796d <+173>:   shl    $0x8,%ecx
   0x0000000000767970 <+176>:   movzwl %cx,%r11d
   0x0000000000767974 <+180>:   or     %r12d,%r11d
   0x0000000000767977 <+183>:   mov    %r11d,(%rdx)
   0x000000000076797a <+186>:   movslq 0x8(%r10),%rdi
   0x000000000076797e <+190>:   mov    (%rdx),%r12d
   0x0000000000767981 <+193>:   cmp    $0xffffffff,%edi
   0x0000000000767984 <+196>:   je     0x767ba9 <set_key+745>
   0x000000000076798a <+202>:   imul   $0x10c,%rdi,%rcx
   0x0000000000767991 <+209>:   mov    0x108(%r8,%rcx,1),%r11d
   0x0000000000767999 <+217>:   mov    0x104(%r8,%rcx,1),%edi
   0x00000000007679a1 <+225>:   add    %r11d,%edi
   0x00000000007679a4 <+228>:   shl    $0x10,%edi
   0x00000000007679a7 <+231>:   and    $0xff0000,%edi
   0x00000000007679ad <+237>:   or     %r12d,%edi
   0x00000000007679b0 <+240>:   mov    %edi,(%rdx)
   0x00000000007679b2 <+242>:   movslq 0xc(%r10),%r10
   0x00000000007679b6 <+246>:   mov    (%rdx),%r12d
   0x00000000007679b9 <+249>:   cmp    $0xffffffff,%r10d
   0x00000000007679bd <+253>:   je     0x767b97 <set_key+727>
   0x00000000007679c3 <+259>:   imul   $0x10c,%r10,%rcx
   0x00000000007679ca <+266>:   mov    0x108(%r8,%rcx,1),%edi
   0x00000000007679d2 <+274>:   add    0x104(%r8,%rcx,1),%edi
   0x00000000007679da <+282>:   shl    $0x18,%edi
   0x00000000007679dd <+285>:   or     %r12d,%edi
   0x00000000007679e0 <+288>:   mov    %edi,(%rdx)
   0x00000000007679e2 <+290>:   mov    0x19ac8a4(%rip),%edi        # 0x211428c <key_idx>
   0x00000000007679e8 <+296>:   mov    0x19ac939(%rip),%r8        # 0x2114328 <saved_idx>
   0x00000000007679ef <+303>:   mov    %edi,%r12d
   0x00000000007679f2 <+306>:   mov    %edi,%edx
   0x00000000007679f4 <+308>:   shl    $0x7,%r12d
   0x00000000007679f8 <+312>:   or     %eax,%r12d
   0x00000000007679fb <+315>:   cmp    $0x4,%eax
=> 0x00000000007679fe <+318>:   mov    %r12d,(%r8,%rsi,4)
   0x0000000000767a02 <+322>:   jle    0x767b8a <set_key+714>
   0x0000000000767a08 <+328>:   lea    -0x5(%rax),%esi
   0x0000000000767a0b <+331>:   lea    0x1(%rdi),%edx
   0x0000000000767a0e <+334>:   mov    0x19ac91b(%rip),%r12        # 0x2114330 <saved_plain>
   0x0000000000767a15 <+341>:   mov    %rbx,%rcx
   0x0000000000767a18 <+344>:   shr    $0x2,%esi
   0x0000000000767a1b <+347>:   mov    %esi,%r9d
   0x0000000000767a1e <+350>:   lea    (%rdx,%rsi,1),%r11d
   0x0000000000767a22 <+354>:   and    $0x7,%r9d
   0x0000000000767a26 <+358>:   je     0x767b20 <set_key+608>
   0x0000000000767a2c <+364>:   lea    0x4(%rbx),%rcx
---Type <return> to continue, or q <return> to quit---q
Quit
(gdb) i r
rax            0x7      7
rbx            0x3977b640       964146752
rcx            0x0      0
rdx            0x0      0
rsi            0x1c8669 1869417
rdi            0x0      0
rbp            0x7fffffffca50   0x7fffffffca50
rsp            0x7fffffffca40   0x7fffffffca40
r8             0x7fff1d000000   140733679927296
r9             0x7      7
r10            0x1      1
r11            0x1      1
r12            0x7      7
r13            0x207ef1c        34074396
r14            0x207f028        34074664
r15            0x207eaec        34073324
rip            0x7679fe 0x7679fe <set_key+318>
eflags         0x10206  [ PF IF RF ]
cs             0x33     51
ss             0x2b     43
ds             0x0      0
es             0x0      0
fs             0x0      0
gs             0x0      0
```

### PR DESCRIPTION
**Pull request by ghost**
Properly initialize mask. Any format benchmarked right after LM-opencl crashes: super's --dev=1 makes the crash reproducible.
*****

I would test the patch again after a good night of sleep, but super is not available right now.

Fixes #4376

### CODE REVIEW

**Comment by solardiz** [comment]
I've just tested this on a V100 on AWS, works just fine. Thanks, Claudio!

```
89 formats benchmarked.
All 89 formats passed self-tests!
```

I didn't have to disable any formats anymore.

I'm still puzzled by why the reported number of formats benchmarked/tests is one greater than the number of "Benchmarking ..." lines, but that's an entirely separate issue.

**Comment by solardiz** [comment]
For further occasions: I think let's not mention hostnames and device numbers in commit messages - this only says anything to a few of us and is noise for most other people, and is going to become out of date. Mentioning GPU types makes more sense, e.g. "on a Vega 64".

**Comment by solardiz** [comment]
I used squash-and-merge this time to edit the commit message. The original sounded a bit like the crashes were seen with this fix, rather than before this fix. I forgot to add a "Fixes ..." line to there, though.

**Comment by ghost** [comment]
Too fast. The commit message could be changed up to 32 seconds ago.

**Pull request merged**
