### PR TITLE
Added the ability to validate Tezos Seed Words

### PR DESCRIPTION
**Pull request by LordDarkHelmet**
Fixed issues with the tezos2john.py file. The previous version did not check the validity of the seed words before producing data for John to use. The check allows users to correct issues with their seed words before spending time trying to crack their password. 

- Validate that exactly 15 seed words are used
- Validate all words are in the same language
- Validate that all words are valid ICO seed words
- Validate seed words pass mnemonic checksum

I have also included the addition of argparse to look at the inputs. This adds the ability to enhance future versions.
- Added "-ignoreICORules" as an attribute, this is used if someone created a Tezos password with non-standard rules

I have added but not tested multiple languages.

### CODE REVIEW

**Comment by LordDarkHelmet** [comment]
Related to Issue:
https://github.com/magnumripper/JohnTheRipper/issues/4040

**Comment by kholia** [comment]
Some of the code doesn't look robust enough (too many things on a single line).

I cannot determine if these changes are necessary and correct.

**Comment by solardiz** [comment]
> Some of the code doesn't look robust enough (too many things on a single line).

How does having "too many things on a single line" affect robustness? Isn't that only a coding style issue?

> I cannot determine if these changes are necessary and correct.

I guess we'll need to trust @LordDarkHelmet on this, unless you have a better suggestion?

**Comment by LordDarkHelmet** [comment]
@solardiz I will be modifying the code to address the concerns that @kholia addressed.

**To address "too many things on one line"**:
Most likely this was referring to the BIP39 word lists. All 2048 words were on a single line for the associated language.  I have verified that the Tezos wallet used the standard BIP39 word list and will be adding the appropriate word list files. This should address the robustness concern and also provide a resource to others so that they can also perform BIP39 validation. 

**To address "if the changes  are necessary"**: 
This is validation of human input. There is nothing downstream that prevents bad input from propagating. For example, this is very invalid, but it is still accepted by John. 

```python tezos2john.py 'Th1S 1s' 'a@bad.Input' 'tz1eF6A2Wo4UeoCS32bAX167J8BWeg5c9ZLX'```

As you can see there are just two seed words (must be mod 3) and there are no associated words on the word list, so I am unsure as to what John is doing with the input information. It should have been rejected as the invalid words do not have a location. Validation will provide an opportunity for the user to correct the issue.

A simple misspelling or typo can lead to a user thinking that John is cracking their password when it is not.  

**To address if the changes are correct**:

I can add a unit test to verify the seed words are properly validated. This will also serve as an opportunity to validate foreign languages. I can do this by using known English BIP39 word locations to create equivalent seed words in all other languages. 

I suggest that we wait until I am able to address these concerns.

**Comment by solardiz** [comment]
Actually, I'd rather merge this PR as-is so that we have this revision in the repository, and then you may submit another. Works for you?

I am not convinced that moving the wordlists to separate files would improve robustness - on the contrary, I'd expect occasional issues with wordlist files not being found when the script is invoked from a different directory, etc.

**Comment by LordDarkHelmet** [comment]
Yes, that works for me. 

I will create checks for verifying that the external files exist. It will be relative to the script location which should limit issues with missing files. 

I am testing foreign languages now. If you have someone on the team who knows Japanese, Korean, or Chinese I would appreciate a test from them when I do the next pull request. I discovered that the Japanese use a different space (at least from my copy and paste from https://github.com/bip32JP/bip32JP.github.io/blob/master/test_JP_BIP39.json). 

```
ord('　')=12288,   IDEOGRAPHIC SPACE
ord(' ')=32,   space
```

I am performing a Unicode normalization "NFKD" which catches that case, but I do not know if other cases exist that will not be caught. 

So, while I can validate the word locations, I do not have a way of reliably verifying that I have identified the delimiters between words in all languages.

**Comment by LordDarkHelmet** [comment]
More changes added to the pipe:

-Added more robustness to the checksum check.  …
-Simplified checksum check (.zfil and binascii.unhexlify)
-Moved BIP39 word list to external files.
-Added Validation of external BIP39 wordlist files (count=2048)
-Added normalization of seed words to handle languages other than English
-Added more robust rule checking options ICO rules and Normal Rules (-i, -I)
-Added more robust input check
-Added validation of external word files.
-Added useful feedback for invalid address.
-Added basic email validation

Created Unittest test_tezos2john.py
-Valid list is translated to a variety of errors and languages.
-Tests are performed on all variations and verified

Unable to perform proper input test for foreign languages, Help with external validation would be appreciated.

To run the unit test: (this will provide verification that it is correct)
```python test_tezos2john.py -v```

**Review by ghost — APPROVED** [review]
I'm merging. So other people can test it.

And it is safe (no "core" changes).

**Pull request merged**
