### PR TITLE
bitcoin2john: python 3 compatibility

### LINKED ISSUE #4143: bitcoin2john.py Python 3 compatibility
A revision of `bitcoin2john.py` (per #4142) when run on an altcoin wallet with Python 2 produces a "hash", whereas when run with Python 3 says "this wallet is not encrypted!" (missing a linefeed after that message - something we should fix as well).

This could indicate a Python 3 compatibility issue in the script itself, or it might be a side-effect of differences in Berkeley DB versions in use by these two Python builds on this system (although I'd have expected the `db.open` call to fail, like it sometimes does, if the DB type is unsupported). To get the script to work with Python 3 on this throw-away Fedora VM, I had to explicitly install Berkeley DB support for it:

```
dnf install libdb-devel python3-devel
pip3 install bsddb3
```

I hope this is right. For Python 2, the system had working Berkeley DB support out of the box.

Also, the uses of `print` in `if __name__ == '__main__':` are Python 2 specific.

Related: #3591, #4085.

### PR DESCRIPTION
**Pull request by exploide**
Made `bitcoin2john.py` python3 compatible. fixes #4143

I targeted the current `bitcoin2john-cleanup2` branch for this Pull Request.

This version of the script produces the same output than before, but this time, working with python2 as well as python3. I tested with the two test wallets from https://openwall.info/wiki/john/sample-non-hashes#Bitcoin-Core-wallet-files

However, I don't know if I missed some edge case or what happens with other wallet types. It would be great if someone could test a little bit more.

BTW, the script had inconsistent indentation and still has. I would have cleaned that up but wanted to keep the diff manageable. Should I do this now in a further commit?

### CODE REVIEW

**Review by solardiz — APPROVED** [review]
I haven't tested the revised script yet, but the changes look good to me as a non-Python person. ;-)

The proposed indentation fixes should be a separate commit, or maybe even a separate PR.

**Comment by solardiz** [comment]
@exploide I'm sorry, but can you please redo this PR (create a new one like it) against bleeding-jumbo branch? It was not only against my temporary branch (which I noticed), but also destined to be merged into that branch (which I didn't notice). Now trying to merge from that branch into bleeding-jumbo results in (fake) merge conflicts, because my two commits appear to be independently done (from git's perspective) in that branch and in bleeding-jumbo after I did a "rebase and merge" of my two commits. I could handle that, but it'd look unclean.

**Comment by solardiz** [comment]
@exploide I already have further changes on top of yours (removing many more lines from that script), but I'd rather have your proper PR properly merged before I introduce those. Thanks!

**Comment by solardiz** [comment]
@exploide ping! I'd like to bring my further changes to here in a proper PR, after yours.

Also, would this copyright statement and license be OK with you? -

```
# This software is
# Copyright (c) 2012-2018 Dhiru Kholia <dhiru at openwall.com>
# Copyright (c) 2019 Solar Designer
# Copyright (c) 2019 exploide
# Redistribution and use in source and binary forms, with or without
# modification, are permitted.  (This is a heavily cut-down "BSD license".)
#
# While the above applies to the stated copyright holders' contributions,
# this software is also dual-licensed under the MIT License, to be certain
# of license compatibility with that of the components listed below.
#
# This script (bitcoin2john.py) might still contain portions of jackjack's
# pywallet.py [1] which is forked from Joric's pywallet.py whose licensing
# information follows,
#
# [1] https://github.com/jackjack-jj/pywallet
#
# PyWallet 1.2.1 (Public Domain)
# http://github.com/joric/pywallet
# Most of the actual PyWallet code placed in the public domain.
# PyWallet includes portions of free software, listed below.
#
# BitcoinTools (wallet.dat handling code, MIT License)
# https://github.com/gavinandresen/bitcointools
# Copyright (c) 2010 Gavin Andresen
```

I intend to introduce this edit to the comment along with my further changes. Thanks!

**Comment by exploide** [comment]
Yeah, I was going to ask how you plan to resolve the merge conflict. But sure, I will create a new PR.

And yes, this copyright statement is fine for me.

**Pull request merged**
