### PR TITLE
RAR format: Allow to use UBSAN in tests on AMD64

### PR DESCRIPTION
**Pull request by ghost**
It seems ok to me as this change will only impact someone when/if UBSAN (a "Development Option") is enabled.

Works fine locally:
```
$ OMP_NUM_THREADS=3 ../run/john --test=0 --format=rar
Will run 3 OpenMP threads
Testing: rar, RAR3 (length 5) [SHA1 256/256 AVX2 8x AES]... (3xOMP) PASS
```

```
$ ../run/john --list=build-info
Version: 1.9.0-jumbo-1+bleeding-82d9e7f383 2024-06-10 10:16:32 -0300
Build: linux-gnu 64-bit x86_64 AVX2 AC OMP UbSan
[...]
Parsed terminal locale: UTF-8
Built with these debugging options
        UbSan (Undefined Behavior Sanitizer debugging)
```

### CODE REVIEW

**Comment by solardiz** [comment]
Hmm, it's surprising this format works with UbSan on any platform, given that it's said to require unaligned accesses and UbSan is supposed to catch those.

Nitpick: you check `__x86_64__` twice.

**Comment by ghost** [comment]
It is (both are defined in my local gcc):
```
__x86_64  VERSUS
__x86_64__
```

I can test using clang before we merge it. gcc 11.4, Ubuntu 22 it works fine. Double checked now.

**Comment by solardiz** [comment]
For some context behind us disabling the RAR format on archs without unaligned access, see https://github.com/openwall/john/issues/2868#issuecomment-349657708 and #4600

The thing with requiring alignment is that passing tests do not guarantee the code is correct and will work on another build. We may just happen to have alignment in that build/run, which isn't unusual - e.g. an array of chars on the stack would most often have greater alignment, yet without a guarantee.

So I'm tempted not to merge this PR without proper understanding as to why this passes UbSan, and whether that's consistent.

**Comment by solardiz** [comment]
> So I'm tempted not to merge this PR without proper understanding as to why this passes UbSan, and whether that's consistent.

And if the reason is there's no unaligned access possibility, including not in actual usage of the format, then we'd need to remove the check - just have this format available on all archs. If the reason is we're lacking a test vector that would expose the issue, we should identify and add such test vector.

**Comment by ghost** [comment]
That is ok. I would like the format to be enabled for testing, but I can ignore the format or patch it for testing.
****
It also works on clang 18 (AVX2, no OMP).

```
[...]
Testing: RAKP, IPMI 2.0 RAKP (RMCP+) [HMAC-SHA1 256/256 AVX2 8x2]... PASS
Testing: rar, RAR3 (length 5) [SHA1 256/256 AVX2 8x2 AES]... PASS
Testing: RAR5 [PBKDF2-SHA256 256/256 AVX2 8x]... PASS
Testing: Raw-SHA512 [SHA512 256/256 AVX2 4x]... PASS
[...]
Testing: dynamic_2014 [md5($s.md5($p).$s) (PW > 55 or salt > 11 bytes) 256/256 AVX2 8x5]... PASS
Testing: dummy [N/A]... PASS
Testing: crypt, generic crypt(3) [?/64]... PASS
All 425 formats passed self-tests
```

```
+ git am 5493.patch
Applying: RAR format: Allow to use UBSAN in tests on AMD64
```

**Comment by ghost** [comment]
Thinking a little more about the problem, it still seems to me that only the test that fails should be disabled using:

E.g., probably: `__attribute__((no_sanitize("alignment")))`. 

Are we not testing it because in some other place, condition or architecture it might fail? Bad strategy.
UBSAN is not just about alignment.

**Pull request closed without merging**
