### PR TITLE
Create 7z2john.py

### PR DESCRIPTION
**Pull request by amandeepdhiman**

### CODE REVIEW

**Comment by ghost** [comment]
Is this a port of the existing tool from Perl to Python? I can see Dhiru as the copyright holder. Is he going to review the code (or the copyright note is wrong)?

Please, let us know your plans.

**Comment by magnumripper** [comment]
The existing `7z2john.pl` was written by @philsmd, not Dhiru. I'm pretty sure the copyright stuff we see here are just copy-paste artifacts from something @amandeepdhiman used as template.

That said, I agree with "let us know your plans". What is this PR about? Is it better than the existing `7z2john.pl` or just about the same? Is it a rewrite from scratch or is it merely a port of Phil's Perl code to Python?

**Comment by magnumripper** [comment]
Also, this version doesn't support BCJ et al, so it's outdated and not usable. Latest version of 7z2john.pl does.

**Comment by magnumripper** [comment]
I'm thinking we should just close this due to the questions raised + no response.

**Comment by kholia** [comment]
Let's close this, please.

I vaguely remember writing some of the code (+ comments!) in this PR. I tried multiple times but failed to get it working well.

We should continue using `7z2john.pl` from @philsmd (thank you!).

**Pull request closed without merging**
