### PR TITLE
ssh2john: python3 compatibility

### PR DESCRIPTION
**Pull request by exploide**
I ported `ssh2john` to python3. Actually only three lines are changed :yum:

### CODE REVIEW

**Comment by solardiz** [comment]
IMO, we need these scripts to work with _both_ Python 2 and Python 3. Turning a Python 2 only script into Python 3 only isn't obviously an improvement yet, as many systems still have Python 2 and where systems have both there are often differences in available library versions - e.g., I found this especially important with differing Berkeley DB versions for `bitcoin2john.py` (a different script, but I think we should use a common approach to those).

@exploide Can you make changes to have this script work with either Python version? And please test those with both versions on test files at https://openwall.info/wiki/john/sample-non-hashes#SSH - make sure the script's output stays the same. IIRC, this script can also process non-SSH PEM files - please try this as well: https://openwall.info/wiki/john/sample-non-hashes#PEM

Thanks!

**Comment by exploide** [comment]
Thanks for your fast response.

Is cross-python-version compatibility a requirement for this project? Then I can try to accomplish your proposed changes.

But to be honest, I do not see the advantage of this. I don't know of fairly modern systems that do not have python3, so I think it should be available. If both, python2 and python3 are available, it's still fine since the script has the appropriate shebang. And maintaining both, python2 and python3 compatibility is definitely more work and bloats the code (generally, not for this script in particular). Regarding that python2 will be EOL in two month, I don't see why this is worth it. You might have a point with the library versions, but this script has only standard imports.

I noticed there are already other python3 only scripts in John.

**Comment by solardiz** [comment]
For new scripts, we accept whatever we're given - it's better to have a Python 2 only or a Python 3 only script than no implementation at all. For existing scripts, so far we haven't been converting Python 2 only to Python 3 only, but we have enhanced some scripts to work with either Python version. We haven't ever made it "a requirement for this project", but I think we also haven't deviated from this practice so far.

**Comment by exploide** [comment]
All right, I made the script py2 and py3 compatible.

I checked that for all SSH sample files, the old version, the new with py2 and the new with py3 produce the same results.

The PEM sample file could not be processed, even with the old version. However `pem2john.py` works on this one. While testing this, I noticed `pem2john.py` included a reference to the old name of `ssh2john.py`. I fixed that as well.

**Review by solardiz — APPROVED** [review]
I trust your testing, so this is good now. Thanks!

My only concern is the added dependency on the "codecs" module - I don't know if it's always installed or might have to be installed by a user. Do you? If "codecs" is not always available, then changes similar to the first commit here but augmented with Python version checks and fallbacks to the existing code would be more portable.

**Comment by exploide** [comment]
`codecs` is a standard import, available in both, python2 and python3. Hence, it is available on every "normal" Python installation.

However, on systems where python (and other packages) are intentionally kept small, for example OpenWrt routers, the `codecs` module, despite being part of the standard library, needs to be installed via a separate package. However, this is also true for most other parts of the library on such systems, so you would have the same trouble with all the other imports in this and other scripts ;)

**Comment by solardiz** [comment]
OK, I'm fine merging this now, but I'd rather let @magnumripper decide on whether to do a merge commit, a rebase of the 3 commits, or a squash and merge. To me, it makes sense to keep your initial commit somewhere in the project's history, such as in case we later choose to support Python 3 only.

**Review by magnumripper — APPROVED** [review]
Groovy

**Comment by magnumripper** [comment]
@exploide, thanks! Just so you know, we are SERIOUSLY lacking contributors right now so any future contributions you might come up with just might be what saves us from giving up. Kudos.

**Comment by solardiz** [comment]
@exploide Is the exception we catch here still the right one after the base64 decode line update or does it maybe also need to be updated? See https://github.com/openwall/john/issues/4564#issuecomment-2901567550

**Comment by exploide** [comment]
The function has been changed to `base64.b64decode()` in #4801 anyway (don't know why I didn't used that one directly in this PR). But `base64.binascii.Error` has always been the correct exception subclass.

**Pull request merged**
