### PR TITLE
bench.c: Always benchmark with one hash per bucket

### LINKED ISSUE #4450: Benchmark passes multi-hash list into crypt_all()
Turns out that for descrypt our `--test` benchmark calls `crypt_all` with a list of 3 hashes for the salt, and for LM with a list of 10. If the format's implementation implements hash comparison in `crypt_all`, it ends up doing more work than the user running the benchmark likely expects: we previously benchmarked for 1 hash per salt. We should probably fix this by using 1-entry lists during benchmark, even if we use multi-entry lists during self-test.

### PR DESCRIPTION
**Pull request by magnumripper**
Closes #4450

### CODE REVIEW

**Comment by magnumripper** [comment]
We might want to add a separate commit that drops the workarounds in `DES_bs_b.c` before we merge. Is that simply the checks of `benchmark_running` in the while loops? We'd still need to check `self_test_running`.

**Comment by solardiz** [comment]
> We might want to add a separate commit that drops the workarounds in `DES_bs_b.c` before we merge.

Please do.

> Is that simply the checks of `benchmark_running` in the while loops? We'd still need to check `self_test_running`.

The `self_test_running` checks should also be dropped - their only purpose was to limit the workaround to the benchmark, excluding the self-test from the workaround.

**Review by solardiz — APPROVED** [review]
Looks correct to me. Thanks!

**Comment by solardiz** [comment]
Confirmed this works as intended - and it does - by temporarily introducing debugging counter/printf into `DES_bs_b.c`.

**Comment by solardiz** [comment]
Didn't notice a commit message was wrong - we don't have a `DES_bs_b.h`.

**Pull request merged**
