### PR TITLE
Fix bug in --stress-test option handling.

### LINKED ISSUE #4351: --stress-test option no longer works
Investigating #4295 I just noticed `--stress-test` option is b0rken. It used to be same as `--test` except it looped the test(s) forever.
```
Invalid options combination or duplicate option: "--stress-test"
```

### PR DESCRIPTION
**Pull request by magnumripper**
Closes #4351

### CODE REVIEW

**Review by solardiz — APPROVED** [review]
So apparently this broke when we enabled mask for "--test" by default. I guess it was also broken for explicit "--test --mask" before. Don't we have the same problem for "--test-full"? Should fix that one as well?

Why are we allowing(?) "--no-log" with "--test" and "--stress-test", can any logging occur during testing? Why are we not allowing that with "--test-full", then?

**Comment by ghost** [comment]
May I merge this?

**Comment by solardiz** [comment]
> May I merge this?

I don't mind, but as I pointed out there are probably a few more closely related things to fix, which we shouldn't forget to at least consider.

**Comment by magnumripper** [comment]
> Why are we allowing(?) "--no-log" with "--test" and "--stress-test", can any logging occur during testing? Why are we not allowing that with "--test-full", then?

I guess they are minor bugs and the reasons are twofold: First, it took me years to even understand how to put these flags right. Second and more important, we were out of options flags for quite some while before I extended them to 64 bits (and now we're severly close to run out of them again).

@claudioandre-br if you want this now, just merge and open an issue for the remaining issues. If you wait with merging I'll try to amend this PR within 24h or so

**Comment by magnumripper** [comment]
> Don't we have the same problem for "--test-full"? Should fix that one as well?

Apparently not, I believe it doesn't use mask.

> Why are we allowing(?) "--no-log" with "--test" and "--stress-test", can any logging occur during testing? Why are we not allowing that with "--test-full", then?

I'll remove that and amend this PR.

**Comment by magnumripper** [comment]
Done, anyone merge once bots are done

**Review by solardiz — APPROVED** [review]
The revised commit looks good to me.

**Pull request merged**
