### PR TITLE
zip2john: workaround false negatives with pkzip archive made by macOS eZip app

### PR DESCRIPTION
**Pull request by magnumripper**
A pkzip archive made by macOS eZip app (closed source but seem to use libarchive) only have a single byte valid checksum. We assume here that EFH 0x6c78 means we can't trust the second byte.  This workaround can't break anything: At worst (if it's too promiscuous) it will lead to slightly worse performance from some (very rare) archives.

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Just in case you need approval

**Comment by magnumripper** [comment]
I don't seem to be able to even look at the bot checks. Are they running at all?

**Comment by ghost** [comment]
> Are they running at all?

No.

**Review by jfoug — APPROVED** [review]
The code appears ok.  with the amount of RW information we have about how the programs build these checksums, I think this is the best way to proceed at this time.

**Comment by magnumripper** [comment]
@solardiz I'm neither powerful enough now to merge this with uncompleted bot checks nor investigate why those checks aren't working. Code is tested and fine though, so please merge at will.

**Comment by solardiz** [comment]
@magnumripper Thanks. I'll see if we can repair the bots before merging this, or will just merge if that would be taking too long.

**Comment by solardiz** [comment]
I've merged this with my admin privs for now. Let's see what happens with the bots next time, now that Travis does see this repo.

**Pull request merged**
