### PR TITLE
CI: disable OpenCL formats that run slowly

### PR DESCRIPTION
**Pull request by ghost**
* some formats are really bad inside CI
* I bet we will gain more than 5 minutes skipping these 3 formats

### CODE REVIEW

**Comment by ghost** [comment]
I'm afraid this PR needs to be merged. Timeouts were frequent yesterday and today.

**Comment by solardiz** [comment]
Maybe we can speed the testing of these formats up by forcing a low GWS?

**Comment by ghost** [comment]
> Maybe we can speed the testing of these formats up by forcing a low GWS?

We do it already. E.g.: Only a few formats do not use shared OpenCL code (and they are ok).

```
$ ../run/john --test=0 -verb=6 --format=ethereum-opencl --dev=4
[...]
TestDB LWS=7 GWS=49 (7 blocks) PASS

```

**Comment by magnumripper** [comment]
Not sure why these formats are so ridiculously slow on CPU device? However, we could try changing the `LWS=7, GWS=49` to eg. `LWS=1, GWS=7` for CPU devices.

**Comment by magnumripper** [comment]
Merged manually. We should look into the "lower worksizes for CPU device" idea.

**Pull request closed without merging**
