### PR TITLE
Tune sha256/512crypt to V100

### PR DESCRIPTION
**Pull request by ghost**
Anyone is going to use a V100 during contest? I don't think so, it's far from cheap.

### CODE REVIEW

**Review by solardiz — APPROVED** [review]
The changes look sane to me, but make me wonder: do we also need to check for Turing separately from Volta? And can we somehow treat all future NVIDIA GPUs the same as the latest revision we tuned for? Or simply make that the default for unknown NVIDIA GPUs, assuming that we do have checks for all known GPU families going far enough back.

**Comment by solardiz** [comment]
Of course, some people will use V100 in the contest, but I guess they'll use hashcat for sha512crypt because apparently it delivers ~370k vs. ~358k you reported with these changes. The difference is now small, but it still does exist. I don't know what the numbers are for sha256crypt and whether it's possibly the other way around - someone should test. Also, especially for contests it's highly desirable to use a lower GWS.

**Comment by ghost** [comment]
> And can we somehow treat all future NVIDIA GPUs the same as the latest revision we tuned for? 

I thought about it, so I compared the value used in sm5x. Yes, we can do that, but I would say it would be more faith than facts.

**Comment by solardiz** [comment]
To "treat all future NVIDIA GPUs the same as the latest revision we tuned for" would be "faith", but it could be faith based on statistics and reasoning. It is reasonable for GPU designers not to hurt performance of programs tuned for the previous generation of GPUs without good reasons, so it is reasonable for us to expect that such differences in required tuning will typically be smaller between adjacent generations than between arbitrary ones.

So I suggest we do make that change.

**Comment by solardiz** [comment]
@claudioandre-br Also, what about Turing? Do we need a check for it? Will you add it?

**Comment by solardiz** [comment]
Here are some benchmarks on bare metal V100 32GB, "Driver Version: 450.51.06    CUDA Version: 11.0":

```
user@twin:~/j/src$ ../run/john -test -form=sha512crypt-opencl
Device 1: Tesla V100-SXM2-32GB
Benchmarking: sha512crypt-opencl, crypt(3) $6$ (rounds=5000) [SHA512 OpenCL]... LWS=256 GWS=1310720 (5120 blocks) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	382134 c/s real, 382134 c/s virtual, Dev#1 util: 100%

user@twin:~/j/src$ ../run/john -test -form=sha256crypt-opencl
Device 1: Tesla V100-SXM2-32GB
Benchmarking: sha256crypt-opencl, crypt(3) $5$ (rounds=5000) [SHA256 OpenCL]... LWS=256 GWS=2621440 (10240 blocks) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	624896 c/s real, 624152 c/s virtual, Dev#1 util: 100%

user@twin:~/j/src$ GWS=20480 ../run/john -test -form=sha512crypt-opencl
Device 1: Tesla V100-SXM2-32GB
Benchmarking: sha512crypt-opencl, crypt(3) $6$ (rounds=5000) [SHA512 OpenCL]... LWS=128 GWS=20480 (160 blocks) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	364990 c/s real, 366805 c/s virtual, Dev#1 util: 97%
```

The last one forces a lower GWS, yet still delivers a decent speed.

**Comment by solardiz** [comment]
My own test on AWS p3.2xlarge, V100 16GB, "Driver Version: 418.87.00    CUDA Version: 10.1", two runs:

```
$ ../run/john -test -form=sha512crypt-opencl
Device 1: Tesla V100-SXM2-16GB
Benchmarking: sha512crypt-opencl, crypt(3) $6$ (rounds=5000) [SHA512 OpenCL]... LWS=256 GWS=2621440 (10240 blocks) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	393019 c/s real, 392725 c/s virtual

$ ../run/john -test -form=sha512crypt-opencl
Device 1: Tesla V100-SXM2-16GB
Benchmarking: sha512crypt-opencl, crypt(3) $6$ (rounds=5000) [SHA512 OpenCL]... LWS=256 GWS=2621440 (10240 blocks) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	391844 c/s real, 391551 c/s virtual
```

Also GWS=20480 (for running tiny wordlists on lots of salts):

```
$ ../run/john -test -form=sha512crypt-opencl -gws=20480
Device 1: Tesla V100-SXM2-16GB
Benchmarking: sha512crypt-opencl, crypt(3) $6$ (rounds=5000) [SHA512 OpenCL]... LWS=32 GWS=20480 (640 blocks) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	368640 c/s real, 368640 c/s virtual
```

All of this looks good to me. I don't know why Claudio had reported somewhat worse speeds.

**Comment by solardiz** [comment]
For comparison, on the same AWS instance with current hashcat, CUDA API:

```
$ ./hashcat -b -O -w3 -m1800
hashcat (v6.1.1-20-gdc9a2468) starting in benchmark mode...

nvmlDeviceGetFanSpeed(): Not Supported

CUDA API (CUDA 10.1)
====================
* Device #1: Tesla V100-SXM2-16GB, 15814/16130 MB, 80MCU

OpenCL API (OpenCL 1.2 CUDA 10.1.236) - Platform #1 [NVIDIA Corporation]
========================================================================
* Device #2: Tesla V100-SXM2-16GB, skipped

Benchmark relevant options:
===========================
* --optimized-kernel-enable
* --workload-profile=3

Hashmode: 1800 - sha512crypt $6$, SHA512 (Unix) (Iterations: 5000)

Speed.#1.........:   392.0 kH/s (82.76ms) @ Accel:8 Loops:256 Thr:1024 Vec:1

Started: Sun Aug  9 15:58:07 2020
Stopped: Sun Aug  9 15:58:22 2020
```

OpenCL API:

```
$ ./hashcat -b -O -w3 -m1800 -d2
hashcat (v6.1.1-20-gdc9a2468) starting in benchmark mode...

nvmlDeviceGetFanSpeed(): Not Supported

CUDA API (CUDA 10.1)
====================
* Device #1: Tesla V100-SXM2-16GB, skipped

OpenCL API (OpenCL 1.2 CUDA 10.1.236) - Platform #1 [NVIDIA Corporation]
========================================================================
* Device #2: Tesla V100-SXM2-16GB, 15744/16130 MB (4032 MB allocatable), 80MCU

Benchmark relevant options:
===========================
* --backend-devices=2
* --optimized-kernel-enable
* --workload-profile=3

Hashmode: 1800 - sha512crypt $6$, SHA512 (Unix) (Iterations: 5000)

Speed.#2.........:   376.1 kH/s (86.45ms) @ Accel:8 Loops:256 Thr:1024 Vec:1

Started: Sun Aug  9 15:59:02 2020
Stopped: Sun Aug  9 15:59:07 2020
```

(I tried running each of these twice, and the other runs were consistent with the above.)

So our OpenCL speed at full GWS is now the same as hashcat's CUDA speed, whereas hashcat's OpenCL speed is somehow a bit lower here.

**Comment by solardiz** [comment]
Oh, but hashcat's `-w4` with CUDA is faster:

```
$ ./hashcat -b -O -w4 -m1800
hashcat (v6.1.1-20-gdc9a2468) starting in benchmark mode...

nvmlDeviceGetFanSpeed(): Not Supported

CUDA API (CUDA 10.1)
====================
* Device #1: Tesla V100-SXM2-16GB, 15814/16130 MB, 80MCU

OpenCL API (OpenCL 1.2 CUDA 10.1.236) - Platform #1 [NVIDIA Corporation]
========================================================================
* Device #2: Tesla V100-SXM2-16GB, skipped

Benchmark relevant options:
===========================
* --optimized-kernel-enable
* --workload-profile=4

Hashmode: 1800 - sha512crypt $6$, SHA512 (Unix) (Iterations: 5000)

Speed.#1.........:   398.6 kH/s (326.13ms) @ Accel:8 Loops:1024 Thr:1024 Vec:1

Started: Sun Aug  9 16:02:49 2020
Stopped: Sun Aug  9 16:02:56 2020
```

OpenCL is still slightly lower than ours:

```
$ ./hashcat -b -O -w4 -m1800 -d2
hashcat (v6.1.1-20-gdc9a2468) starting in benchmark mode...

nvmlDeviceGetFanSpeed(): Not Supported

CUDA API (CUDA 10.1)
====================
* Device #1: Tesla V100-SXM2-16GB, skipped

OpenCL API (OpenCL 1.2 CUDA 10.1.236) - Platform #1 [NVIDIA Corporation]
========================================================================
* Device #2: Tesla V100-SXM2-16GB, 15744/16130 MB (4032 MB allocatable), 80MCU

Benchmark relevant options:
===========================
* --backend-devices=2
* --optimized-kernel-enable
* --workload-profile=4

Hashmode: 1800 - sha512crypt $6$, SHA512 (Unix) (Iterations: 5000)

Speed.#2.........:   382.5 kH/s (340.11ms) @ Accel:8 Loops:1024 Thr:1024 Vec:1

Started: Sun Aug  9 16:04:08 2020
Stopped: Sun Aug  9 16:04:15 2020
```

So best hashcat is 398k+ and best john is 393k.

Anyway, these are now close enough that I guess choice of tool will often be determined by other factors.

**Comment by ghost** [comment]
> All of this looks good to me. I don't know why Claudio had reported somewhat worse speeds.

The best result was 366 Kc/s. Azure (cheapest instance). Quick testing.

BTW: I haven't tested in Turing.

**Comment by solardiz** [comment]
Just for fun, ran CPU benchmarks on a machine with V100. With enough AVX-512 cores, it's actually significant addition to the GPUs:

```
Benchmarking: sha512crypt, crypt(3) $6$ (rounds=5000) [SHA512 512/512 AVX512BW 8x]... (48xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	91701 c/s real, 1908 c/s virtual

Benchmarking: sha256crypt, crypt(3) $5$ (rounds=5000) [SHA256 512/512 AVX512BW 16x]... (48xOMP) DONE
Speed for cost 1 (iteration count) of 5000
Raw:	139109 c/s real, 2905 c/s virtual

Benchmarking: md5crypt, crypt(3) $1$ (and variants) [MD5 512/512 AVX512BW 16x3]... (48xOMP) DONE
Many salts:	3515K c/s real, 73255 c/s virtual
Only one salt:	3308K c/s real, 68799 c/s virtual

Benchmarking: phpass ($P$9) [phpass ($P$ or $H$) 512/512 AVX512BW 16x3]... (48xOMP) DONE
Speed for cost 1 (iteration count) of 2048
Many salts:     2483K c/s real, 51641 c/s virtual
Only one salt:  2004K c/s real, 41760 c/s virtual
```

**Comment by ghost** [comment]
> Just for fun, ran CPU benchmarks on a machine with V100. With enough AVX-512 cores, it's actually significant addition to the GPUs:
> 

Tweet about it. In here the information will be lost

**Pull request merged**
