### PR TITLE
Error out when not SYSTEMWIDE and john_home_path detected empty

### PR DESCRIPTION
**Pull request by ulidtko**
See discussion in #3686

### CODE REVIEW

**Comment by solardiz** [comment]
This is a good idea, thanks! I think we need to make these adjustments:

1. Make it an error (and call `error();` from `misc.h`), not just a warning. It's actually unsafe to have `john` read its `john.conf` and such from the current directory, which might be untrusted.

2. Avoid talking in `argv[0]` terms in the error message, which might be confusing to users who know how to use the shell, but haven't programmed in C.

3. Don't require full pathname in the message, as relative will also work.

So:

```c
			} else {
				fprintf(stderr,
				    "Error: Cannot find John home. Invoke the program via full or relative pathname.\n"
				    "For example, /full/path/john or path/john, or set and use a shell alias.\n");
				error();
			}
```

**Comment by solardiz** [comment]
The failure on Travis CI is irrelevant:

```
The job exceeded the maximum time limit for jobs, and has been terminated.
```

**Review by solardiz — CHANGES_REQUESTED** [review]
Please make and test changes as I proposed in a comment. This will also re-launch CI, hopefully letting us merge the revised PR. Thanks!

**Comment by solardiz** [comment]
BTW, I think keeping source code lines within 80 characters is a lost cause for jumbo, and we can go for up to 132. However, let's try to keep messages printed by `john` within 80 characters, with exceptions for status lines and for messages that embed filenames, etc., which can sometimes grow longer.

**Comment by solardiz** [comment]
Actually, I've made the edit myself. Untested. Let's see what CI says. Let's plan on squashing the two commits when merging.

**Comment by ulidtko** [comment]
Yeah, sorry, you clearly beat me to it while I was unpiling the rest of the inbox :)

**Comment by solardiz** [comment]
Hmm, I now realize this won't work right on Windows, where (except maybe in Cygwin shell? or in there as well?) one can simply type "john" and it will invoke from the current directory - effectively the same as having "." in PATH, but with this being standard and accepted behavior.

Unfortunately, this also means we'd have to accept the security impact of one possibly putting a `c:\full\path\john\run` into PATH on Windows (a wrong thing to do given our current approach, just like it is on Unix) and then running `john` when not being in that directory - it will try to read `john.conf`, etc. from the current directory.

So maybe we need to add e.g.:

```c
#ifdef __unix__
...
#endif 
```

around the code added here. Or there's that variable `dos` we could check at runtime, but it'd be weird to have this code compiled in at all on systems where it's supposed to be dead code.

**Comment by solardiz** [comment]
BTW, it's interesting our CI runs on Wine succeeded. Perhaps we don't rely on "." in PATH there.

I'd appreciate to hear from Claudio and magnum before we possibly add this ifdef/endif thing.

**Comment by ghost** [comment]
I agree: the `ifdef` is needed because "one can simply type "john" and it will invoke from the current directory". 

In fact, I do test "my" deployed package this way. E.g., inside the **phase 2 CI**:

```
    - cd JtR/run
    - powershell "cmd /c 'john --list=build-info'"
```

**Comment by solardiz** [comment]
Thanks Claudio, I've made the change.

What's "phase 2 CI"?

**Comment by ghost** [comment]
> What's "phase 2 CI"?

Basically, it is because I'm testing the **deployed package**, the **released package**, using the (files inside the) GitHub release. To assure everything is ok after the upload (so, I can detect a misbehavior before real users).

**Review by solardiz — APPROVED** [review]
I approve my changes. ;-)

**Comment by solardiz** [comment]
Claudio or magnum, this failed on Travis CI with "The job exceeded the maximum time limit for jobs, and has been terminated." again. Can you override this, so that we can squash and merge? Thanks!

Edit: I guess only magnum can do this?

**Comment by ghost** [comment]
Ready to merge now. Well, what I can do is:
- rerun the job (what I did now);
- make the job optional (allowed to fail)
- remove (again) the slower format(s)

**Pull request merged**
