### PR TITLE
bitcoin2john: python 3 compatibility

### LINKED ISSUE #4143: bitcoin2john.py Python 3 compatibility
A revision of `bitcoin2john.py` (per #4142) when run on an altcoin wallet with Python 2 produces a "hash", whereas when run with Python 3 says "this wallet is not encrypted!" (missing a linefeed after that message - something we should fix as well).

This could indicate a Python 3 compatibility issue in the script itself, or it might be a side-effect of differences in Berkeley DB versions in use by these two Python builds on this system (although I'd have expected the `db.open` call to fail, like it sometimes does, if the DB type is unsupported). To get the script to work with Python 3 on this throw-away Fedora VM, I had to explicitly install Berkeley DB support for it:

```
dnf install libdb-devel python3-devel
pip3 install bsddb3
```

I hope this is right. For Python 2, the system had working Berkeley DB support out of the box.

Also, the uses of `print` in `if __name__ == '__main__':` are Python 2 specific.

Related: #3591, #4085.

### PR DESCRIPTION
**Pull request by exploide**
bitcoin2john: python 3 compatibility; fixes #4143

New PR due to misunderstanding in #4147.

@solardiz do you already have your additional changes present (as code) or is this in a planning state? If the latter I would do the code cleanup commit now. Otherwise I will wait until you are done.

### CODE REVIEW

**Comment by solardiz** [comment]
Thanks, @exploide. I already have my "additional changes present (as code)" - in fact, as several revisions that I intend to commit after merging this PR. So please postpone your code cleanup - in fact, it might not even be needed in the end, as my commits will reduce the number of lines of code much further.

**Comment by exploide** [comment]
Ok, great. Then go ahead :)

**Review by solardiz — APPROVED** [review]
I assume these are exactly the same changes as we had in the previous incarnation of this PR.

**Comment by exploide** [comment]
In fact it is the cherry-picked commit from my previous branch ;)

**Comment by solardiz** [comment]
I'm now waiting for CI to complete before I can merge this, due to this repo's settings...

**Pull request merged**
