### PR TITLE
Assorted fixes and usability enhancements

### PR DESCRIPTION
**Pull request by solardiz**
This closes several issues referenced in the commits.

### CODE REVIEW

**Comment by solardiz** [comment]
Turns out can't `#include` anything that includes `memory.h` before the `#include "mem_map.h"` line (if present), since `mem_map.h` does an `#undef MEM_FREE` when building for Windows.

**Comment by solardiz** [comment]
CI is happy now.
@magnumripper @claudioandre-br You want to review, or OK to merge?

**Review by ghost — APPROVED** [review]
Everything looks correct.

**Review by magnumripper — COMMENTED** [review]
Good stuff, I think

**Pull request merged**
