### PR TITLE
fix overflow in hmac-md5 decoding base64

### LINKED ISSUE #4989: HMAC-MD5 format ASan crash seen in multi-format --fuzz
```
$ OMP_NUM_THREADS=1 time ../run/john -fuzz -format=-md5crypt-long,-scrypt,-andOTP,-argon2,-as400-ssha1,-agilekeychain,-axcrypt,-AndroidBackup,-BestCrypt,-bks,-diskcryptor,-dmg,-dmd5,-DPAPImk,-electrum,-Fortigate256,-Bitcoin,-BitLocker,-bitshares,-ethereum,-Fortigate,-hdaa,-keepass,-krb5tgs,-leet,-luks,-monero,-mscash,-mscash2,-pgpwde,-radius,-sappse,-telegram,-odf,-padlock,-PBKDF2-HMAC-MD4,-PBKDF2-HMAC-MD5,-PBKDF2-HMAC-SHA1,-PBKDF2-HMAC-SHA256,-PBKDF2-HMAC-SHA512,-pfx,-phps,-rsvp,-7z,-lastpass,-zip
[...]
Fuzzing: ZipMonster, MD5(ZipMonster) [MD5-128/128 AVX 4x3 x 50000]...    Completed
Fuzzing: plaintext, $0$ [n/a]...    Completed
Fuzzing: has-160 [HAS-160 32/64]...    Completed
Fuzzing: HMAC-MD5 [password is key, MD5 128/128 AVX 4x3]... =================================================================
==20592==ERROR: AddressSanitizer: global-buffer-overflow on address 0x0000016298c0 at pc 0x4b1c38 bp 0x7ffeb12c6d20 sp 0x7ffeb12c6d18
WRITE of size 1 at 0x0000016298c0 thread T0
    #0 0x4b1c37 in actual_base64_to_raw_conv /home/solar/j/syl/john/src/base64_convert.c:459
    #1 0x4b46f6 in mime_to_raw /home/solar/j/syl/john/src/base64_convert.c:543
    #2 0x4b46f6 in base64_convert /home/solar/j/syl/john/src/base64_convert.c:786
    #3 0x6ef608 in prepare /home/solar/j/syl/john/src/hmacMD5_fmt_plug.c:192
    #4 0x8b8d47 in ldr_split_line /home/solar/j/syl/john/src/loader.c:662
    #5 0x8baf92 in ldr_load_pw_line /home/solar/j/syl/john/src/loader.c:958
    #6 0xbbac62 in fuzz_test /home/solar/j/syl/john/src/fuzz.c:586
    #7 0xbbb04f in fuzz /home/solar/j/syl/john/src/fuzz.c:689
    #8 0x8ae597 in john_run /home/solar/j/syl/john/src/john.c:1672
    #9 0x8ae597 in main /home/solar/j/syl/john/src/john.c:2082
    #10 0x7fc5f5955d1f in __libc_start_main (/lib64/libc.so.6+0x1ed1f)
    #11 0x4069a4 (/home/solar/j/syl/john/run/john+0x4069a4)

0x0000016298c0 is located 0 bytes to the right of global variable 'out' from 'hmacMD5_fmt_plug.c' (0x16297c0) of size 256
SUMMARY: AddressSanitizer: global-buffer-overflow /home/solar/j/syl/john/src/base64_convert.c:459 actual_base64_to_raw_conv
Shadow bytes around the buggy address:
  0x0000802bd2c0: 00 f9 f9 f9 f9 f9 f9 f9 00 00 f9 f9 f9 f9 f9 f9
  0x0000802bd2d0: 00 00 00 00 00 00 00 00 00 f9 f9 f9 f9 f9 f9 f9
  0x0000802bd2e0: 00 00 00 00 f9 f9 f9 f9 00 f9 f9 f9 f9 f9 f9 f9
  0x0000802bd2f0: 00 f9 f9 f9 f9 f9 f9 f9 00 00 00 00 00 00 00 00
  0x0000802bd300: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0000802bd310: 00 00 00 00 00 00 00 00[f9]f9 f9 f9 00 00 00 00
  0x0000802bd320: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0000802bd330: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0000802bd340: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0000802bd350: 00 07 f9 f9 f9 f9 f9 f9 00 00 f9 f9 f9 f9 f9 f9
  0x0000802bd360: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Contiguous container OOB:fc
  ASan internal:           fe
==20592==ABORTING
90011.30user 797.14system 25:14:20elapsed 99%CPU (0avgtext+0avgdata 82718204maxresident)k
1840inputs+5643232outputs (11major+15863480minor)pagefaults 0swaps
```

### PR DESCRIPTION
**Pull request by AlekseyCherepanov**
(closes #4989)

### CODE REVIEW

**Comment by AlekseyCherepanov** [comment]
According to #4989 overflow happens in bas `src/base64_convert.c:459` `actual_base64_to_raw_conv()`:
```c
	if ((flags&flg_Base64_DONOT_NULL_TERMINATE) == 0)
		*cpo = 0;
```

The call in prepare() in `src/hmacSHA1_fmt_plug.c` before fix:
```c
		len = base64_convert(p, e_b64_mime, (int)(d - p - 1),
		                     o, e_b64_raw,
		                     sizeof(out),
		                     flg_Base64_MIME_TRAIL_EQ, 0);
```

Overflow happens if decoded data fills the buffer fully, so null byte goes after the buffer. Null byte is not needed in prepare(), so the flag can be used.

Is it ok that `base64_convert()` can write more than `to_len`?

Alternatively smaller length could be passed to make room for null byte. It might more consistent with code after the call:
```c
		if (len > sizeof(out)-2)
			return split_fields[1];
```

**Comment by AlekseyCherepanov** [comment]
I tested it against a crasher as in #4989 and with --test. I did not run the test suite.

**Comment by AlekseyCherepanov** [comment]
There is the second call to base64_convert. It seems problematic too, but I did not create a crasher yet.

**Comment by AlekseyCherepanov** [comment]
> There is the second call to base64_convert. It seems problematic too, but I did not create a crasher yet.

No, the call seems ok: `o` points to `out` skipping `len`+1 bytes, specified size is `sizeof(out) - len - 2`, so null byte would go into the buffer.

**Comment by solardiz** [comment]
Thanks, Aleksey! Can you rerun `-fuzz` of this format in an ASan build to make sure there's no longer a(nother) crash?

Also, please avoid over-long lines in commit messages. The commit title line should be 72 chars max, further lines (after the empty line) 75 max.

**Comment by AlekseyCherepanov** [comment]
BTW there might be 2 minor problems in `valid()`.

There is check for hex with conditions. I guess a table is used in other places and should be used here too.

There is a check that seems wrong to me:
```c
	p = strrchr(ciphertext, '#'); // allow # in salt
	if (!p || p > &ciphertext[strlen(ciphertext) - 1])
		return 0;
```

I think `p > &ciphertext[strlen(ciphertext) - 1]` may be omitted.

**Comment by AlekseyCherepanov** [comment]
I changed commit message.

**Comment by solardiz** [comment]
> There is check for hex with conditions. I guess a table is used in other places and should be used here too.

Ditto in all other HMAC formats.

> There is a check that seems wrong to me:
> 
> ```c
> 	p = strrchr(ciphertext, '#'); // allow # in salt
> 	if (!p || p > &ciphertext[strlen(ciphertext) - 1])
> 		return 0;
> ```
> 
> I think `p > &ciphertext[strlen(ciphertext) - 1]` may be omitted.

Right, and ditto in `hmacSHA1_fmt_plug.c`. Omitting this check is a trivial fix, so please feel free to add it with a separate commit addressing it for both formats.

Replacing the legacy hex checks in all four formats will require testing, so only do it if you can afford the time. That would be one more commit for all four.

**Comment by solardiz** [comment]
> a table is used in other places

Actually, we now use one of these functions as appropriate:

```
common.h:size_t hexlen(const char *q, int *extra_chars);
common.h:size_t hexlenl(const char *q, int *extra_chars); /* lower cased only */
common.h:size_t hexlenu(const char *q, int *extra_chars); /* upper cased only */
```

Please see e.g. add4ce3661b395975c858f5e4d0219cc81d6b516 for current usage pattern. With this, you'd also avoid `strlen`.

**Comment by AlekseyCherepanov** [comment]
I built john with `--enable-asan --disable-openmp --enable-fuzz` (i.e. not `--enable-libfuzzer`) and kept it running with `--fuzz --format=zipmonster,plaintext,has-160,hmac-md5` for 100+ minutes. I am not sure how long I should keep it to get a crash. (I crafted my crasher manually from the code mentioned in the backtrace in #4989.)

**Comment by solardiz** [comment]
> kept it running with `--fuzz --format=zipmonster,plaintext,has-160,hmac-md5` for 100+ minutes. I am not sure how long I should keep it to get a crash.

Did it even reach fuzzing `hmac-md5`? When run like that, it fuzzes the formats one by one.

**Comment by AlekseyCherepanov** [comment]
Yes, it reached hmac-md5. Other formats were "Completed" rather quick. But hmac-md5 works and works.

**Comment by solardiz** [comment]
Well, the command in #4989 took 25 hours, but it fuzzed many other formats before, including some taking a long while each. Can you just leave it running for some hours, with and without the fix (you'd use 2 cores for that)?

**Comment by AlekseyCherepanov** [comment]
Ok, I'll keep fuzzing running. I have another machine to do that.

Fuzzing with one core and 24 Gb of memory use 23 Gb of swap after 283 minutes (almost 5 hours). Does swap slow down fuzzing? Or leaked memory get into swap and is not used second time?

Is fuzzing purely random? Will I loose progress restarting it on other machine?

**Comment by AlekseyCherepanov** [comment]
I removed check after `strrchr` in 4 formats:
```
hmacMD5_fmt_plug.c:	if (!p || p > &ciphertext[strlen(ciphertext) - 1])
hmacSHA1_fmt_plug.c:	if (!p || p > &ciphertext[strlen(ciphertext) - 1]) return 0;
hmacSHA256_fmt_plug.c:	if (!p || p > &ciphertext[strlen(ciphertext)-1])
hmacSHA512_fmt_plug.c:	if (!p || p > &ciphertext[strlen(ciphertext)-1])
```

`--test` is ok.

**Comment by AlekseyCherepanov** [comment]
> 23 Gb of swap

Oops, I confused free and used. 7 Gb was used. 13 Gb is used 3.5 hours later. That's ~29 Mb/minute.

**Comment by solardiz** [comment]
> removed no-op check after strrchr

Please start commit messages with subsystem name whenever appropriate, so e.g. 'HMAC formats: removed no-op check after strrchr`.

> leaked memory get into swap and is not used second time?

I guess so, although I was only fuzzing on a machine without swap.

> Is fuzzing purely random? Will I loose progress restarting it on other machine?

I think our `--fuzz` is not random at all, which means that yes you will lose all of the progress and would be doing duplicate work.

**Comment by AlekseyCherepanov** [comment]
I changed commit message.

**Comment by AlekseyCherepanov** [comment]
BTW stopping fuzzing with `^C` reports leaks in asan. Also stats reported include only finished formats. (Local paths reduced with `...`)
```
$ /usr/bin/time ./run/john --fuzz --format=zipmonster,plaintext,has-160,hmac-md5
Fuzzing: ZipMonster, MD5(ZipMonster) [MD5-128/128 SSE4.1 4x3 x 50000]...    Completed
Fuzzing: plaintext, $0$ [n/a]...    Completed
Fuzzing: has-160 [HAS-160 32/64]...    Completed
Fuzzing: HMAC-MD5 [password is key, MD5 128/128 SSE4.1 4x3]...   ^CWait...
All 3 formats passed fuzzing test!
Session aborted

=================================================================
==1648==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 402653184 byte(s) in 3 object(s) allocated from:
    #0 0x7f87e06b9330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x5579cb8dde2c in mem_alloc .../john/src/memory.c:90
    #2 0x5579cb8bcc6d in ldr_init_password_hash .../john/src/loader.c:347
    #3 0x5579cb8c3ca8 in ldr_load_pw_line .../john/src/loader.c:973
    #4 0x5579cb963ee3 in fuzz_test .../john/src/fuzz.c:586
    #5 0x5579cb96444d in fuzz .../john/src/fuzz.c:689
    #6 0x5579cb8b9167 in john_run .../john/src/john.c:1672
    #7 0x5579cb8b9167 in main .../john/src/john.c:2082
    #8 0x7f87dfc1509a in __libc_start_main ../csu/libc-start.c:308

Direct leak of 25165824 byte(s) in 3 object(s) allocated from:
    #0 0x7f87e06b9518 in calloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9518)
    #1 0x5579cb8ddf2e in mem_calloc .../john/src/memory.c:107
    #2 0x5579cb8c164d in ldr_init_database .../john/src/loader.c:302
    #3 0x5579cb963d14 in fuzz_test .../john/src/fuzz.c:579
    #4 0x5579cb96444d in fuzz .../john/src/fuzz.c:689
    #5 0x5579cb8b9167 in john_run .../john/src/john.c:1672
    #6 0x5579cb8b9167 in main .../john/src/john.c:2082
    #7 0x7f87dfc1509a in __libc_start_main ../csu/libc-start.c:308

SUMMARY: AddressSanitizer: 427819008 byte(s) leaked in 6 allocation(s).
Command exited with non-zero status 1
9.03user 1.80system 0:11.21elapsed 96%CPU (0avgtext+0avgdata 772380maxresident)k
40072inputs+6760outputs (94major+124785minor)pagefaults 0swaps
```

**Comment by AlekseyCherepanov** [comment]
I had to stop fuzzing of fix on my machine after 10.5 hours. Fuzzing of version without the fix got killed after 12 hours because I've started fuzzing of version with 2 commits. The latter version still works and I can keep it further.

**Comment by AlekseyCherepanov** [comment]
So after 47 hours, fuzzing of `hmac-md5` got killed on machine with 128Gb of ram without swap. Fix for #4990 seems desirable.
```
$ /usr/bin/time ./run/john --fuzz --format=zipmonster,plaintext,has-160,hmac-md5
Fuzzing: ZipMonster, MD5(ZipMonster) [MD5-256/256 AVX2 8x3 x 50000]... Created directory: fuzz_status
   Completed
Fuzzing: plaintext, $0$ [n/a]...    Completed
Fuzzing: has-160 [HAS-160 32/64]...    Completed
Fuzzing: HMAC-MD5 [password is key, MD5 256/256 AVX2 8x3]... Command terminated by signal 9
169965.83user 50.19system 47:13:48elapsed 99%CPU (0avgtext+0avgdata 130415828maxresident)k
214992inputs+62816outputs (984major+40017816minor)pagefaults 0swaps
```

**Pull request merged**
