### PR TITLE
Add Gitpod config

### PR DESCRIPTION
**Pull request by annonymau5**

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
* 100% safe to merge.
* we have 50 hours/month. We can apply for **a free unlimited open source plan**.
* not sure if the image has everything it should.
* it is interesting, but I'm not aware of people that is using it.
  * some introduction text may help.
  * I use VS code myself. So, I'm far from being against it.

**Comment by ghost** [comment]
Are you sure the Dockerfile has anything it should? SSL, zLib, pcap, OpenCL, ...?

I would say you should "sell" your point of view. Why accept the PR? It is interesting, but I don't see any JtR developers using it right now (I could be wrong, not sure about it). [1]
****
BTW, why highlight the IDE/site?

image

****
**[edited]**
[1] Maybe Solar and magnum are fans of _k-pop_ and IDEs nowadays. Who knows!? 

* I have no idea what is _k-pop_, but I love IDEs.

**Review by magnumripper — COMMENTED** [review]
I see no harm in this PR, but I have absolutely no idea what Gitpod is and have no time investigating it.

**Comment by magnumripper** [comment]
OP lost by WO

**Pull request closed without merging**
