### PR TITLE
Fix --status for --fork with --node sessions; support any node ranges divisible by fork count

### LINKED ISSUE #4584: Allow fork divisible node values
I have played around with using --fork instead of openmp as @solardiz suggested and on some nodes I am getting pretty good results. Therefore I would like to implement it on my system. However I have see2, avx and avx2 nodes. As @solardiz suggested "overbooking" them does work however this bring up the issue that some of those machines I do NOT want to use all cores for john (they also have other tasks to do ;)). I understand why --node is connected with --fork and making them independent won't be an easy task. However if I am able to "overbook" --fork it should be also possible (with --fork divisible number) to "overbook" --node. I hope this would be much simpler to implement and won't require big code changes?

### LINKED ISSUE #4589: --status of a --fork session fails to consider --node range found in main .rec file
I have switched to fork in system and as a result had to scale down nodes. Now I think I have encountered another issue with --status switch. Half of the nodes have always status completed. Here is the cmd:
`OMP_NUM_THREADS=1 john --format=descrypt '-2=[opqrstuvwxyz0123456789]' -1=?l?d --min-len=1 --mask=?2?1?1?1?1?1?1?u --node=16-47/47 --fork=32 ./test.pwd --session=test`
When I remove --session and use default session instead of "completed" they simply stop showing progress. I attach relevant screenshots 
[test.pwd.zip](https://github.com/openwall/john/files/6082193/test.pwd.zip)
Zrzut ekranu 2021-03-4 o 09 59 47
Zrzut ekranu 2021-03-4 o 09 56 31
Zrzut ekranu 2021-03-4 o 10 04 33

### PR DESCRIPTION
**Pull request by solardiz**
This is a merge of these changes I had made and tested in core earlier today. In jumbo, I've only tested that these build (but didn't try building with MPI support). I haven't yet tested whether they actually work. I hope @sectroyer and others will help with testing.

Fixes #4589, closes #4584.

### CODE REVIEW

**Comment by solardiz** [comment]
@magnumripper I notice there's MPI-related functionality that was copy-paste-edit from my fork/node stuff. I haven't updated it to mimic my revised code here, merely trying to keep it working like it was before. _Maybe_ it would also benefit from the arbitrary multiples support, or maybe not - I think this is something for you to consider.

**Comment by solardiz** [comment]
> I haven't yet tested whether they actually work.

I just did. My CPU only tests pass just like they did in core. I haven't yet tested with OpenCL nor ZTEX. I'd appreciate others helping test all of these combinations.

BTW, one maybe-shortcoming is that the status lines are prefixed with just one node number - the start of range for each process. So e.g. `-node=9-12/40 -fork=2` produces status lines like these:

```
9 0g 0:00:00:35  0g/s 65.82p/s 223992c/s 223992C/s morti
11 7g 0:00:00:35  0.2000g/s 65.82p/s 228644c/s 228644C/s saria11
```

where the first process is actually virtual nodes 9 and 10, and the second is 11 and 12. Maybe we should prefix these with `9-10` and `11-12`, respectively? Anyway, this would be a separate commit (also to core) and can as well be in a separate PR.

**Comment by solardiz** [comment]
@sectroyer Just to make it clear, you'll need to clone the fork from my personal account to test this before we merge it.

**Comment by sectroyer** [comment]
> @sectroyer Just to make it clear, you'll need to clone the fork from my personal account to test this before we merge it.

I assumed I have to wait for it to merge. K will do that tomorrow. Today fever so have to wait to get little better ;)

**Comment by sectroyer** [comment]
If read code correctly this doesn't have a fix for this: https://github.com/openwall/john/issues/4579#issuecomment-788136376 ?

**Comment by sectroyer** [comment]
Okay I switched to this version and it works just 47 node on 32 core system is always completed :D I guess this has something to do with warning I get ? (attaching screen shots). Command was:
`OMP_NUM_THREADS=1 john --format=descrypt '-2=[pqrstuvwxyz0123456789]' -1=?l?d --min-len=1 --mask=?u?2?1?u?1?1?1?1 --session=~/work//sessions/apic_brute_des_john_1 --node=29-92/92 --fork=32 test.pwd
[test.pwd.zip](https://github.com/openwall/john/files/6096874/test.pwd.zip)
`

Zrzut ekranu 2021-03-7 o 10 28 57
Zrzut ekranu 2021-03-7 o 10 29 06

**Comment by solardiz** [comment]
> If read code correctly this doesn't have a fix for this: [#4579 (comment)](https://github.com/openwall/john/issues/4579#issuecomment-788136376) ?

Yes, this PR is only about what's in its title (edit: plus cosmetic changes related to core's recent move from CVS to Git). It would have been wrong to mix any ETA stuff in here, and besides I am not going to look into ETA issues - I leave that to others.

> it works just 47 node on 32 core system is always completed :D I guess this has something to do with warning I get ?

Looks like that node is somehow getting too little work. Looks like an issue specific to mask mode. As I didn't implement node support for mask mode (I only did for modes that come from core), I am not going to look into this - others might.

Thank you for testing!

**Comment by solardiz** [comment]
> it works just 47 node on 32 core system is always completed :D

@sectroyer I guess you can reproduce this issue with code prior to this PR by using `--node=29-92/92 --fork=64`? If so, this would confirm it's not a bug in this PR's changes, but is an issue we had before. Can you do this test, please? (In fact, I'd expect nodes 47 and 48 to complete early with that test.)

**Comment by sectroyer** [comment]
OK, will test. Meanwhile I noticed other issue. This 32 core machine doesn't finish at all and john enters "infinite loop" or something like that :) Take a look:
image

**Comment by solardiz** [comment]
> This 32 core machine doesn't finish at all and john enters "infinite loop" or something like that :) Take a look

Doesn't look that way. Looks like uneven work distribution between nodes, leaving more work for nodes 29-30 and 91-92 than for all others. I think it's part of the same problem that made nodes 47-48 complete too soon. Someone will need to look into and improve mask mode's work distribution to nodes and test it across a variety of masks and length ranges.

**Comment by magnumripper** [comment]
> @magnumripper I notice there's MPI-related functionality that was copy-paste-edit from my fork/node stuff. I haven't updated it to mimic my revised code here, merely trying to keep it working like it was before. _Maybe_ it would also benefit from the arbitrary multiples support, or maybe not - I think this is something for you to consider.

Right... I think we should just leave MPI as-is.

**Comment by magnumripper** [comment]
> Right... I think we should just leave MPI as-is.

On second thought, a feature we've had for a long time is that any forked run can be stopped and resumed using MPI instead, and vice versa. So I think I'll update the MPI code and test it.

**Comment by solardiz** [comment]
> a feature we've had for a long time is that any forked run can be stopped and resumed using MPI instead, and vice versa.

Did anyone know, besides you?

> So I think I'll update the MPI code and test it.

I guess you'd do that separately from this PR, and after we've merged it, right?

I actually had a different thought regarding MPI: we might want to add an alternative MPI support mode for heterogeneous clusters where the number of virtual nodes would be much greater than the number of logical CPUs in the cluster, and processes would dynamically (via MPI messages) request/obtain next virtual node numbers after they've done their work with the previous number. (Like what I had posted to john-users with many masks and file renames, but instead with many nodes and MPI.) You want to open a separate issue for this?

**Review by magnumripper — APPROVED** [review]
I verified this doesn't seem to cause any regressions with MPI. Will test more later but probably not until making same changes to it (#4594)

**Comment by magnumripper** [comment]
> > a feature we've had for a long time is that any forked run can be stopped and resumed using MPI instead, and vice versa.
> 
> Did anyone know, besides you?

It's clearly documented, but that doesn't mean anyone read it, lol

> > So I think I'll update the MPI code and test it.
> 
> I guess you'd do that separately from this PR, and after we've merged it, right?

Yes.

> I actually had a different thought regarding MPI: we might want to add an alternative MPI support mode for heterogeneous clusters where the number of virtual nodes would be much greater than the number of logical CPUs in the cluster, and processes would dynamically (via MPI messages) request/obtain next virtual node numbers after they've done their work with the previous number. (Like what I had posted to john-users with many masks and file renames, but instead with many nodes and MPI.) You want to open a separate issue for this?

That's a cool idea, for later.

**Comment by sectroyer** [comment]
> > it works just 47 node on 32 core system is always completed :D
> 
> @sectroyer I guess you can reproduce this issue with code prior to this PR by using `--node=29-92/92 --fork=64`?

With those settings node finished without any issues.

**Comment by sectroyer** [comment]
>>Someone will need to look into and improve mask mode's work distribution to nodes and test it across a variety of masks and length ranges.

Should I create a separate issue for this bug ?

**Pull request merged**
