### PR TITLE
Improve workarounds for buggy OpenCL profiling data

### LINKED ISSUE #5265: Fast formats (nt, raw-sha256)-opencl autotune error
As seen below, the `nt-opencl` format is incorrectly calculating the `crypt()` duration time. This is usually related to a wrong `ROUNDS` value set somewhere.

```
c:\Temp\Devel>run\john --test=5 --format=nt-opencl --verbosity=6
initUnicode(UNICODE, RAW/RAW)
RAW -> RAW -> RAW
Device 1: gfx902 [AMD Radeon(TM) Vega 8 Graphics]
Benchmarking: NT-opencl [MD4 OpenCL/mask accel]... Loaded 44 hashes with 1 different salts to test db from test vectors
TestDB LWS=8 GWS=48 (6 blocks) PASS,
Test mask: ?a?a?l?u?d?d?s
Expecting "no" false positives
44 hashes: bitmap 4x32768 bits, mask 0x7fff, effectively 38 bits (0x3fffffffff), 16 KiB (local)
Offset tbl 104 B, Hash tbl 360 B, Results 532 B, Dupe bmp 8 B, TOTAL on GPU: 17388 B
Options used: -I opencl -cl-mad-enable -cl-std=CL1.2 -D__GPU__ -DDEVICE_INFO=522 -D__SIZEOF_HOST_SIZE_T__=8 -DDEV_VER_MAJOR=3075 -DDEV_VER_MINOR=13 -D_OPENCL_COMPILER -D OFFSET_TABLE_SIZE=26 -D HASH_TABLE_SIZE=45 -DUCS_2 -D NUM_LOADED_HASHES=44 -D NUM_INT_KEYS=2470 -D SELECT_CMP_STEPS=4 -D BITMAP_MASK=0x7fffU -D USE_LOCAL_BITMAPS=1 -D IS_STATIC_GPU_MASK=1 -D CONST_CACHE_SIZE=3230701977 -DENC_RAW -DENC_RAW -DPLAINTEXT_LENGTH=27 -D LOC_0=0 -D LOC_1=2 -D LOC_2=-1 -D LOC_3=-1 $JOHN/opencl/nt_kernel.cl
binary size 61824
Internal mask, multiplier: 2470 (target: 2048)
Calculating best GWS for LWS=64; max. 200 ms single kernel invocation.
Raw speed figures including buffer transfers:
Tuning for password length 7
key xfer: 3.680 us, idx xfer: 1.919 us, crypt: 1266874666.407 s* (exceeds 200 ms)
key xfer: 2.880 us, idx xfer: 2.080 us, crypt: 1266874666.406 s* (exceeds 200 ms)
Calculating best LWS for GWS=64
Note: Profiling timers seem buggy
Testing LWS=64 GWS=64 ... 1266874666.406 s
Calculating best GWS for LWS=64; max. 200 ms single kernel invocation.
Raw speed figures including buffer transfers:
key xfer: 4.160 us, idx xfer: 2.400 us, crypt: 1266874666.406 s* (exceeds 200 ms)
key xfer: 3.200 us, idx xfer: 2.240 us, crypt: 1266874666.406 s* (exceeds 200 ms)
TestDB LWS=64 GWS=512 (8 blocks) x2470 DONE
Raw:    307814K c/s real, 2210M c/s virtual
```

### PR DESCRIPTION
**Pull request by ghost**
#4598 has the value 8.7s (I can increase my magic number from 5s to 10s if that makes sense)

The values obtained from autotune are:
- startTime   = 18446744057352783936
- endTime     = 18446744057356799936
- submitTime  = 323781007400

Closes #5265
Related to #4598

### CODE REVIEW

**Review by magnumripper — APPROVED** [review]
This looks fine to me

**Comment by ghost** [comment]
Thank you

**Comment by magnumripper** [comment]
I just noticed i get this now, on macOS:
```
opencl_common.c: In function 'gws_test':
opencl_common.c:1589:25: error: format '%lu' expects argument of type 'long unsigned int', but argument 3 has type 'cl_ulong' {aka 'long long unsigned int'} [-Werror=format=]
 1589 |    fprintf(stderr, " [%lu, %lu, %lu, %u, %d]", startTime, endTime,
      |                       ~~^                      ~~~~~~~~~
      |                         |                      |
      |                         long unsigned int      cl_ulong {aka long long unsigned int}
      |                       %llu
opencl_common.c:1589:30: error: format '%lu' expects argument of type 'long unsigned int', but argument 4 has type 'cl_ulong' {aka 'long long unsigned int'} [-Werror=format=]
 1589 |    fprintf(stderr, " [%lu, %lu, %lu, %u, %d]", startTime, endTime,
      |                            ~~^                            ~~~~~~~
      |                              |                            |
      |                              long unsigned int            cl_ulong {aka long long unsigned int}
      |                            %llu
opencl_common.c:1589:35: error: format '%lu' expects argument of type 'long unsigned int', but argument 5 has type 'cl_ulong' {aka 'long long unsigned int'} [-Werror=format=]
 1589 |    fprintf(stderr, " [%lu, %lu, %lu, %u, %d]", startTime, endTime,
      |                                 ~~^
      |                                   |
      |                                   long unsigned int
      |                                 %llu
 1590 |            submitTime, rounds, hash_loops);
      |            ~~~~~~~~~~              
      |            |
      |            cl_ulong {aka long long unsigned int}
cc1: all warnings being treated as errors
make[1]: *** [opencl_common.o] Error 1
make: *** [default] Error 2
```
I'm puzzled I don't see it under Linux - they should be the same wrt `long` vs. `long long`. **EDIT** it's probably just `cl_ulong` that differs.

For printing `uint64_t`, we need to either use the `PRIu64` macro instead of `%lu` or `%llu` - or cast the variables to (in this case) `(long unsigned int)`. **EDIT** we print `cl_ulong` here, so probably need to cast.

**Comment by ghost** [comment]
If you don't create a new PR, I will propose one using cast.

Thanks.

**Pull request merged**
