### PR TITLE
Discard -m64 from LDFLAGS

### PR DESCRIPTION
**Pull request by lucic71**

### CODE REVIEW

**Comment by lucic71** [comment]
Closes #5240

**Comment by ghost** [comment]
Since it passed CI, that's fine with me, but probably magnum wants to say something.

BTW: 
* we believe you have tested it and it solves your problem;
* the commit message should be more like this:

autoconf: discard -m64 from LDFLAGS

**Review by magnumripper — APPROVED** [review]
It's probably perfectly fine but I have no time for regression testing. Is this the only place we needed to remove it though? I would have guessed more places but it was many many years ago (and the m4 files are a mess).

**Comment by ghost** [comment]
@lucic71 could you please amend the commit message? I cannot Squash and Merge using GitHub UI.

You have troubles:
```
git commit -a --amend # just edit the text
git push origin lucic71:bleeding-jumbo -f
```
BTW: could you add a note to Changes-jumbo:

Something simple as:
```
Fix configure. Remove '-m64' from configure, do not add -m64 in LDFLAGS.
```
Thanks.
****
> It's probably perfectly fine but I have no time for regression testing. Is this the only place we needed to remove it though? I would have guessed more places but it was many many years ago (and the m4 files are a mess).

I haven't found any other places except Makefile.legacy. And I'd rather leave it alone.

**Comment by solardiz** [comment]
> could you add a note to Changes-jumbo:

We only have `CHANGES-jumbo` (which we haven't updated since our release in 2019 and _might_ update before next release again using git history or drop it) and `NEWS` (into which noteworthy changes go, and this one is not). So let's not add any note about the minor change here.

As to the commit message, yes, prefixing it with `autoconf: ` or `configure*: ` would be appropriate, but I wouldn't insist.

**Comment by solardiz** [comment]
And yes, let's leave `Makefile.legacy` alone. It does use `-m64` in some make targets, but that's because it was needed in those. Incidentally, this gives us a check list for which platforms to test this PR's change on.

**Comment by solardiz** [comment]
We auto-detect Solaris 10 and 11 sparc64 systems as 32-bit and produce a working 32-bit build, but `gmake -f Makefile.legacy solaris-sparc64-gcc` produces a working 64-bit build, which runs faster - and it needs the `-m64` on linking there. Omitting `-m64` from `LDFLAGS` results in:

```
ld: fatal: file jumbo.o: wrong ELF class: ELFCLASS64
ld: fatal: file john_mpi.o: wrong ELF class: ELFCLASS64
ld: fatal: file DES_fmt.o: wrong ELF class: ELFCLASS64
```

and so on for all other object files built with `-m64`.

Given this knowledge, instead of merging this PR should we perhaps fix auto-detection of 64-bit for systems like this?

**Comment by ghost** [comment]
> it needs the `-m64` on linking there.

Like magnum predicted. 

Well, at least for now, we should avoid to merge.
***

It seems it is possible to CI using Solaris: I am going to try.

**Review by solardiz — APPROVED** [review]
Looks good to me. Thanks!

**Comment by solardiz** [comment]
Now the commit message isn't exactly right because with this change we don't add (not discard) `-m64` to all of `CFLAGS`, `ASFLAGS`, and `LDFLAGS` (not only `LDFLAGS`). But I'll go ahead and merge this anyway - it's taking us too much time already.

**Comment by ghost** [comment]
>
> Now the commit message isn't exactly right because ...
>

Something to think about: re-enable the squash option so that the approver
can edit the commit message if needed.

**Comment by magnumripper** [comment]
It's disabled? Where, how?

**Comment by ghost** [comment]
> It's disabled? Where, how?

There are no more PRs available here. Anyway, you can understand by looking at the picture below (merge commit is disabled):

image

Edit at (probably at https://github.com/openwall/john/settings): 

image

**Pull request merged**
