### PR TITLE
Do not abort on seeing a UTF-16 BOM in input file or wordlist, just warn

### LINKED ISSUE #4238: Review UTF-16 detection and other encoding detections (fatal error vs. warning)
https://www.openwall.com/lists/john-users/2020/03/27/4

I can't remember: Maybe the fatal error only happens when detecting UTF-16 in *input files* (as in *hash files*), I'm not quite sure we check *wordlists* for just that at all. Anyway we should probably almost never die from problems seen in a wordlist (potentially a long way into a session), only warn. While we're at it, I believe we currently die on seeing a NULL in a wordlist (probably only when buffering/indexing to RAM) and that too might be better as just a warning.

On a side note, I've been meaning to add (optional) color to warnings, eg. yellow for important notes/reminders and red for worse problems. Sometimes it's easy to miss a crucial note and even more so if we revert to chug-along behavior per above.

### PR DESCRIPTION
**Pull request by magnumripper**
Closes #4238, see also #2812

### CODE REVIEW

**Review by solardiz — APPROVED** [review]
Thank you for fixing that issue! This mostly looks good to me, but I suggest edits to the messages: 
"password hash file" instead of "input file" and "NUL" instead of "NULL" when speaking about characters.

**Comment by magnumripper** [comment]
Done, although I consistently call it the "input file" in discussions and docs (I don't use that term for eg. wordlists).

**Comment by solardiz** [comment]
OK. Looks good to me now.

**Comment by solardiz** [comment]
All tests except for the pending Circle more-tests have passed, and I am able to merge without needing to override anything. So our CI is working well again, to the same extent it worked before the repo move.

I'll merge this now.

**Pull request merged**
