### PR TITLE
dynamic: tweaks for valid

### PR DESCRIPTION
**Pull request by AlekseyCherepanov**
Related to #5032.

### CODE REVIEW

**Comment by AlekseyCherepanov** [comment]
I added extra strict code. It duplicates existing checks partially. Conveniently it is localized to formats with salts with variable length.

While my code rejects more than I would like, it accepts all self-tests without adjustments. `--format=dynamic --test=0` and `--format=disabled --test=0` are ok.

The following comment made me think @jfoug might want fixes to be emphasized and localized:
```c
// NOTE if looking at this in the future, this was not my fix.
```

I did not find any existing format using fields (`$$F`). There are formats with salt-2 (`$$2`) and usernames (`$$U`), but they seem to use flat buffers and do not suffer from overflows.

Maybe I should investigate, how flat buffers handle overly long intermediate input, and fix `__SSE_append_string_to_input` to behave similarly. OTOH it might affect performance.

Besides from salt-only formats, the following formats have the problem and `SaltLen` correct for both salt and username. So I use its value to check both lengths:
```
dynamic_1015 [md5(md5($p.$u).$s) (PostgreSQL 'pass the hash') 128/128 SSE4.1 4x3]
dynamic_1034 [md5($p.$u) (PostgreSQL MD5) 128/128 SSE4.1 4x3]
dynamic_1506 [md5($u.:XDB:.$p) (Oracle 12c "H" hash) 128/128 SSE4.1 4x3]
dynamic_1550 [md5($u.:mongo:.$p) (MONGODB-CR system hash) 128/128 SSE4.1 4x3]
```

This format has fixed length of salt and no info about allowed length of username:
```
dynamic_1551 [md5($s.$u.(md5($u.:mongo:.$p)) (MONGODB-CR network hash) 128/128 SSE4.1 4x3]
```

I guess `dynamic_1551` should be disabled (temporarily?) in favor of slower `dynamic_1552` without overflows. But I don't know how.

Should I disable `dynamic_1551` commenting it out completely? Or should I mark it as disabled so it could be enabled with `--format=`? The second variant seem weak: it is easy to enable a disabled format inadvertently (e.g. with `--format=-asdf`).

Also I might add commits with fixes of typos in comments and documentation into this PR.

**Comment by solardiz** [comment]
@AlekseyCherepanov I have no time to dive into this. If you need someone's input before we merge this, then let's see if anyone else hopefully comments. If this is ready to merge as-is (and your questions here are to be addressed or not separately), let me know. Thanks!

**Comment by solardiz** [comment]
@AlekseyCherepanov What's the current status of this PR?

**Comment by AlekseyCherepanov** [comment]
Now `dynamic_1551` is the only predefined dynamic crashing.

The only question: should I fix it?

I could disable it or add very specific code into `valid` just for this particular format until there would be a better solution.

**Comment by AlekseyCherepanov** [comment]
I added checks of length in the crashing appending functions. So `dynamic_1551` does not crash, instead it works incorrectly for too long usernames.

`--format=dynamic,disabled --test=0` is ok. I did not test speeds though.

The fix seems good enough to fix crash. But I dislike it: it should be rejected in `valid`. Also I would say that skipping appending could produce incorrect crack, but it seems that structure of `dynamic_1551` does not allow it.

**Comment by AlekseyCherepanov** [comment]
Fixed typo in commit message.

**Comment by solardiz** [comment]
OK, is this ready to merge (once CI is happy again)?

**Comment by AlekseyCherepanov** [comment]
Added insufficient fixes to `dynamic_fmt.c` and `dynamic_preloads.c`.

This PR is ready.

**Comment by AlekseyCherepanov** [comment]
> (16 is max for safe `$u` in the first concatenation)

That's incorrect. Max is 25. Also there is a comment in `dynamic.conf`:
```
MaxInputLen=23
MaxInputLenX86=110
# note, saltlen + length(:mongo:) + length(plain) must stay <= 55 for SIMD
#   so 25+7+23 == 55
```

**Pull request merged**
