### PR TITLE
'rain' final

### PR DESCRIPTION
**Pull request by e2002e**
Hi, I had some time since my series of pull request where nothing was working.
This is serious mangling, not dumb. It falls on it's paws like a cat, meaning no losses no duplicates.
I also took the task of making the restoring of sessions not just fail when the counter has reached over the size of what is printable/scanable with available C functions.
So this is all done. Take it or ignore it ;)

### CODE REVIEW

**Comment by magnumripper** [comment]
We wont merge this anyway until there's proven merit (or otherwise interesting, alas, tut mir leid it's not) BUT as a general advice you should rebase your work onto our current(-ish) code before making a PR (it's not even mergeble as-is!) and you should also squash it all down to, like, a single commit with a good commit description.

**Comment by e2002e** [comment]
Magnum, thanks for replying. As I described in my latest tests, the algorithm seems to be compatible with incremental since it does find a good load of hashes when run afterward.
Also, correct me if i'm wrong, the incremental doesn't handle opencl for the generation and needs the -mask option on vary fast format and/or powerful rigs, this make it loose it's advantage over rain and I ended up cracking more keys with the latest. I know the correct answer is that the work should be done on inc.
I rebased it so you can take it from here.

**Comment by magnumripper** [comment]
You didn't rebase it - there's still conflicts. Also, there's 147 commits that should better be squashed into a single one.

**Comment by e2002e** [comment]
I took me 3 hours to rebase it. Thanks for the apprenticeship...

**Comment by solardiz** [comment]
To give this the benefit of the doubt, I just ran some tests. I took the HITB v7 set from https://haveibeenpwned.com/Passwords in the form of NTLM hashes, "ordered by hash", and extracted first 10 million hashes from there. This gives non-random hashes (since the hash list is, as stated, "ordered by hash", while I extracted only a portion of it), but I think a representative sample of the corresponding plaintext passwords (assuming no correlation between password complexity and NTLM hash values). (Ideally, I'd have run `shuf` on the whole 22 GB text file, but it'd take a while and I expect the results wouldn't differ much.)

Here's testing of rain vs. incremental vs. incremental+rain with lowercase-only on one Sandy Bridge core:

```
$ ./john -rain=abcdefghijklmnopqrstuvwxyz -max-run-time=60 -form=nt -verb=1 ~/hibp/pp-by-hash-10m
Using default input encoding: UTF-8
Loaded 10000000 password hashes with no different salts (NT [MD4 128/128 AVX 4x3])
Press 'q' or Ctrl-C to abort, almost any other key for status
5g 0:00:00:00 12.15% (2) (ETA: 18:31:00) 21.73g/s 1669p/s 1669c/s 16695MC/s y..efdcb
45g 0:00:00:00 0.14% (3) (ETA: 18:31:00) 195.6g/s 43826p/s 43826c/s 100799MC/s utvxad..aabbdgkpvcjr
518g 0:00:00:00 0.01% (4) (ETA: 18:31:00) 1786g/s 850758p/s 850758c/s 2467GC/s wvwyywriubbug..dddeczulxeexjm
5557g 0:00:00:01 0.00% (5) (ETA: 2020-12-10 05:17) 3139g/s 3366Kp/s 3366Kc/s 59571GC/s vuvwyaeoiqsudau..ddddeeismu
28587g 0:00:00:38 0.00% (6) (ETA: 2027-09-07 17:18) 739.8g/s 3702Kp/s 3702Kc/s 37582GC/s vuvwxzzvhzk..dddddecxjblucb
31114g 0:00:01:04 25.84% (6) (ETA: 18:35:07) 486.0g/s 3433Kp/s 3433Kc/s 34270GC/s pdzrcqn..uiewhvsutry
Session stopped (max run-time reached)
```

```
$ ./john -inc=lower -max-run-time=60 -progress=10 -form=nt -verb=1 ~/hibp/pp-by-hash-10m
Using default input encoding: UTF-8
Loaded 10000000 password hashes with no different salts (NT [MD4 128/128 AVX 4x3])
Press 'q' or Ctrl-C to abort, almost any other key for status
143176g 0:00:00:10  14175g/s 21553Kp/s 21553Kc/s 215540GC/s nkhwej..nkhsih
188619g 0:00:00:20  9384g/s 21242Kp/s 21242Kc/s 210655GC/s immdws..immwbp
215638g 0:00:00:30  7164g/s 21078Kp/s 21078Kc/s 208215GC/s aumotemme..aumotorto
239023g 0:00:00:40  5960g/s 21104Kp/s 21104Kc/s 207911GC/s babbjohm..babbjorn
261915g 0:00:00:50  5228g/s 21395Kp/s 21395Kc/s 210272GC/s khenugot..khenmkii
278090g 0:00:01:00  4609g/s 21217Kp/s 21217Kc/s 209023GC/s ivwmumx..ivwmcad
278090g 0:00:01:00  4606g/s 21203Kp/s 21203Kc/s 209023GC/s ivwmumx..ivwmcad
Session stopped (max run-time reached)

# saved john.pot here

$ ./john -rest
Loaded 10000000 password hashes with no different salts (NT [MD4 128/128 AVX 4x3])
Remaining 9721910 password hashes with no different salts
Proceeding with incremental:lower
Press 'q' or Ctrl-C to abort, almost any other key for status
278090g 0:00:01:03  4414g/s 20318Kp/s 20318Kc/s 199069GC/s ivwmumo
297256g 0:00:01:13  4072g/s 20557Kp/s 20557Kc/s 201154GC/s myalunale..myalundme
308209g 0:00:01:23  3713g/s 20680Kp/s 20680Kc/s 202126GC/s ihralugia..ihraluian
315809g 0:00:01:33  3395g/s 20665Kp/s 20665Kc/s 201786GC/s aikyabbyl..aikyabyoo
333775g 0:00:01:46  3148g/s 20097Kp/s 20097Kc/s 196066GC/s bummbalin..bummbabby
345936g 0:00:01:56  2982g/s 20202Kp/s 20202Kc/s 196915GC/s charnatz..charnesg
354624g 0:00:02:06  2814g/s 20232Kp/s 20232Kc/s 197044GC/s spcccbll..spcclnow
354624g 0:00:02:06  2814g/s 20232Kp/s 20232Kc/s 197044GC/s spcccbll..spcclnow
Session stopped (max run-time reached)

# restored the saved john.pot here

$ ./john -rain=abcdefghijklmnopqrstuvwxyz -max-run-time=60 -form=nt -verb=1 ~/hibp/pp-by-hash-10m
Using default input encoding: UTF-8
Loaded 10000000 password hashes with no different salts (NT [MD4 128/128 AVX 4x3])
Remaining 9721910 password hashes with no different salts
Press 'q' or Ctrl-C to abort, almost any other key for status
4g 0:00:00:00 12.15% (2) (ETA: 18:41:04) 21.05g/s 2021p/s 2021c/s 19648MC/s y..efdcb
6g 0:00:00:00 0.14% (3) (ETA: 18:41:04) 31.57g/s 53052p/s 53052c/s 97996MC/s utvxad..aabbdgkpvcjr
7g 0:00:00:00 0.01% (4) (ETA: 18:41:04) 28.00g/s 986880p/s 986880c/s 2398GC/s wvwyywriubbug..dddeczulxeexjm
49g 0:00:00:01 0.00% (5) (ETA: 2020-12-10 05:27) 28.99g/s 3525Kp/s 3525Kc/s 57931GC/s vuvwyaeoiqsudau..ddddeeismu
953g 0:00:00:37 0.00% (6) (ETA: 2027-07-04 20:41) 25.31g/s 3799Kp/s 3799Kc/s 37585GC/s vuvwxzzvhzk..dddddecxjblucb
1386g 0:00:01:00 27.49% (6) (ETA: 18:44:42) 23.01g/s 3730Kp/s 3730Kc/s 36406GC/s kwgbkgarcn..lxhclhbsdo
Session stopped (max run-time reached)
```

Similar tests with default (unrestricted) charsets:

```
$ ./john -rain -max-run-time=60 -form=nt -verb=1 ~/hibp/pp-by-hash-10m
Using default input encoding: UTF-8
Loaded 10000000 password hashes with no different salts (NT [MD4 128/128 AVX 4x3])
Press 'q' or Ctrl-C to abort, almost any other key for status
20g 0:00:00:00 0.35% (2) (ETA: 18:47:38) 133.3g/s 9600p/s 9600c/s 14399MC/s `..12
177g 0:00:00:00 0.01% (3) (ETA: 18:47:38) 983.3g/s 752533p/s 752533c/s 1354GC/s ~}0..55668bfkqxFOY)
2999g 0:00:00:03 0.00% (4) (ETA: 2021-03-21 10:14) 983.2g/s 3938Kp/s 3938Kc/s 40034GC/s _^_{{..1112
7649g 0:00:01:00 N/A 127.0g/s 3952Kp/s 3952Kc/s 39634GC/s i/;G]G..n>@L|LXd:J
Session stopped (max run-time reached)

$ ./john -inc -max-run-time=60 -progress=10 -form=nt -verb=1 ~/hibp/pp-by-hash-10m
Using default input encoding: UTF-8
Loaded 10000000 password hashes with no different salts (NT [MD4 128/128 AVX 4x3])
Press 'q' or Ctrl-C to abort, almost any other key for status
225105g 0:00:00:10  22331g/s 14211Kp/s 14211Kc/s 141194GC/s b1321st..b132036
345805g 0:00:00:20  17221g/s 17638Kp/s 17638Kc/s 173005GC/s mma267m..mma26mv
424599g 0:00:00:30  14115g/s 19112Kp/s 19112Kc/s 186062GC/s hpta3r..hpter1
488398g 0:00:00:40  12185g/s 19893Kp/s 19893Kc/s 192598GC/s jemuty7u..jemuthuk
546707g 0:00:00:50  10916g/s 20600Kp/s 20600Kc/s 198515GC/s 5filo!..5fil2g
610845g 0:00:01:00  10135g/s 20846Kp/s 20846Kc/s 200721GC/s 253b3n1..253bhut
610845g 0:00:01:00  10128g/s 20832Kp/s 20832Kc/s 200721GC/s 253b3n1..253bhut
Session stopped (max run-time reached)

# saved john.pot here

$ ./john -rest
Loaded 10000000 password hashes with no different salts (NT [MD4 128/128 AVX 4x3])
Remaining 9389155 password hashes with no different salts
Proceeding with incremental:ASCII
Press 'q' or Ctrl-C to abort, almost any other key for status
610845g 0:00:01:01  10013g/s 20597Kp/s 20597Kc/s 197431GC/s 253b3ng
662797g 0:00:01:11  9335g/s 20988Kp/s 20988Kc/s 200425GC/s brru1ld..brru1me
697178g 0:00:01:21  8607g/s 21295Kp/s 21295Kc/s 202692GC/s gtgach3..gtgacox
726162g 0:00:01:31  7979g/s 21613Kp/s 21613Kc/s 205115GC/s 0163654188..0163651289
757104g 0:00:01:41  7496g/s 21749Kp/s 21749Kc/s 205873GC/s 282gds!..282g1f6
779435g 0:00:01:51  7021g/s 21818Kp/s 21818Kc/s 206052GC/s sebcal86..sebcastu
796877g 0:00:02:01  6585g/s 21831Kp/s 21831Kc/s 205756GC/s rlbox6x..rlboxm5
796877g 0:00:02:01  6585g/s 21831Kp/s 21831Kc/s 205756GC/s rlbox6x..rlboxm5
Session stopped (max run-time reached)

# restored the saved john.pot here

$ ./john -rain -max-run-time=60 -form=nt -verb=1 ~/hibp/pp-by-hash-10m
Using default input encoding: UTF-8
Loaded 10000000 password hashes with no different salts (NT [MD4 128/128 AVX 4x3])
Remaining 9389155 password hashes with no different salts
Press 'q' or Ctrl-C to abort, almost any other key for status
16g 0:00:00:00 0.35% (2) (ETA: 18:46:14) 106.6g/s 9600p/s 9600c/s 13520MC/s `..12
89g 0:00:00:00 0.01% (3) (ETA: 18:46:14) 494.4g/s 752533p/s 752533c/s 1271GC/s ~}0..55668bfkqxFOY)
1545g 0:00:00:03 0.00% (4) (ETA: 2021-03-21 10:12) 506.5g/s 3938Kp/s 3938Kc/s 37591GC/s _^_{{..1112
3233g 0:00:01:00 N/A 53.71g/s 3948Kp/s 3948Kc/s 37181GC/s [i<+Nr..\j=,OsZyl2QV|
Session stopped (max run-time reached)
```

As you can see, rain performs a lot worse in all of these tests, and especially when incremental mode isn't "crippled" by restricting it to lowercase-only.

Now I recall @e2002e mentioned testing with length 15 passwords. Let's try some of that:

```
$ ./john -rain=abcdefghijklmnopqrstuvwxyz -max-run-time=60 -progress=10 -form=nt -verb=1 -min-len=15 -max-len=15 ~/hibp/pp-by-hash-10m 
Using default input encoding: UTF-8
Loaded 10000000 password hashes with no different salts (NT [MD4 128/128 AVX 4x3])
Press 'q' or Ctrl-C to abort, almost any other key for status
1g 0:00:00:10  (15) 0.09920g/s 2656Kp/s 2656Kc/s 26780GC/s iuossrhlztkkywo..zocczvijulzxjet
1g 0:00:00:20  (15) 0.04980g/s 2682Kp/s 2682Kc/s 26928GC/s eypsftovrfhjijw..vsddmxptmxxxute
1g 0:00:00:30  (15) 0.03324g/s 2690Kp/s 2690Kc/s 26977GC/s uorzfkmxbiuwddg..ljejlnmuvajimkl
1g 0:00:00:40  (15) 0.02495g/s 2694Kp/s 2694Kc/s 26999GC/s shvovtrmujkilsm..jciycwrjoayuvar
1g 0:00:00:50  (15) 0.01997g/s 2697Kp/s 2697Kc/s 27014GC/s qkwsefsvmsyoohb..hfjbkhrrfilywnf
1g 0:00:01:00  (15) 0.01661g/s 2695Kp/s 2695Kc/s 27037GC/s iehlyeirhjjnlsn..qnordiltijilioi
Session stopped (max run-time reached)
```

```
$ ./john -rain -max-run-time=60 -progress=10 -form=nt -verb=1 -min-len=15 -max-len=15 ~/hibp/pp-by-hash-10m
Using default input encoding: UTF-8
Loaded 10000000 password hashes with no different salts (NT [MD4 128/128 AVX 4x3])
Press 'q' or Ctrl-C to abort, almost any other key for status
1g 0:00:00:10  (15) 0.09920g/s 2646Kp/s 2646Kc/s 26679GC/s BSvJ?7DTpe^t|Y~..BTuH<3yNi6;j=M=
1g 0:00:00:20  (15) 0.04980g/s 2675Kp/s 2675Kc/s 26859GC/s pO 4,N`Gy7|G?"n..pPZ3*K\Bs0@x+Rb
1g 0:00:00:30  (15) 0.03324g/s 2687Kp/s 2687Kc/s 26943GC/s 0s}#|QH'EUtZ$Rw..0t|!_MC!xMkPTFj
1g 0:00:00:40  (15) 0.02495g/s 2693Kp/s 2693Kc/s 26984GC/s l2t;i9|OKUVrE/p..l3s/f5]IDMMht#c
1g 0:00:00:50  (15) 0.01997g/s 2697Kp/s 2697Kc/s 27008GC/s 95Yw9#?4U{U_K&e..96Xu6Z:}O@M<AV2
1g 0:00:01:00  (15) 0.01661g/s 2693Kp/s 2693Kc/s 27023GC/s `3}@6y?"<L*-*=r..':)Z/aWCRjHJFN_
Session stopped (max run-time reached)
```

Incremental mode isn't really good at this length - by default, we limit it to up to 13 except for all-digits - but for the tests below I edited `john.conf` to use length 15:

```
$ ./john -inc=lower -max-run-time=60 -progress=10 -form=nt -verb=1 -min-len=15 -max-len=15 ~/hibp/pp-by-hash-10m 
Using default input encoding: UTF-8
Loaded 10000000 password hashes with no different salts (NT [MD4 128/128 AVX 4x3])
Press 'q' or Ctrl-C to abort, almost any other key for status
0g 0:00:00:10  0g/s 17320Kp/s 17320Kc/s 174586GC/s iieoeooooaeiiaa..iieoeooooeaaaei
0g 0:00:00:20  0g/s 17457Kp/s 17457Kc/s 175271GC/s aeiaeioaiiioiaa..aeiaeioaioioaei
0g 0:00:00:30  0g/s 17520Kp/s 17520Kc/s 175667GC/s eooeeooeooeeoea..eooeeooeoooooii
0g 0:00:00:40  0g/s 17557Kp/s 17557Kc/s 175881GC/s eooiieeaeiiaaoa..eooiieeaeiooooi
0g 0:00:00:50  0g/s 17505Kp/s 17505Kc/s 175303GC/s eaaooiieiaeaaao..eaaooiieiaieooo
0g 0:00:01:00  0g/s 17381Kp/s 17381Kc/s 174245GC/s oieeaaiieoeiaao..oieeaaiieoioooo
0g 0:00:01:00  0g/s 17369Kp/s 17369Kc/s 174245GC/s oieeaaiieoeiaao..oieeaaiieoioooo
Session stopped (max run-time reached)
```

```
$ ./john -inc -max-run-time=60 -progress=10 -form=nt -verb=1 -min-len=15 -max-len=15 ~/hibp/pp-by-hash-10m 
Using default input encoding: UTF-8
Loaded 10000000 password hashes with no different salts (NT [MD4 128/128 AVX 4x3])
Press 'q' or Ctrl-C to abort, almost any other key for status
2g 0:00:00:10  0.1986g/s 17269Kp/s 17269Kc/s 173904GC/s 11aiie1aia1aa1a..11aiie1aieaa1a1
2g 0:00:00:20  0.09965g/s 17463Kp/s 17463Kc/s 175242GC/s ae1aea1i1aaiaaa..ae1aea1i1aiiee1
2g 0:00:00:30  0.06651g/s 17555Kp/s 17555Kc/s 175962GC/s eii1iii11aaaiaa..eii1iii11a11ie1
2g 0:00:00:40  0.04992g/s 17595Kp/s 17595Kc/s 176220GC/s 1aaaeai1aa1aaia..1aaaeai1aaiiii1
2g 0:00:00:50  0.03995g/s 17529Kp/s 17529Kc/s 175508GC/s eaeai1aieieaaai..eaeai1aiei1eiii
2g 0:00:01:00  0.03323g/s 17396Kp/s 17396Kc/s 174462GC/s i1e1ea1a1a1aaai..i1e1ea1a1aieiii
2g 0:00:01:00  0.03321g/s 17385Kp/s 17385Kc/s 174462GC/s i1e1ea1a1a1aaai..i1e1ea1a1aieiii
Session stopped (max run-time reached)
```

Now it's too small numbers of successful guesses for a comparison. It turns out the same one password was cracked by both rain mode runs, and it is:

```
$NT$015bc90e4a219c40bd3f853610283e7d:zzzzzzzzzzzzzzz
```

and with incremental mode the two guesses are:

```
$NT$02f4ac2528510eea4bf90889e9af83bb:a1111111aa11111
$NT$032d59f507a7e213ae1fce784380ff8c:111111aaa111111
```

All of these look like they'd be better cracked with the subsets mode. Indeed:

```
$ ./john -subsets -max-run-time=60 -progress=10 -form=nt -verb=1 -min-len=15 -max-len=15 ~/hibp/pp-by-hash-10m 
Using default input encoding: UTF-8
Loaded 10000000 password hashes with no different salts (NT [MD4 128/128 AVX 4x3])
Press 'q' or Ctrl-C to abort, almost any other key for status
63g 0:00:00:10  (15) 6.250g/s 12239Kp/s 12239Kc/s 123375GC/s ZZVZVZVZVZZVVZV..ZZVZVVZVZZVVZZV
69g 0:00:00:20  (15) 3.436g/s 12853Kp/s 12853Kc/s 129047GC/s 901190110190001..901190101190001
69g 0:00:00:30  (15) 2.293g/s 13134Kp/s 13134Kc/s 131698GC/s 0j00jj0j111j111..0j00j1j11j0j111
70g 0:00:00:40  (15) 1.746g/s 13276Kp/s 13276Kc/s 133028GC/s 000ttttt1t1t01t..000tttt1t1ttt10
70g 0:00:00:50  (15) 1.398g/s 13361Kp/s 13361Kc/s 133805GC/s 011C10111CCC000..011C1010C1C010C
70g 0:00:01:00  (15) 1.163g/s 13390Kp/s 13390Kc/s 134305GC/s 011M1M011M0M0MM..011M1M00M0MM1M1
70g 0:00:01:00  (15) 1.162g/s 13383Kp/s 13383Kc/s 134305GC/s 011M1M011M0M0MM..011M1M00M0MM1M1
Session stopped (max run-time reached)
```

The 70 guesses include the one rain's crack (all z's), but somehow do not include the two incremental mode cracks yet - I guess a longer or a restricted subsets mode run would be needed to get those as well.

For the sake of completeness, all-lowercase subsets also works better than all-lowercase rain or incremental at this test:

```
$ ./john -subsets=abcdefghijklmnopqrstuvwxyz -max-run-time=60 -progress=10 -form=nt -verb=1 -min-len=15 -max-len=15 ~/hibp/pp-by-hash-10m 
Using default input encoding: UTF-8
Loaded 10000000 password hashes with no different salts (NT [MD4 128/128 AVX 4x3])
Press 'q' or Ctrl-C to abort, almost any other key for status
29g 0:00:00:10  (15) 2.874g/s 13291Kp/s 13291Kc/s 134109GC/s bkkaakakbbbbaab..bkkaabkbbabbaka
30g 0:00:00:20  (15) 1.493g/s 13452Kp/s 13452Kc/s 135134GC/s ubaabbaubbuuubu..ubaababuuubbbuu
30g 0:00:00:30  (15) 0.9973g/s 13516Kp/s 13516Kc/s 135524GC/s aacacgaaagacagg..aacaccaggaggaaa
30g 0:00:00:40  (15) 0.7485g/s 13540Kp/s 13540Kc/s 135676GC/s qcaacqaqqaaacqq..qcaacqacqaqqaaq
30g 0:00:00:50  (15) 0.5990g/s 13555Kp/s 13555Kc/s 135773GC/s azzaaczcaccaaca..azzaacaccacacza
30g 0:00:01:00  (15) 0.4983g/s 13537Kp/s 13537Kc/s 135828GC/s daddndaannaddnn..daddnannndnadad
30g 0:00:01:00  (15) 0.4980g/s 13528Kp/s 13528Kc/s 135828GC/s daddndaannaddnn..daddnannndnadad
Session stopped (max run-time reached)
```

And lowercase+digits subsets to have a better chance to catch the two incremental mode cracks within 1 minute:

```
$ ./john -subsets=abcdefghijklmnopqrstuvwxyz0123456789 -max-run-time=60 -progress=10 -form=nt -verb=1 -min-len=15 -max-len=15 ~/hibp/pp-by-hash-10m 
Using default input encoding: UTF-8
Loaded 10000000 password hashes with no different salts (NT [MD4 128/128 AVX 4x3])
Press 'q' or Ctrl-C to abort, almost any other key for status
57g 0:00:00:10  (15) 5.649g/s 13271Kp/s 13271Kc/s 133910GC/s abbbbababaaajjb..abbbbabaajbbaja
58g 0:00:00:20  (15) 2.887g/s 13494Kp/s 13494Kc/s 135553GC/s attbtbaataabata..attbtatbaabaata
58g 0:00:00:30  (15) 1.927g/s 13566Kp/s 13566Kc/s 136072GC/s aaa3a333aa33bb3..aaa3a33ba3a3b33
58g 0:00:00:40  (15) 1.446g/s 13605Kp/s 13605Kc/s 136358GC/s cacfaafccfcaacc..cacfaafaccccacf
58g 0:00:00:50  (15) 1.158g/s 13624Kp/s 13624Kc/s 136465GC/s cpapcacappcpcac..cpapcacaapccppc
58g 0:00:01:00  (15) 0.9636g/s 13611Kp/s 13611Kc/s 136544GC/s azcazczczzzzzcc..azcaczzczczczzz
58g 0:00:01:00  (15) 0.9631g/s 13604Kp/s 13604Kc/s 136544GC/s azcazczczzzzzcc..azcaczzczczczzz
Session stopped (max run-time reached)
```

And there they are, among others:

```
$ fgrep 111111 john.pot
$NT$032d59f507a7e213ae1fce784380ff8c:111111aaa111111
$NT$02f4ac2528510eea4bf90889e9af83bb:a1111111aa11111
$NT$00b0511d91bbf484a3d47a7222695bea:111111111111qqq
$NT$03d20614c558a0ec3427155eeefd7ba8:wwwwwwww1111111
$NT$0105c1d5ff67f4a7f2f59b8ca9d8b796:111111110000000
$NT$01d874b559a98adccfbd4d0cf80d591f:111111111222222
```

I do have some thoughts on a let's call it lottery mode, which would try to minimize the chances of hitting the same candidate passwords that other independent competitors have presumably tested, yet wouldn't be totally unreasonable. Rain mode may be viewed as something of this kind, but I think it's not good enough even for that obscure purpose. If I'm ever in the mood and have time, I might try implementing a better lottery mode, the testing of which would involve (among other things) seeing mostly non-overlapping sequences of passwords generated for the different players.

I think we're done discussing rain. I think merging rain into the tree would be of overall negative value: it'd add more confusion and distraction than useful functionality. So it's hereby politely rejected. Thanks!

**Comment by e2002e** [comment]
It is right, this is a last resort technique which doesn't target human
passwords.
Thanks for the tests, also you forgot to write the numbers of cracked keys !
Farewell.

**Comment by solardiz** [comment]
> you forgot to write the numbers of cracked keys

They're in the final status lines, e.g. `31114g` for the first rain run.

**Comment by solardiz** [comment]
Not really on rain (so a bit of off-topic for this PR's comments, sorry), but clarifying/updating my testing (vs. rain) that I described in a previous comment here (thus, relevant to here):

BTW, incremental mode isn't inherently that bad at length 15 - it just wasn't good enough at lengths higher than 13 in our testing so we excluded detailed information for lengths 14 and higher from the .chr files we distribute with JtR, for quicker downloads. Here's a test with this information included:

```
$ sed 's/^/:/' < rockyou.txt > fake.pot
$ ./john -make=custom.chr -pot=fake.pot
Loaded 14344391 plaintexts
Remaining 14344390 plaintexts
Generating charsets........................ DONE
Generating cracking order..---------------------------------------------------- Stable order (54 recalculations)
Successfully wrote charset file: custom.chr (214 characters)
```

An extra (undesirable) difference from how we had generated the included .chr files is that we had used the full RockYou list with any duplicate lines intact, whereas in the above I used the frequency-sorted list of unique passwords only (whatever I had handy). Anyway, it does perform better than not having this information at all:

```
$ ./john -inc=custom -max-run-time=60 -progress=10 -form=nt -min-len=15 -max-len=15 ~/hibp/pp-by-hash-10m 
Using default input encoding: UTF-8
Loaded 10000000 password hashes with no different salts (NT [MD4 128/128 AVX 4x3])
Warning: no OpenMP support for this hash type, consider --fork=32
Warning: only 214 characters available
Press 'q' or Ctrl-C to abort, almost any other key for status
andresalexander  (?)     
allanteamomucho  (?)     
michaelanatalie  (?)     
alexandresantos  (?)     
4g 0:00:00:10  0.3964g/s 17053Kp/s 17053Kc/s 172070GC/s alanandrendaver..alanandrenantic
christina122532  (?)     
christopher1978  (?)     
christopher2025  (?)     
marisarodriguez  (?)     
michellesantana  (?)     
9g 0:00:00:20  0.4479g/s 17265Kp/s 17265Kc/s 173430GC/s samareenamathan..samareenandeval
anthonylovessam  (?)     
10g 0:00:00:30  0.3323g/s 17422Kp/s 17422Kc/s 174748GC/s arteria10210189..arteria10203991
crystalorange12  (?)     
amistosamente12  (?)     
12g 0:00:00:40  0.2993g/s 17473Kp/s 17473Kc/s 175132GC/s arthoterastinda..arthoterastasos
12g 0:00:00:50  0.2396g/s 17551Kp/s 17551Kc/s 175791GC/s adiosamisaniero..adiosamisantath
12g 0:00:01:00  0.1993g/s 17554Kp/s 17554Kc/s 176154GC/s strombonesaster..strombonesa1492
12g 0:00:01:00  0.1991g/s 17542Kp/s 17542Kc/s 176154GC/s strombonesaster..strombonesa1492
Use the "--show --format=NT" options to display all of the cracked passwords reliably
Session stopped (max run-time reached)
```

2 of the 12 cracked passwords were present in the RockYou list:

```
$ cut -d: -f2- john.pot | fgrep -xf - rockyou.txt
alexandresantos
allanteamomucho
```

So this gives us 10 new cracks that simply running the RockYou list against the hashes wouldn't crack. This isn't as effective as the subsets mode, but all of the cracks are different, so these two modes are good to be used together.

Speaking of file size, I notice the generated `custom.chr` is of very similar size to `utf8.chr` that we do include in jumbo (I didn't have that in core):

```
-rw-------. 1 solar solar 9288427 Dec  8 13:33 custom.chr
```

```
-rw-------. 1 solar solar 5720262 Dec  7 18:16 ascii.chr
-rw-------. 1 solar solar 7449800 Dec  7 18:16 latin1.chr
-rw-------. 1 solar solar 9286825 Dec  7 18:16 utf8.chr
```

Trying that instead somehow cracks 10 passwords:

```
$ ./john -inc=utf8 -max-run-time=60 -progress=10 -form=nt -min-len=15 -max-len=15 ~/hibp/pp-by-hash-10m 
Using default input encoding: UTF-8
Loaded 10000000 password hashes with no different salts (NT [MD4 128/128 AVX 4x3])
Warning: no OpenMP support for this hash type, consider --fork=32
Press 'q' or Ctrl-C to abort, almost any other key for status
andresalexander  (?)     
allanteamomucho  (?)     
cheekymonkey102  (?)     
christopher1978  (?)     
christopher2025  (?)     
michaelanatalie  (?)     
christina122532  (?)     
7g 0:00:00:10  0.6951g/s 16750Kp/s 16750Kc/s 168678GC/s angromilovesica..angromilovarier
alexandresantos  (?)     
8g 0:00:00:20  0.3986g/s 17152Kp/s 17152Kc/s 172121GC/s matheareteanies..mathearetessexa
8g 0:00:00:30  0.2660g/s 17250Kp/s 17250Kc/s 172904GC/s sentellendanday..sentellenden186
crystalorange12  (?)     
9g 0:00:00:40  0.2246g/s 17277Kp/s 17277Kc/s 173029GC/s assswenelas1992..assswenelass156
marlonisthebest  (?)     
10g 0:00:00:50  0.1997g/s 17376Kp/s 17376Kc/s 173977GC/s amoartantoder12..amoartantodinan
10g 0:00:01:00  0.1661g/s 17450Kp/s 17450Kc/s 175024GC/s stupiromaincess..stupiromainguay
10g 0:00:01:00  0.1660g/s 17441Kp/s 17441Kc/s 175024GC/s stupiromaincess..stupiromainguay
Use the "--show --format=NT" options to display all of the cracked passwords reliably
Session stopped (max run-time reached)
```

2 of these 10 were not cracked with `custom.chr`:

```
$ fgrep -vxf john.pot-custom john.pot
$NT$03f1b3cc70bf8733081c1ce5f74b4c12:cheekymonkey102
$NT$0137d4b84f3d4dd37a75529093ddabbd:marlonisthebest
```

but 3 of the 10 (including 1 of 2 above) are in RockYou:

```
$ cut -d: -f2- john.pot | fgrep -xf - rockyou.txt
alexandresantos
cheekymonkey102
allanteamomucho
```

I guess it's the effects of (not) including the duplicate RockYou lines when generating the .chr files. We might want to run longer tests for lengths 14+ to determine whether it's best to include or exclude duplicate lines when generating .chr files for such lengths.

`latin1` cracks the same 10 that `utf8` does.

I guess we should add a comment somewhere near the incremental mode definitions in `john.conf` that for lengths beyond 13 people shouldn't simply edit `MaxLen`, but should use these alternative predefined modes instead. Alternatively, we should include detailed statistics for all lengths in all of our .chr files.

As yet another alternative, we could try filtering to the desired charset at .chr file load time (with extra code in `inc.c`) rather than when generating them. This would include statistics from substrings in passwords that didn't fully match the restricted charset, which has both pros (more data) and cons (the extra data is less relevant), resulting in non-obvious overall effect. I guess this is something for me to experiment with when making other updates to incremental mode later.

An unrelated observation I made when running these tests is that `-max-run-time=60 -progress=10` produces almost-duplicate final line, I guess because 60 is a multiple of 10. Perhaps we should add a check to suppress this duplicate.

**Comment by magnumripper** [comment]
> Speaking of file size, I notice the generated `custom.chr` is of very similar size to `utf8.chr` that we do include in jumbo (I didn't have that in core):
> 
> Trying that instead somehow cracks 10 passwords:
> 
> 2 of these 10 were not cracked with `custom.chr`:
> 
> I guess it's the effects of (not) including the duplicate RockYou lines when generating the .chr files. We might want to run longer tests for lengths 14+ to determine whether it's best to include or exclude duplicate lines when generating .chr files for such lengths.

Actually I believe the utf8.chr was made with a filter length of 24 instead of 13, to accommodate for multi-byte stuff. I can't remember the details but it may have been produced in a way that allowed up to 24 ASCII-characters (the size do indicate that).

**Comment by e2002e** [comment]
Hi sir, please check my fork at https://github.com/e2002e/john
You must checkout on 'rain', what I did is tweaking the mask so that there
is deep mangling and alteration of lengths.
I actually beg you to not let my 5 years of hard working be in vain:
If you give it a run you'll find out that it cracks less passwords than the
standard mode because the overall speed is divided by maxlength -
mask_cur_len,
but finds longer one.

**Pull request closed without merging**
