### PR TITLE
Update URLs for GitHub repository transfer to Openwall org

### PR DESCRIPTION
**Pull request by solardiz**
This is the result of:

```shell
sed -i s,github.com/magnumripper/JohnTheRipper,github.com/openwall/john,g `fgrep -rl github.com/magnumripper src/`
sed -i s,github.com/magnumripper/JohnTheRipper,github.com/openwall/john,g `fgrep -rl github.com/magnumripper doc/`
sed -i s,github.com/magnumripper/JohnTheRipper,github.com/openwall/john,g README.md
```

and some manual edits of `README.md`.

There are still CI-specific mentions of magnumripper left in `README.md`. I'd appreciate @claudioandre-br's help on those.

### CODE REVIEW

**Comment by solardiz** [comment]
CI doesn't even start on this - I guess it's broken. Claudio, do you want to try and repair CI with this same PR?

As admin, I can merge this PR now anyway, despite of no CI. We can try and repair CI with this PR or separately.

**Comment by ghost** [comment]
If you need this merged, please, merge. 

I found the build on Circle. But I can't find any builds on Travis. 
Travis org has some repositories (not john) at https://travis-ci.org/github/openwall

**Comment by solardiz** [comment]
OK, I'll merge this and let's plan to figure CI out separately.

**Comment by solardiz** [comment]
Claudio, why is it that Travis has all of Openwall org repos except john? Is this somehow related to us using Travis for this repo before the move?

Perhaps these links need to be somehow updated, but I don't know what to update them to:

```
[![Build Status](https://travis-ci.com/magnumripper/JohnTheRipper.svg?branch=bleeding-jumbo)](https://travis-ci.com/magnumripper/JohnTheRipper)
[![Circle CI](https://circleci.com/gh/magnumripper/JohnTheRipper/tree/bleeding-jumbo.svg?style=shield)](https://circleci.com/gh/magnumripper/JohnTheRipper/tree/bleeding-jumbo)
```

**Comment by ghost** [comment]
> Claudio, why is it that Travis has all of Openwall org repos except john? 

Probably because it was using Travis.com (not .org). As you can see below, only admins can enable repositories, view organization settings, ..., ... inside CI providers.

WHAT! error message:
Captura de tela de 2020-08-18 19-47-14

I am the repository administrator (not yet authorized).
Captura de tela de 2020-08-18 19-45-24

**Comment by solardiz** [comment]
Claudio, should I make any particular change or grant you extra access to the john repo or to Openwall org to help  repair this?

**Comment by solardiz** [comment]
The john repo appeared on https://travis-ci.org/github/openwall now, but somehow shows last build from 2 years ago.

**Comment by solardiz** [comment]
Circle now has recent builds at https://circleci.com/gh/openwall/john/tree/bleeding-jumbo but it says in there "This UI will no longer be accessible as of August 14, 2020. Read More about this change, or Switch to the New UI now." Clicking "Switch to the New UI" brings me to a page asking to authorize Circle's access to my personal account and to an unrelated org I'm a member of, but not to Openwall org. Weird.

Travis is in fact confused by .com vs. .org, but I don't know how to fix that. https://travis-ci.org/github/openwall/john says "This repository was migrated and is now building on travis-ci.com" and "Take me there!", clicking which brings me to https://travis-ci.com/openwall/john, which says " We couldn't display the repository openwall/john" and "This repository may not exist or you may need to Sign in". Singing in as solardiz and authorizing the app results in the same error message again, and a button "Sign in with another account". I guess I should look more carefully into granting access specifically to the Openwall org.

**Comment by solardiz** [comment]
I seem to have managed to authorized Travis to access the Openwall org, now I see builds until "phpass-opencl: specialized code ..." in my dashboard there. However, the Travis .com URL above still displays the same error.

**Comment by solardiz** [comment]
There's also https://travis-ci.com/github/openwall/JohnTheRipper, which says " This is not an active repository" and "You don't have sufficient rights to enable this repo on Travis. Please contact the admin to enable it or to receive admin rights yourself."

I guess the repo rename from JohnTheRipper to john might have confused Travis. Maybe it doesn't know how to handle both a repo transfer and a rename when both happen almost at once.

**Pull request merged**
