### PR TITLE
formats.c: Bug fixes for wildcard matching

### LINKED ISSUE #5053: crash with `--format=*-jo --list=formats` when in ASan build (read)
Crash with `--format=*-jo --list=formats` with asan:
```
$ ./john/run/john '--format=*-jo' --list=formats
=================================================================
==86700==ERROR: AddressSanitizer: global-buffer-overflow on address 0x55591eed1eff at pc 0x7faf5315fd54 bp 0x7ffe8bd74450 sp 0x7ffe8bd73c00
READ of size 1 at 0x55591eed1eff thread T0
    #0 0x7faf5315fd53 in __interceptor_strcasecmp ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:511
    #1 0x55591ed02019 in fmt_match /home/user/john/src/formats.c:157
    #2 0x55591ed1082d in john_register_one /home/user/john/src/john.c:206
    #3 0x55591ed1278a in john_register_all /home/user/john/src/john.c:251
    #4 0x55591ed1278a in john_init /home/user/john/src/john.c:1563
    #5 0x55591ed1278a in main /home/user/john/src/john.c:2065
    #6 0x7faf52a24d09 in __libc_start_main ../csu/libc-start.c:308
    #7 0x55591e81d1f9 in _start (/home/user/john/run/john+0x1f31f9)

0x55591eed1eff is located 46 bytes to the right of global variable '*.LC2' defined in 'LM_fmt.c' (0x55591eed1ec0) of size 17
  '*.LC2' is ascii string 'aad3b435b51404ee'
0x55591eed1eff is located 1 bytes to the left of global variable '*.LC3' defined in 'LM_fmt.c' (0x55591eed1f00) of size 3
  '*.LC3' is ascii string 'LM'
SUMMARY: AddressSanitizer: global-buffer-overflow ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:511 in __interceptor_strcasecmp
Shadow bytes around the buggy address:
  0x0aaba3dd2380: f9 f9 f9 f9 00 00 00 00 02 f9 f9 f9 f9 f9 f9 f9
  0x0aaba3dd2390: 00 05 f9 f9 f9 f9 f9 f9 00 00 06 f9 f9 f9 f9 f9
  0x0aaba3dd23a0: 00 00 00 06 f9 f9 f9 f9 00 01 f9 f9 f9 f9 f9 f9
  0x0aaba3dd23b0: 00 00 00 02 f9 f9 f9 f9 00 04 f9 f9 f9 f9 f9 f9
  0x0aaba3dd23c0: 00 00 06 f9 f9 f9 f9 f9 00 00 00 f9 f9 f9 f9 f9
=>0x0aaba3dd23d0: 05 f9 f9 f9 f9 f9 f9 f9 00 00 01 f9 f9 f9 f9[f9]
  0x0aaba3dd23e0: 03 f9 f9 f9 f9 f9 f9 f9 01 f9 f9 f9 f9 f9 f9 f9
  0x0aaba3dd23f0: 00 00 01 f9 f9 f9 f9 f9 00 00 05 f9 f9 f9 f9 f9
  0x0aaba3dd2400: 07 f9 f9 f9 f9 f9 f9 f9 00 00 05 f9 f9 f9 f9 f9
  0x0aaba3dd2410: 00 f9 f9 f9 f9 f9 f9 f9 00 00 05 f9 f9 f9 f9 f9
  0x0aaba3dd2420: 00 f9 f9 f9 f9 f9 f9 f9 00 00 05 f9 f9 f9 f9 f9
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==86700==ABORTING
```

`--format=*-opencl` fails too, so it is not specific to non-existent format names. `*md5` crashes. `*d5` works.

The backtrace resembles one in #5052 partially.

### PR DESCRIPTION
**Pull request by magnumripper**
Closes #5053

### CODE REVIEW

**Comment by magnumripper** [comment]
I noticed `n*t` would match NT, which it wasn't supposed to. Should be fine now:

`n*` matches NT (and others)
`*t` matches NT (and others)
`n*t` does not match NT
`p*t` does match the PST format.

ASAN is happy for all cases.

**Comment by AlekseyCherepanov** [comment]
`/* We don't want n*t to match NT */` -- are you sure? Maybe it would be practical. In theory `*` is zero or more chars usually. Also it seems inconsistent with trailing `*`: `*nt` would not find `nt` while `nt*` would find `nt`. (I did not try it really. So I might misinterpret something.)

**Comment by magnumripper** [comment]
> `/* We don't want n*t to match NT */` -- are you sure? Maybe it would be practical. In theory `*` is zero or more chars usually. Also it seems inconsistent with trailing `*`: `*nt` would not find `nt` while `nt*` would find `nt`. (I did not try it really. So I might misinterpret something.)

OK, maybe I should revert that. I thought `ls n*t` would not list a file named `nt`, but it does.

**Comment by magnumripper** [comment]
Reverted to first version. The below is with ASAN:
```
$ ./john -list=formats -format=jo-*
Error: No format matched requested wildcard 'jo-*'

$ ./john -list=formats -format=nt*
NT, NT-opencl, ntlmv2-opencl
3 formats

$ ./john -list=formats -format=*nt
NT
1 formats

$ ./john -list=formats -format=n*t
NT
1 formats
```

**Comment by AlekseyCherepanov** [comment]
I guess `*asdf` finds `nt` too because `label_len` is less than `wild_len`.

The second version was good except for `- 1`. Check `(label_len - pre_len < trail_len)` would mean that `nt*nt` would not find `nt`.

**Comment by magnumripper** [comment]
Ouch, you are right. Fixed now.

**Comment by AlekseyCherepanov** [comment]
I tried. It seems good.

I am not sure about `int` for result of `strlen`. With string of `INT_MAX + 1` chars there would be a negative number. For `trail_len` negative value is bad. OTOH on linux, there is fixed limit on size of single argument ([131072 bytes](https://unix.stackexchange.com/questions/120642/what-defines-the-maximum-size-for-a-command-single-argument)).

**Pull request merged**
