### PR TITLE
Incremental: Allow supplying a charset file as "mode"

### PR DESCRIPTION
**Pull request by magnumripper**
This lets you use eg. --inc=temp.chr without any entry in john.conf

### CODE REVIEW

**Comment by frank-dittrich** [comment]
You could also adjust this john.conf part (adding a comment that .chr files can be used directly instead of a mode):
```
# This is for one-off uses (make your own custom.chr)
[Incremental:Custom]
File = $JOHN/custom.chr
MinLen = 0
```

**Comment by frank-dittrich** [comment]
Should I adjust bash completion to add all existing .chr files (and all names of subdirectories where might be some .chr files)
Especially including subdirectories could be confusing.

**Review by solardiz — APPROVED** [review]

**Comment by magnumripper** [comment]
> Should I adjust bash completion to add all existing .chr files (and all names of subdirectories where might be some .chr files)
> Especially including subdirectories could be confusing.

That would be great, but not super important. You could leave out subdirs unless it was already specified, such as `--inc=dir/[tab]`

**Comment by magnumripper** [comment]
> You could also adjust this john.conf part (adding a comment that .chr files can be used directly instead of a mode):
> 
> ```
> # This is for one-off uses (make your own custom.chr)
> [Incremental:Custom]
> File = $JOHN/custom.chr
> MinLen = 0
> ```

That's a good point. I didn't want to drop this but the comment could be amended.

**Comment by magnumripper** [comment]
> > Should I adjust bash completion to add all existing .chr files (and all names of subdirectories where might be some .chr files)
> > Especially including subdirectories could be confusing.

The more I think about this, the messier it gets. We wouldn't want to list `.chr` files that *have* a section. Probably best to just leave it alone.

**Pull request merged**
