### PR TITLE
Fix-up NSEC3 and Cardano; Fix mscash2 scalar --without-openssl

### PR DESCRIPTION
**Pull request by solardiz**
This is a follow-up on #5188 and #5187. Edit: and fix for #5190.

@anonion0 and @ilap, you might want to take a look. Thanks.

### CODE REVIEW

**Comment by solardiz** [comment]
This passes basic tests in an `--enable-asan --enable-fuzz` SIMD build:

```
[solar@super run]$ time ./john -fuzz -form=nsec3,cardano
Fuzzing: nsec3, DNSSEC NSEC3 [SHA-1 32/64]...    Completed
Fuzzing: cardano, Cardano Encrypted 128-byte Secret Key (a.k.a XPrv) [PBKDF2-SHA512/BLAKE2b/ChaCha20 128/128 AVX 2x]...    Completed

All 2 formats passed fuzzing test!

real    0m20.503s
user    0m17.865s
sys     0m2.630s
[solar@super run]$ time ./john -test-full=1 -form=nsec3,cardano
Will run 32 OpenMP threads
Testing: nsec3, DNSSEC NSEC3 [SHA-1 32/64]... (32xOMP) PASS
Testing: cardano, Cardano Encrypted 128-byte Secret Key (a.k.a XPrv) [PBKDF2-SHA512/BLAKE2b/ChaCha20 128/128 AVX 2x]... (32xOMP) PASS
All 2 formats passed self-tests!

real    0m2.920s
user    0m16.467s
sys     0m0.220s
```

**Comment by solardiz** [comment]
Also passed same tests with `--enable-asan --enable-fuzz --disable-simd`.

**Comment by solardiz** [comment]
Also passed same tests with `--enable-asan --enable-fuzz --disable-simd --without-openssl`.

**Comment by solardiz** [comment]
Also passes tests on Power7 64-bit big-endian (no SIMD as, IIRC, we require Power8+ for 64-bit SIMD elements).

**Comment by anonion0** [comment]
Looks good from my side, thanks!

**Comment by ilap** [comment]
Yeah, looks good to me. Thx.

**Comment by AlekseyCherepanov** [comment]
I tested 1 build with the dictionary for fuzzing. It is ok.
```
src$ ./configure --enable-asan --disable-openmp --enable-fuzz
[...]
src$ make -s clean && make -sj4
[...]
src$ ../run/john --format='nsec3,cardano' --fuzz=../run/fuzz.dic
[...]
All 2 formats passed fuzzing test!
```

**Pull request merged**
