### PR TITLE
Fix OpenCL leak

### PR DESCRIPTION
**Pull request by ghost**
Partial fix of #4295

### CODE REVIEW

**Comment by ghost** [comment]
Something like this will be needed in a couple of places:
```
diff --git a/src/opencl_tc_fmt_plug.c b/src/opencl_tc_fmt_plug.c
index c3e7ce57c..1461a469c 100644
--- a/src/opencl_tc_fmt_plug.c
+++ b/src/opencl_tc_fmt_plug.c
@@ -156,14 +156,16 @@ static void create_clobj(size_t gws, struct fmt_main *self)
 
 static void release_clobj(void)
 {
-       HANDLE_CLERROR(clReleaseMemObject(mem_in), "Release mem in");
-       HANDLE_CLERROR(clReleaseMemObject(mem_setting), "Release mem setting");
-       HANDLE_CLERROR(clReleaseMemObject(mem_out), "Release mem out");
-
-       MEM_FREE(inbuffer);
-       MEM_FREE(outbuffer);
-       MEM_FREE(keyfiles_data);
-       MEM_FREE(keyfiles_length);
+       if (inbuffer) {
+               HANDLE_CLERROR(clReleaseMemObject(mem_in), "Release mem in");
+               HANDLE_CLERROR(clReleaseMemObject(mem_setting), "Release mem setting");
+               HANDLE_CLERROR(clReleaseMemObject(mem_out), "Release mem out");
+
+               MEM_FREE(inbuffer);
+               MEM_FREE(outbuffer);
+               MEM_FREE(keyfiles_data);
+               MEM_FREE(keyfiles_length);
+       }
 }
 
 static void done(void)

```

**Comment by ghost** [comment]
Done. 

To test I have to remove MsCash (does it use shared code or not?). Not sure what I should do.

More tests are needed, but, I would say some formats are leaking, I'm almost sure (and not because of shared code). 
The reference test (mine, at least) is sha256crypt-opencl: it has no leak.
****
I'm still testing, anyway, you guys can review and give a feedback.

**Comment by magnumripper** [comment]
Thanks, I'll have a look at this within 18h. During my debugging previously today I didn't see (using assertions) any missing call to `release_clobj()` from autotune so I'm not sure this is all there is to it.

**Comment by magnumripper** [comment]
I think the `if (inbuffer)` was present in all formats I looked at, and anyway missing that would not result in memory leaks but the opposite - trying to free already freed stuff. I *think* it's allowed to call `clReleaseMemObject()` once too much (although perhaps not clearly documented by Khronos so maybe we shouldn't depend on it) and our `MEM_FREE` macro has a safety net in place for null pointers.

**Comment by magnumripper** [comment]
OK so of your two approaches, one (this) is to add a `release_clobj()` in a single file `opencl_autotune.h` and the other (#4354) is to do it to all formats. I think I like this first one better unless you saw some caveat?

**Comment by ghost** [comment]
> add a release_clobj() in a single file opencl_autotune.h and the other (#4354) is to do it to all formats. I think I like this first one better unless you saw some caveat?

A single `release_clobj()` in `opencl_autotune.h` do not fix all leaks (it is NOT enough) .

**Comment by magnumripper** [comment]
Ah OK. Then let's close this PR and merge #4354 for a starter

**Pull request closed without merging**
