### PR TITLE
bitcoin2john.py fix and documentation update

### LINKED ISSUE #4273: bitcoin2john.py - unsupported btree version: 10
Hello! Today have an eror while tried to get hash:
unsupported btree version: 10

### PR DESCRIPTION
**Pull request by solardiz**
Fixes #4273

### CODE REVIEW

**Comment by ghost** [comment]
I tested in Docker. Since I know packaged bsddb3 is bsddb3-6.2.7, I changed it a little.

To understand what is going on:
```
sudo docker run -it -v $(pwd):/host ubuntu:20.04
```
Inside Docker
```
apt update
apt install python3 python3-pip unzip

wget https://download.oracle.com/berkeley-db/db-6.2.32.NC.tar.gz
tar xzf db-6.2.32.NC.tar.gz
cd db-6.2.32.NC/build_unix
../dist/configure --prefix /usr/local/berkeley-db/6.2.32
make install

# Probably, not needed. #####
echo YES_I_HAVE_THE_RIGHT_TO_USE_THIS_BERKELEY_DB_VERSION=1 >> /etc/environment
echo BERKELEYDB_DIR=/usr/local/berkeley-db/6.2.32 >> /etc/environment
#############################

# Ubuntu upstream version is bsddb3-6.2.7. So:
YES_I_HAVE_THE_RIGHT_TO_USE_THIS_BERKELEY_DB_VERSION=1 BERKELEYDB_DIR=/usr/local/berkeley-db/6.2.32 pip3 install bsddb3

# Because JtR is installed on host. 
cd /host
# You can also download the 2john tool.
# wget https://raw.githubusercontent.com/magnumripper/JohnTheRipper/bleeding-jumbo/run/bitcoin2john.py
#############################

wget https://openwall.info/wiki/_media/john/xdn_wallet.zip
unzip xdn_wallet.zip 

python3 bitcoin2john.py xdn_wallet.dat
$bitcoin$64$095888dbe5dfcfdb2e471f1548ccbc11842357a4faf843efbeb28e286cfbcc09$16$4261bbe00ecd71d0$178285$2$00$2$00
```

Cracking using the host machine
```
$ john bitcoin.hash 
Using default input encoding: UTF-8
Loaded 1 password hash (Bitcoin, Bitcoin Core [SHA512 AES 256/256 AVX2 4x])
Cost 1 (iteration count) is 178285 for all loaded hashes
Will run 8 OpenMP threads
Proceeding with single, rules:Single
Press 'q' or Ctrl-C to abort, almost any other key for status
Almost done: Processing the remaining buffered candidate passwords, if any.
Proceeding with wordlist:/snap/john-the-ripper/current/run/password.lst
123              (?)
1g 0:00:00:01 DONE 2/3 (2020-06-16 19:25) 0.6896g/s 22.06p/s 22.06c/s 22.06C/s 123456..maggie
Use the "--show" option to display all of the cracked passwords reliably
Session completed. 
```

**Review by ghost — APPROVED** [review]
LGTM

**Comment by solardiz** [comment]
Thanks, Claudio! I guess the changes to `/etc/environment` didn't take effect for that same shell session, which is why you had to specify those env vars on the `pip3` command line explicitly. Correct? If so, we need to update the instructions accordingly before merging this. I guess 
@deathmorlock's over-use of `sudo` happened to trigger a read of  `/etc/environment` before the invocation of `pip3`, which is why that file mattered and was sufficient. Can one of you test without the `/etc/environment` edits, but with the env vars on the `pip3` command line?

**Comment by solardiz** [comment]
Claudio, are you running _all_ of the commands as root? Because it's a container anyway? Actually, I did preserve `sudo` in `sudo python3 setup.py install`, so it probably does trigger the use of `/etc/environment` (indirectly, due to starting a new shell).

**Comment by ghost** [comment]
> Claudio, are you running _all_ of the commands as root? Because it's a container anyway? 

Yes.

**Comment by solardiz** [comment]
Claudio, why do you install `unzip`?

**Comment by ghost** [comment]
> Claudio, why do you install `unzip`?

Because of `unzip xdn_wallet.zip` (to test the demo).

**Comment by solardiz** [comment]
@claudioandre-br @deathmorlock How does this look to you both? -

```
deathmorlock and Claudio Andre provided the below instructions for Ubuntu, for 
use in a throw-away VM or container (since this messes with the system badly):

apt update
apt install python3 python3-pip 

wget https://download.oracle.com/berkeley-db/db-6.2.32.NC.tar.gz
tar xzf db-6.2.32.NC.tar.gz
cd db-6.2.32.NC/build_unix
../dist/configure --prefix /usr/local/berkeley-db/6.2.32
sudo make install

# Ubuntu upstream version is bsddb3-6.2.7. So:
YES_I_HAVE_THE_RIGHT_TO_USE_THIS_BERKELEY_DB_VERSION=1 BERKELEYDB_DIR=/usr/local/berkeley-db/6.2.32 sudo pip3 install bsddb3

Alternatively to the above command, the following was also tested:

sudo echo YES_I_HAVE_THE_RIGHT_TO_USE_THIS_BERKELEY_DB_VERSION=1 >> /etc/environment
sudo echo BERKELEYDB_DIR=/usr/local/berkeley-db/6.2.32 >> /etc/environment

wget https://files.pythonhosted.org/packages/fa/ad/eb82bcccbfb076b6a6797f48c339460699103065fb2a2fc72403b16970fe/bsddb3-6.2.7.tar.gz
tar xzf bsddb3-6.2.7.tar.gz
cd bsddb3-6.2.7
sudo python3 setup.py install
```

**Comment by ghost** [comment]
> How does this look to you both?

Tested without editing `/etc/environment`. LGTM

**Comment by solardiz** [comment]
Also added `sudo` before the `apt` commands. Force-pushed. Now waiting on CI, then will likely merge.

**Comment by deathmorlock** [comment]
Looks good :)   I am used many sudo cuz i have Ubuntu on WSL and it worked only with it

**Pull request merged**
