### PR TITLE
Workaround for broken CircleCI Ubuntu VM image

### PR DESCRIPTION
**Pull request by ghost**
Since the base image is out of date, we need to do something to fix it (or the build).

### CODE REVIEW

**Review by solardiz — APPROVED** [review]
Thank you, @claudioandre-br! This seems to have worked, although I am puzzled by the commented out `sudo apt ...` line - didn't we need to install those packages?

**Comment by ghost** [comment]
We will need to reverse this line later. Now some post-installation script is presenting an "OK" window (probably because of the OpenSSL update).

**Comment by solardiz** [comment]
How does the build succeed with the `apt` line commented out at all? `libssl-dev` is a required dependency unless we use `--without-openssl`. Is this package somehow installed anyway?

Anyhow, I don't mind just merging this without knowing more, since it's just CI and now it works.

**Comment by ghost** [comment]
> Is this package somehow installed anyway?

Yes, there is an old version installed.

**Pull request merged**
